### ISSUE TITLE
about the cityscapes_info.json

### ISSUE THREAD

**Issue by RobinHan24** [CoinCheung/BiSeNet#1]
I trained the cityscapes dataset, it worked. So how to train my own data, and how to generate my own json just like the cityscapes_info.json. Thanks a lot.

**Comment by CoinCheung** [comment]
@RobinHan24 What matters in the `cityscapes_info.json` are only the `id` and `trainid`  in each dict data structure. The `id`s are the pixel values of the label images, while the `trainid`s are the label values that the naive label image pixels should be mapped to.

If you need to train on your own dataset, you may simply assign each `trainid` with the identical value as its associated `id`. Just directly modify in my `cityscapes_info.json` would be fine. You may adjust the number of dicts in that file according to your category numbers. Hope I have made myself clear.

**Comment by RobinHan24** [comment]
> @RobinHan24 What matters in the `cityscapes_info.json` are only the `id` and `trainid` in each dict data structure. The `id`s are the pixel values of the label images, while the `trainid`s are the label values that the naive label image pixels should be mapped to.
> 
> If you need to train on your own dataset, you may simply assign each `trainid` with the identical value as its associated `id`. Just directly modify in my `cityscapes_info.json` would be fine. You may adjust the number of dicts in that file according to your category numbers. Hope I have made myself clear.

Cool, it works. But I have met another problem, the trainning loss is always 0.0000. Is there some error in my .json or my own data, can you help me? Thanks.
my .json file
[  
  {
    "hasInstances": false,
    "category": "void",
    "catid": 0,
    "name": "unlabeled",
    "ignoreInEval": true,
    "id": 0,
    "color": [
      0,
      0,
      0
    ],
    "trainId": 255
  },
{
    "hasInstances": false,
    "category": "spinning",
    "catid": 1,
    "name": "spinning",
    "ignoreInEval": false,
    "id": 10,
    "color": [
      128,
      64,
      128
    ],
    "trainId": 0
  }
]
just one class, the pixel value of this class is 10.
training data
![1_leftimg8bit](https://user-images.githubusercontent.com/12028744/51885214-80538f00-23c5-11e9-9074-f3a5c1502ca5.png)
label data
![1_gtfine_labelids](https://user-images.githubusercontent.com/12028744/51885230-94978c00-23c5-11e9-9a0e-0b41b4246aae.png)

**Comment by CoinCheung** [comment]
@RobinHan24 What do you expect the model to output given you have only one class? If you let your model have single channel output, no matter what value the logit becomes, you will pick that class. You do not cope well with a classification task like this. I guess `just one class, the pixel value of this class is 10` means you have only one foreground category, you will also need to assign a background category. Maybe you could modify you .json file like this: 
```
[
{
"hasInstances": false,
"category": "void",
"catid": 0,
"name": "unlabeled",
"ignoreInEval": true,
"id": 0,
"color": [
0,
0,
0
],
"trainId": 1
},
{
"hasInstances": false,
"category": "spinning",
"catid": 1,
"name": "spinning",
"ignoreInEval": false,
"id": 10,
"color": [
128,
64,
128
],
"trainId": 0
}
]
```

**Comment by CoinCheung** [comment]
By assigning a label pixel to be 255, you are neglecting that pixel in the training. It is not the thing of background class, which you should count in the training stage.

**Comment by RobinHan24** [comment]
> By assigning a label pixel to be 255, you are neglecting that pixel in the training. It is not the thing of background class, which you should count in the training stage.

Perfect. It works.Thanks a lot.

**Comment by CoinCheung** [comment]
I am closing this since  the problem seems to be solved for now.

**Comment by zpge** [comment]
> > By assigning a label pixel to be 255, you are neglecting that pixel in the training. It is not the thing of background class, which you should count in the training stage.
> 
> Perfect. It works.Thanks a lot.

I am also working on a dataset with only two classes(0: backgroud, 1: object). But I encountered the following error:
root@c888940eee85:/data/BiSeNet-master# CUDA_VISIBLE_DEVICES=2,3 python3 -m torch.distributed.launch --nproc_per_node=2 train.py
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    train()
  File "train.py", line 123, in train
    lossp = criteria_p(out, lb)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/zpge/BiSeNet-master/loss.py", line 22, in forward
    loss = self.criteria(logits, labels).view(-1)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 942, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    train()
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "train.py", line 123, in train
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1873, in nll_loss
    lossp = criteria_p(out, lb)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/zpge/BiSeNet-master/loss.py", line 22, in forward
    loss = self.criteria(logits, labels).view(-1)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [2, 1024, 1024, 3]
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 942, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1873, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [2, 1024, 1024, 3]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'train.py', '--local_rank=0']' returned non-zero exit status 1.

Can you help to explain how you modify the scripts for your own dataset?

**Comment by zpge** [comment]
> > By assigning a label pixel to be 255, you are neglecting that pixel in the training. It is not the thing of background class, which you should count in the training stage.
> 
> Perfect. It works.Thanks a lot.

I am faceing the same problem. In my dataset, there is only two classes: backgroud and one object. I am wondering is it a right way to set the json file as the above mentioned case. Because in my evaluation, the program give me the iou of backgroud. I think usually the iou of backgroud need not     
be calculaetd and should not included in the loss calculation.
