### ISSUE TITLE
Help！RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress： an illegal memory access was encountered

### ISSUE THREAD

**Issue by sjxmm** [CoinCheung/BiSeNet#101]
Help！RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress： an illegal memory access was encountered
I use my own data set, a total of 32 classes. Then, I changed label_info, as shown below, but this error occurred.

in cityscapes_cv2.py, I changed it like below：
labels_info = [
    {"hasInstances": False, "category": "void", "catid": 0, "name": "unlabeled", "ignoreInEval": True, "id": 0, "color": [0, 0, 0], "trainId": 255},
    {"hasInstances": True, "category": "Animal", "catid": 1, "name": "Animal", "ignoreInEval": False, "id": 1, "color": [128, 64, 128], "trainId": 0},
    {"hasInstances": True, "category": "Archway", "catid": 2, "name": "Archway", "ignoreInEval": False, "id": 2, "color": [244, 35, 232], "trainId": 1},
    {"hasInstances": True, "category": "Bicyclist", "catid": 3, "name": "Bicyclist", "ignoreInEval": False, "id": 3, "color": [70, 70, 70], "trainId": 2},
    {"hasInstances": True, "category": "Building", "catid": 4, "name": "Bridge", "ignoreInEval": False, "id": 4, "color": [102, 102, 156], "trainId": 3},
    {"hasInstances": True, "category": "Building", "catid": 4, "name": "Building", "ignoreInEval": False, "id": 5, "color": [190, 153, 153], "trainId": 4},
    {"hasInstances": True, "category": "object", "catid": 5, "name": "car", "ignoreInEval": False, "id": 6, "color": [153, 153, 153], "trainId": 5},
    {"hasInstances": True, "category": "object", "catid": 5, "name": "CartLuggagePram", "ignoreInEval": False, "id": 7, "color": [250, 170, 30], "trainId": 6},
    {"hasInstances": True, "category": "object", "catid": 5, "name": "Child", "ignoreInEval": False, "id": 8, "color": [220, 220, 0], "trainId": 7},
    {"hasInstances": True, "category": "object", "catid": 5, "name": "Column_Pole", "ignoreInEval": False, "id": 9, "color": [107, 142, 35], "trainId": 8},
    {"hasInstances": True, "category": "object", "catid": 5, "name": "Fence", "ignoreInEval": False, "id": 10, "color": [152, 251, 152], "trainId": 9},
    {"hasInstances": True, "category": "object", "catid": 5, "name": "LaneMkgsDriv", "ignoreInEval": False, "id": 11, "color": [70, 130, 180], "trainId": 10},
    {"hasInstances": True, "category": "object", "catid": 5, "name": "LaneMkgsNonDriv", "ignoreInEval": False, "id": 12, "color": [220, 20, 60], "trainId": 11},
    {"hasInstances": True, "category": "Misc_Text", "catid": 6, "name": "Misc_Text", "ignoreInEval": False, "id": 13, "color": [255, 0, 0], "trainId": 12},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "MotorcycleScooter", "ignoreInEval": False, "id": 14, "color": [0, 0, 142], "trainId": 13},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "OtherMoving", "ignoreInEval": False, "id": 15, "color": [0, 0, 70], "trainId": 14},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "ParkingBlock", "ignoreInEval": False, "id": 16, "color": [0, 60, 100], "trainId": 15},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Pedestrian", "ignoreInEval": False, "id": 17, "color": [0, 80, 100], "trainId": 16},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Road", "ignoreInEval": False, "id": 18, "color": [0, 0, 230], "trainId": 17},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "RoadShoulder", "ignoreInEval": False, "id": 19, "color": [119, 11, 32], "trainId": 18},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Sidewalk", "ignoreInEval": False, "id": 20, "color": [100, 50, 70], "trainId": 19},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "SignSymbol", "ignoreInEval": False, "id": 21, "color": [40, 60, 100], "trainId": 20},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Sky", "ignoreInEval": False, "id": 22, "color": [60, 50, 90], "trainId": 21},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "SUVPickupTruck", "ignoreInEval": False, "id": 23, "color": [150, 20, 110], "trainId": 22},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "TrafficCone", "ignoreInEval": False, "id": 24,  "color": [200, 80, 100], "trainId": 23},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "TrafficLight", "ignoreInEval": False, "id": 25, "color": [80, 70, 230], "trainId": 24},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Train", "ignoreInEval": False, "id": 26, "color": [121, 21, 52], "trainId": 25},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Tree", "ignoreInEval": False, "id": 27, "color": [110, 21, 82], "trainId": 26},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Truck_Bus", "ignoreInEval": False, "id": 28, "color": [160, 71, 92], "trainId": 27},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Tunnel", "ignoreInEval": False, "id": 29, "color": [180, 61, 102], "trainId": 28},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "VegetationMisc", "ignoreInEval": False, "id": 30, "color": [190, 51, 122], "trainId": 29},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Void", "ignoreInEval": False, "id": 31, "color": [220, 21, 62], "trainId": 30},
    {"hasInstances": True, "category": "vehicle", "catid": 7, "name": "Wall", "ignoreInEval": False, "id": 32, "color": [120, 11, 32], "trainId": 31}
]

class CityScapes(BaseDataset):
    def __init__(self, dataroot, annpath, trans_func=None, mode='train'):
        super(CityScapes, self).__init__(
                dataroot, annpath, trans_func, mode)
        self.n_cats = 32
        self.lb_ignore = 255
        self.lb_map = np.arange(256).astype(np.uint8)
        for el in labels_info:
            self.lb_map[el['id']] = el['trainId']

        self.to_tensor = T.ToTensor(
            mean=(0.3257, 0.3690, 0.3223), # city, rgb
            std=(0.2112, 0.2148, 0.2115),
        )

Traceback (most recent call last):
  File "tools/train.py", line 245, in <module>
    main()
  File "tools/train.py", line 241, in main
    train()
  File "tools/train.py", line 187, in train
    loss_pre = criteria_pre(logits, lb)
  File "/home/sjx/anaconda3/envs/py36bisenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/ohem_ce_loss.py", line 38, in forward
    loss_hard = loss[loss > self.thresh]
RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
NCCL error in: /opt/conda/conda-bld/pytorch_1595629416375/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:69, unhandled cuda error, NCCL version 2.4.8
Traceback (most recent call last):
  File "/home/sjx/anaconda3/envs/py36bisenet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sjx/anaconda3/envs/py36bisenet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sjx/anaconda3/envs/py36bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/sjx/anaconda3/envs/py36bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/sjx/anaconda3/envs/py36bisenet/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--model', 'bisenetv1']' died with <Signals.SIGABRT: 6>.

![QQ图片20201125110501](https://user-images.githubusercontent.com/35440836/100178139-4a728980-2f0e-11eb-99ff-ed128ac4dcb9.png)
![QQ图片20201125110452](https://user-images.githubusercontent.com/35440836/100178179-5bbb9600-2f0e-11eb-88b9-8cd5abcca525.png)

**Comment by DanielEliasib** [comment]
Hi! I'm running into the same problem, I'm trying to train on colab and I have the exact same error, how did you fix it?

**Comment by sjxmm** [comment]
I ended up sampling 19 out of 32 classes.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CoinCheung/BiSeNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 凌晨4:02
收件人:&nbsp;"CoinCheung/BiSeNet"<BiSeNet@noreply.github.com&gt;;
抄送:&nbsp;"九吖么九"<1749968700@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [CoinCheung/BiSeNet] Help！RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress： an illegal memory access was encountered (#101)





 
Hi! I'm running into the same problem, I'm trying to train on colab and I have the exact same error, how did you fix it?
