### ISSUE TITLE
The isues of trainning

### ISSUE THREAD

**Issue by gaowq2017** [CoinCheung/BiSeNet#102]
Hi @CoinCheung ,
    Old iron i have a isues as follow when trainning the code using 3 GPU
![image](https://user-images.githubusercontent.com/29697367/100327608-796c2680-3006-11eb-8c5a-5c47bb373140.png)
Do you any ideas? Thank you! Skr~ Skr~

**Comment by CoinCheung** [comment]
What pytorch version are you using ?? Please use the refactored code which no longer relies on inplace-abn.

**Comment by gaowq2017** [comment]
> What pytorch version are you using ?? Please use the refactored code which no longer relies on inplace-abn.

The version of pytorch is 1.4 . Running the train.py under old file. Thanks!

**Comment by CoinCheung** [comment]
Maybe you can try to down-grade pytorch to 1.0 and try again.

**Comment by CoinCheung** [comment]
I am closing this, and you can still add comments here if your problem is not solved.
