### ISSUE TITLE
config threshold

### ISSUE THREAD

**Issue by Antdancing** [CoinCheung/BiSeNet#103]
HI.

I have a project about real-time binary medical image segmentation, And your code work very well in both of train model & predict mask from testing set. by the way, I have a question. Can you point me out where can I change the threshold of demo.py? I would like to see some change between IoU accuracy and average error of the testing mask when the threshold is slightly change from 0.5.

**Comment by CoinCheung** [comment]
I do not know how did you use this on binary segmentation task. If you want to use a threshold to distinguish positive from negative, you need to use a sigmoid classifier. However, this project is based on softmax classifier, so you need to modify associated part of the code before training. After that if would be easy to figure out where to add your threshold. You can have a try of this, good luck!!

**Comment by CoinCheung** [comment]
Closing this since you might not need to consider this now.
