### ISSUE TITLE
a issue about training custom dataset

### ISSUE THREAD

**Issue by curryJ** [CoinCheung/BiSeNet#104]
Thanks for your code!
When I run this code with my own dataset by python -m torch.distributed.launch --nproc_per_node=2 tools/train.py --model bisenetv2,I have an issue.
I follow the solution in [issue](https://github.com/CoinCheung/BiSeNet/issues/96)
I change the config file and the set_model() function-->net = model_factory [cfg.model_type] (2) ,because my class number is 2.
And I change the evaluate.py,just change 19 to 2.
Here is my issue.But when I change the 2 to 19 in set_model() funtion, the training works but I know it is not what I want.
Thank you!
![image](https://user-images.githubusercontent.com/23001027/100537723-cef23e80-3265-11eb-958e-f83cc606bcd7.png)

**Comment by tangyingli101** [comment]
I have the same problem as you，I set the trainId of the ignoreInEval class to 255 in cityscapes_cv2.py and it worked!

**Comment by curryJ** [comment]
Thanks for your help.I have&nbsp;debugged my code and I find that my label dataset includes more than one class.Originally,I think my label dataset's class is 0 and 1,which 0 represents background and 1 represents object,but now I find the label includes 6 classes

I'm thinking how to change the labels_info in&nbsp;cityscapes_cv2.py

Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangyingli101"<notifications@github.com&gt;; 
发送时间: 2020年11月30日(星期一) 晚上6:06
收件人: "CoinCheung/BiSeNet"<BiSeNet@noreply.github.com&gt;; 
抄送: "PGyoung13"<761478292@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CoinCheung/BiSeNet] a issue about training custom dataset (#104)





 
I have the same problem as you，I set the trainId of the ignoreInEval class to 255 in cityscapes_cv2.py and it worked!

**Comment by CoinCheung** [comment]
Sorry for being so late !! It seems you have figured it out, so I am closing this.
