### ISSUE TITLE
老哥，关于V2的evaluate有个疑问

### ISSUE THREAD

**Issue by BunnySF** [CoinCheung/BiSeNet#105]
文章提到说Seg Head部分只参与训练过程，然而我看evaluate中，V2模型的output_aux依旧是True，是否意味Seg Head仍参与了推理过程？

**Comment by CoinCheung** [comment]
I did not remove it during inference, but the aux outputs does not impact the primary output.

**Comment by CoinCheung** [comment]
Closing this because the question is answered.
