### ISSUE TITLE
Load pretrained model failed

### ISSUE THREAD

**Issue by CuttlefishXuan** [CoinCheung/BiSeNet#106]
ubuntu16.04
virtualenv python==3.6.12
pytorch==1.6.0

When I run the tools/demo.py using the pretrained model "model_final_v2.pth", it tells me: 
model_final_v2.pth is a zip archive(did you mean to use torch.jit.load()?)

Someone says this error is caused by pytorch<1.6 when loading a pretrained model that training with pytorch 1.6. But what is the reason for my situation？ Someone help me please!

**Comment by CoinCheung** [comment]
Yes, I exported it with pytorch1.6. So you need to load it with pytorch1.6.

Or you might re-save it with pytorch1.6 and then load it in your environment:
```
# with pytorch1.6
>>> state = torch.load('model_final_v2.pth')
>>> torch.save(state, 'model_final_v2_2.pth', _use_new_zipfile_serialization=False)
# with your older version pytorch
$ python tools/demo.py ....
```

**Comment by CoinCheung** [comment]
Closing this since it is no longer active. You might have made it work now.
