### ISSUE TITLE
It occurs no defined colors

### ISSUE THREAD

**Issue by shanjiuvspikaqiu** [CoinCheung/BiSeNet#107]
Thank you for the amazing repo! The detailed instructions helped me a lot!

I trained my own datasets with 9 classes. It performs well but the colors are not defined in **cityscapes_cv2.py**. E.g. the road is covered with (132, 61,109), but this color is not defined in cityscapes_cv2.py (I use same color with cityscapes format). 

Could you tell me where may the problem is? Thank you and have a nice day! :p

**Comment by CoinCheung** [comment]
Hi, 

It is not your problem, I just generate these colors randomly. You can align the color maps used in demo.py by editing this line:

https://github.com/CoinCheung/BiSeNet/blob/90de8f9bdb6281f700087a5384996b18a4c6dae7/tools/demo.py#L28

**Comment by CoinCheung** [comment]
I am closing this since you are likely to have coped with your problem.
