### ISSUE TITLE
an problem about calculating mIOU

### ISSUE THREAD

**Issue by Jinyu-M** [CoinCheung/BiSeNet#108]
hi, @CoinCheung , thanks for your enlightening work :)
I have a insignificant problem that why the probability obtained after flip augmentation in multi-scale evaluation (MscEvalCrop.eval_chip) need to be propcessed by a exponential function? But there is not such procedure in MscEvalV0.

**Comment by CoinCheung** [comment]
Hi,

It is left there due to some historical reasons, it should have no great impact on the result.

**Comment by CoinCheung** [comment]
Closing this since the question is answered. You can still leave comments or open new issues if you have other problems about the code.
