### ISSUE TITLE
problem about tools/demo.py

### ISSUE THREAD

**Issue by axt-one** [CoinCheung/BiSeNet#109]
Thanks for your code! I want to learn and use this code. However, I have a problem about tools/demo.py.
I could run tools/demo.py with example.png. But when I tried to run it with other images, I have met the following error.

`Traceback (most recent call last):
  File "tools/demo_webcam.py", line 55, in <module>
    out = net(im)[0].argmax(dim=1).squeeze().detach().cpu().numpy()
  File "/Users/ryo/opt/anaconda3/envs/pytorch2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/models/bisenetv2.py", line 332, in forward
    feat_head = self.bga(feat_d, feat_s)
  File "/Users/ryo/opt/anaconda3/envs/pytorch2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/models/bisenetv2.py", line 273, in forward
    left = left1 * torch.sigmoid(right1)
RuntimeError: The size of tensor a (45) must match the size of tensor b (48) at non-singleton dimension 2`

This error seems to occur when running tools/demo.py because of image size. With (2048, 1024), (512, 314), (160, 90) image, it could run. But the error occurred when I run it whith (640, 360), (160, 100) and more images.

Is it a normal reaction? Is there any process to run it with every size of images?

I run tools/demo.py on cpu, it possibly relates to this error...
I commented out line 34, `net.cuda()`, and end of line 42 `.cuda()`. Is it relates to the error?

**Comment by shanjiuvspikaqiu** [comment]
"RuntimeError: The size of tensor a (45) must match the size of tensor b (48) at non-singleton dimension 2" The problem might be in Downsammpling. These two solutions may help you:

Option1:  resize the images before the net reads them
Option2:  print sizes of tensors in every layers, then adjust the dimension to: e.g. either 45-->48 or 48-->45

**Comment by axt-one** [comment]
Thanks for your help!
I tried both option1 & 2, and it worked well!

**Comment by CoinCheung** [comment]
Hi, 
Sorry for being so late seeing this. Good to know that you have made it work. I am closing this, and please be free to open new issues if you have other problems with this codebase.
