### ISSUE TITLE
not so good result when infer with tensorrt 

### ISSUE THREAD

**Issue by tangyingli101** [CoinCheung/BiSeNet#110]
hi，thank you for your project，it is very usefull to me.I used your method to convert the pytorch model to tensorrt. But when I infer with tensorrt,it not as good as the pytorch model. In the image below,the first image is the tensorrt result,and the second is pytorch result.How can I improve the result of tensorrt??Is there any problem when convert to onnx??Looking forwar to your reply. Thank you!
![res31_v2_tensorrt](https://user-images.githubusercontent.com/8503726/101758715-a5fa6500-3b13-11eb-9ef3-cda16e81b196.jpg)
![res31_v2_result1210](https://user-images.githubusercontent.com/8503726/101758734-aa268280-3b13-11eb-8d21-0037bc87c451.jpg)

**Comment by CoinCheung** [comment]
Hi, 
Would you please provie more details about how you tested the two methods ? did you use same interpolation method and input image size?

**Comment by tangyingli101** [comment]
Thanks for your reply, I have found the problem: the mean and variance are set wrong。
