### ISSUE TITLE
Bisenetv2 problem

### ISSUE THREAD

**Issue by qifengluo** [CoinCheung/BiSeNet#113]
Hi, I used the train.py to train bisenetv2, but just got ingle mIOU 0.7118070721626282, not your reported. I just changed the lr_start = 1e-2.

**Comment by CoinCheung** [comment]
Hi, 

bisenetv2 has a big variance, I trained 5 times, and the results varies between 72-74. Maybe the variance is larger than I tested, you can train it for a few times and see if the results are always lower than 71.

**Comment by CoinCheung** [comment]
Maybe you are not interested in verifying the model variance, but only want to claim that your result is different from the report, so I am closing this with peace and love. If your have other problems about the code, you can still open new issues.

**Comment by CuttlefishXuan** [comment]
Hi, I want to know how many iterations you have trained to get the result of 0.71 with lr_start=1e-2?
