### ISSUE TITLE
Is bisenetv1 better than bisenetv2?

### ISSUE THREAD

**Issue by zyqdragon** [CoinCheung/BiSeNet#116]
All scores of bisenetv1 are higher than the ones of bisenetv2 as follows:
bisenetv1 | 75.55 | 76.90 | 77.40 | 78.91 | 60/19 | download
bisenetv2 | 74.12 | 74.18 | 75.89 | 75.87 | 50/16 | download

**Comment by CoinCheung** [comment]
Not exactly, for what I know, bisenetv2 has fewer parameters, and less flops. It is more light-weighted. My personal opinion of the reason why bisenetv2 has fewer fps than bisenetv1 is that it uses a lot of depth-wise convolution (dwconv) which is a sparse operation and has more latency than the continuous operation of plain conv. Also It is said that cudnn does not provide dwconv operation, so pytorch is using its native implementation. However, if you count the amount of computation, bisenetv2 requires less computation than bisenetv1.

**Comment by novioleo** [comment]
bisev2 is especially suitable for mobile real time segmentation with ncnn,tengine and etc..
