### ISSUE TITLE
新年快樂but I need help with  Custom Dataset ~

### ISSUE THREAD

**Issue by DavidChenTaipei** [CoinCheung/BiSeNet#118]
Happy new year 
But I faced a problem, I want to try the dataset [Uavid](https://uavid.nl/) on the BiseNet V2,however, I do not know how to get the label info, could you please give me some hints or keywords? I need to update the label info in train.py for the custom dataset right?

**Comment by DavidChenTaipei** [comment]
If it is possible, could you talk about how did you get the label info of the Cityscape Dataset

**Comment by kubitz** [comment]
I am currently trying to train in a Uavid too. I wrote some scripts to convert them in a cityscape format. That might be a good starting point for you too: [repo link](https://github.com/kubitz/UAV-Segmentation-Scripts)

**Comment by CoinCheung** [comment]
Sorry for being so late!! I was too busy and exhausted in the past few months.

I do not have experience with that dataset, but maybe you can follow the suggestions of @kubitz .

Maybe you have already solved your problem now that half a year has passed, so I am closing this.
