### ISSUE TITLE
Submission on Cityscapes

### ISSUE THREAD

**Issue by chenyzh28** [CoinCheung/BiSeNet#119]
Hello! I want to submit my testing results to the “https://www.cityscapes-dataset.com”. But I don't know the specific format, should I submit the color image or label image?
![NP@4DWT62N67AYAWGOF~CE](https://user-images.githubusercontent.com/35193979/103602479-19429b80-4f47-11eb-8169-5368ae7a6fb8.png)

**Comment by DavidChenTaipei** [comment]
Same question about this

**Comment by CoinCheung** [comment]
I think it will be label images saved as png format if you are submitting segmentation results.

**Comment by CoinCheung** [comment]
I think this can be closed now.
