### ISSUE TITLE
这是你这儿的模型吗

### ISSUE THREAD

**Issue by MaybeShewill-CV** [CoinCheung/BiSeNet#123]
http://manaai.cn/aicodes_detail3.html?id=55 如题

**Comment by CoinCheung** [comment]
they ask me to pay money to see the code, so I am not sure whether they have used my code or not. But I don't mind anyone to use my code reasonably in their projects. I will not ask them to pay me but I will be very happy if someone would like to give me money :) 

Actually I have a few other tricks to further boost the performance, so I am not going to behave like a mean man at this moment.

**Comment by MaybeShewill-CV** [comment]
@CoinCheung [赞]
