### ISSUE TITLE
Dataloader makes data fewer???

### ISSUE THREAD

**Issue by DavidChenTaipei** [CoinCheung/BiSeNet#125]
Hi guys 
I'm really confusing that why the dataset after passing through the cityscape class has almost 3000 items, however, the number reduces to 371 after passing through dataloader, can anyone help?
Thanks a lot 

By the way, I took off those parts of distributed training codes, but I don't think this is the reason. For me, the main problem is why the dataloader makes the data become fewer.

<img width="1002" alt="截圖 2021-01-24 上午12 22 20" src="https://user-images.githubusercontent.com/54167907/105608085-d43eb600-5ddc-11eb-832c-de8d9c864eae.png">
<img width="949" alt="截圖 2021-01-24 上午12 37 06" src="https://user-images.githubusercontent.com/54167907/105608086-d9036a00-5ddc-11eb-92d3-68c565f58d94.png">

**Comment by DavidChenTaipei** [comment]
It seems like the model stop training after the first epoch

**Comment by NarutoZhao** [comment]
I'm training the v2, I also took off those parts of distributed training codes. 
But, time per 100 iterrations from 85s to 420s. 
what's wrong with distributed training.

**Comment by CoinCheung** [comment]
@DavidChenTaipei  When you use dataloader, the images are batched, so the length of dataloader is shorter than its associated dataset. Also I re-implemented the sampler so that we can count the training iterations rather than epoches, which result in a single epoch during the whole training process.

**Comment by CoinCheung** [comment]
@NarutoZhao How did you modified your code ? If you want to train with single gpu, you can try this: 
```
export CUDA_VISIBLE_DEVICES=0
python -m torch.distributed.launch --nproc_per_node=1 tools/train.py --model bisenetv2
```
But I am afraid you will have to modify some training configurations if you use one gpu.
