### ISSUE TITLE
训练时，cpu 占用100%，gpu占用较低是什么原因？

### ISSUE THREAD

**Issue by YAwei666** [CoinCheung/BiSeNet#127]
thank you

**Comment by CoinCheung** [comment]
What is the version of your pytorch and what is your platform like ?

You can set number of threads to 1 before setting up like this and see if it works:
```
export OMP_NUM_THREADS=1                                                        
export MKL_NUM_THREADS=1 
```

**Comment by CoinCheung** [comment]
Close with love & peace.
