### ISSUE TITLE
FLOPs

### ISSUE THREAD

**Issue by InvictusRichard** [CoinCheung/BiSeNet#130]
Do you have a program to calculate flops? I will be very grateful!

**Comment by CoinCheung** [comment]
Hi,

I do not have scripts to do this, but you can use mmcv to do that, see [this](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/utils/flops_counter.py)

**Comment by CoinCheung** [comment]
close this because I have answered this.
