### ISSUE TITLE
Runtime error about demo.py

### ISSUE THREAD

**Issue by tianchengdw** [CoinCheung/BiSeNet#134]
Thanks for yout great work! I am now learning your code. 
My conda virtual environment is python==3.6.12, pytorch==1.6.0, cudatoolkit==10.2 

And I want to run demo.py by pretrained model to test my images. 
`python tools/demo.py --model bisenetv2 --weight-path ./res/model_final_v2.pth --img-path ./example.png`

But I met a error below. It seems that I can not load the model.
`RuntimeError: Error(s) in loading state_dict for BiSeNetV2:
	Missing key(s) in state_dict: "head.conv_out.0.weight", "head.conv_out.0.bias", "aux2.conv_out.0.conv.weight", "aux2.conv_out.0.bn.weight", "aux2.conv_out.0.bn.bias", "aux2.conv_out.0.bn.running_mean", "aux2.conv_out.0.bn.running_var", "aux2.conv_out.1.weight", "aux2.conv_out.1.bias", "aux3.conv_out.0.conv.weight", "aux3.conv_out.0.bn.weight", "aux3.conv_out.0.bn.bias", "aux3.conv_out.0.bn.running_mean", "aux3.conv_out.0.bn.running_var", "aux3.conv_out.1.weight", "aux3.conv_out.1.bias", "aux4.conv_out.0.conv.weight", "aux4.conv_out.0.bn.weight", "aux4.conv_out.0.bn.bias", "aux4.conv_out.0.bn.running_mean", "aux4.conv_out.0.bn.running_var", "aux4.conv_out.1.weight", "aux4.conv_out.1.bias", "aux5_4.conv_out.0.conv.weight", "aux5_4.conv_out.0.bn.weight", "aux5_4.conv_out.0.bn.bias", "aux5_4.conv_out.0.bn.running_mean", "aux5_4.conv_out.0.bn.running_var", "aux5_4.conv_out.1.weight", "aux5_4.conv_out.1.bias". 
	Unexpected key(s) in state_dict: "head.conv_out.weight", "head.conv_out.bias", "aux2.conv_out.weight", "aux2.conv_out.bias", "aux3.conv_out.weight", "aux3.conv_out.bias", "aux4.conv_out.weight", "aux4.conv_out.bias", "aux5_4.conv_out.weight", "aux5_4.conv_out.bias". `

Can anyone help me?

Thanks in advance!

**Comment by CoinCheung** [comment]
Hi, 

What modifications have you made, and where did you got the pretrained model ?

**Comment by tianchengdw** [comment]
> Hi,
> 
> What modifications have you made, and where did you got the pretrained model ?


Hi, 
You can download from baidu pan link of [bisenetv1](https://pan.baidu.com/s/1K-TafW8XC9fszm-FmR-Jhw)(extract code: 8pju) and [bisenetv2](https://pan.baidu.com/s/1smgpJT0ItE5xMtooxvAT3w)(extract code: yik9).

_Originally posted by @CoinCheung in https://github.com/CoinCheung/BiSeNet/issues/73#issuecomment-669820873_

Thank you for your quick reply! I download the model from these links. And I have not modified any code yet.

**Comment by CoinCheung** [comment]
weights on the paidu pan is old, can you download weights following the link in the README.md ?

**Comment by tianchengdw** [comment]
> weights on the paidu pan is old, can you download weights following the link in the README.md ?

Thank you for your Tips! I got it! 
预祝您牛年快乐~
