### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by tianchengdw** [CoinCheung/BiSeNet#135]
Hi,  thanks for your work!

I wanna train the model on my own datasets. So I modified the cityscapes_cv2.py. The category number of my dataset is 35. But the Cityscapes Dataset is 38. Does it matter?

And I changed the `self.n_cats` value. Mine is 18. Then I ran this `CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 tools/train.py --model bisenetv1`

Sadly, I met issue like issue 80. But the traceback_log is different.

https://github.com/CoinCheung/BiSeNet/issues/80#issue-689764193

In ISSUE 80, why did you mention this?

`        if not self.lb_map is None:
            label = self.lb_map[label]`

`Traceback (most recent call last):
  File "tools/train.py", line 225, in <module>
    main()
  File "tools/train.py", line 221, in main
    train()
  File "tools/train.py", line 172, in train
    loss_pre = criteria_pre(logits, lb)
  File "/home/XXXX/miniconda3/envs/bise/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/ohem_ce_loss.py", line 38, in forward
    loss_hard = loss[loss > self.thresh]
RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
NCCL error in: /opt/conda/conda-bld/pytorch_1595629427286/work/torch/lib/c10d/../c10d/NCCLUtils.hpp:69, unhandled cuda error, NCCL version 2.4.8
Traceback (most recent call last):
  File "/home/XXX/miniconda3/envs/bise/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/XXXX/miniconda3/envs/bise/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/XXX/miniconda3/envs/bise/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/XXXX/miniconda3/envs/bise/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jinda0529/miniconda3/envs/bise/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--model', 'bisenetv1']' died with <Signals.SIGABRT: 6>.
`
Can anyone help me?

Thanks in advance!

**Comment by tianchengdw** [comment]
Hi, I add `torch.backends.cudnn.benchmark = True` in train.py. Then I can train the model BiseNet v1. But I met the LOSS NAN problem after several iterations. 
`iter: 100/180000, lr: 0.006924, eta: 7:58:47, time: 16.13, loss: 6.9297, loss_pre: 1.5755, loss_aux0: 2.4220, loss_aux1: 2.9323
iter: 200/180000, lr: 0.008717, eta: 7:33:54, time: 14.32, loss: nan, loss_pre: nan, loss_aux0: 1.1645, loss_aux1: 2.3486
iter: 300/180000, lr: 0.010974, eta: 7:29:11, time: 14.70, loss: nan, loss_pre: nan, loss_aux0: 1.3122, loss_aux1: 1.1155
iter: 400/180000, lr: 0.013815, eta: 7:28:02, time: 14.88, loss: nan, loss_pre: nan, loss_aux0: 1.2693, loss_aux1: 1.4046
iter: 500/180000, lr: 0.017393, eta: 7:28:44, time: 15.13, loss: nan, loss_pre: nan, loss_aux0: 1.2659, loss_aux1: 1.3227
iter: 600/180000, lr: 0.021896, eta: 7:29:04, time: 15.12, loss: nan, loss_pre: nan, loss_aux0: 1.2891, loss_aux1: 1.3336
iter: 700/180000, lr: 0.027565, eta: 7:30:34, time: 15.43, loss: nan, loss_pre: nan, loss_aux0: 1.3109, loss_aux1: 1.3395
iter: 800/180000, lr: 0.034703, eta: 7:31:27, time: 15.38, loss: nan, loss_pre: nan, loss_aux0: 1.2585, loss_aux1: 1.2688
iter: 900/180000, lr: 0.043688, eta: 7:32:24, time: 15.48, loss: nan, loss_pre: nan, loss_aux0: 1.3432, loss_aux1: 1.2961
iter: 1000/180000, lr: 0.055000, eta: 7:33:05, time: 15.47, loss: nan, loss_pre: nan, loss_aux0: 1.3522, loss_aux1: 1.3020
`

**Comment by CoinCheung** [comment]
If your dataset do not have label map like cityscapes, you need to comment that line out:
```
 # if not self.lb_map is None: label = self.lb_map[label]
```
