### ISSUE TITLE
Color coding of output according to CityScapes color table

### ISSUE THREAD

**Issue by JimmysCheapJeep** [CoinCheung/BiSeNet#136]
Hi!

Thanks for sharing your work!

I would like to generate a color coded output aligned to to the cityscape color table for an evaluation study.

How should I modify the masking color palette array in the code to generate such a colorization?

Line 28 in demo.py says:
palette = np.random.randint(0, 256, (256, 3), dtype=np.uint8) 

which generates a random colored shape of (256, 3).

I ask myself how to create a palette that realizes a color coding that matches to the cityscapes labelling and also leaves out unevaluated and unknown areas...

Ok, i using the class id "image" now.
Is there a list which associates the class label number to a semantic name?
Which of the 19 classes were used in the learning process of the example model?

Thanks!

**Comment by CoinCheung** [comment]
Color information can be found here:
https://github.com/CoinCheung/BiSeNet/blob/90de8f9bdb6281f700087a5384996b18a4c6dae7/lib/cityscapes_cv2.py#L19

**Comment by JimmysCheapJeep** [comment]
Hi! Thanks!
