### ISSUE TITLE
Can't download weights following the link in the README.md

### ISSUE THREAD

**Issue by 2017ND** [CoinCheung/BiSeNet#137]
Sorry, I can't download weights following the link in the README.md.  Please help me.
I'm Chinese and can't log in to google.com. Can you help to upload effective weight to Baidu disk？
Thanks very much!

**Comment by CoinCheung** [comment]
Hi,

You can download from here: 
[bisenetv1](https://github.com/CoinCheung/BiSeNet/releases/download/0.0.0/model_final_v1.pth)
[bisenetv2](https://github.com/CoinCheung/BiSeNet/releases/download/0.0.0/model_final_v2.pth)

**Comment by 2017ND** [comment]
> Hi,
> 
> You can download from here:
> [bisenetv1](https://github.com/CoinCheung/BiSeNet/releases/download/0.0.0/model_final_v1.pth)
> [bisenetv2](https://github.com/CoinCheung/BiSeNet/releases/download/0.0.0/model_final_v2.pth)

Thanks!
