### ISSUE TITLE
Error with BiSeNetV2 cfg

### ISSUE THREAD

**Issue by SaharGezer** [CoinCheung/BiSeNet#138]
Hi,

I got this error:

RuntimeError: Error(s) in loading state_dict for BiSeNetV2:
	Missing key(s) in state_dict: "detail.S1.0.conv.weight", "detail.S1.0.bn.weight", "detail.S1.0.bn.bias", "detail.S1.0.bn.running_mean", "detail.S1.0.bn.running_var", "detail.S1.1.conv.weight", "detail.S1.1.bn.weight", "detail.S1.1.bn.bias", "detail.S1.1.bn.running_mean", "detail.S1.1.bn.running_var", "detail.S2.0.conv.weight", "detail.S2.0.bn.weight", "detail.S2.0.bn.bias", "detail.S2.0.bn.running_mean", "detail.S2.0.bn.running_var", "detail.S2.1.conv.weight", "detail.S2.1.bn.weight", "detail.S2.1.bn.bias", "detail.S2.1.bn.running_mean", "detail.S2.1.bn.running_var", "detail.S2.2.conv.weight", "detail.S2.2.bn.weight", "detail.S2.2.bn.bias", "detail.S2.2.bn.running_mean", "detail.S2.2.bn.running_var", "detail.S3.0.conv.weight", "detail.S3.0.bn.weight", "detail.S3.0.bn.bias", "detail.S3.0.bn.running_mean", "detail.S3.0.bn.running_var", "detail.S3.1.conv.weight", "detail.S3.1.bn.weight", "detail.S3.1.bn.bias", "detail.S3.1.bn.running_mean", "detail.S3.1.bn.running_var", "detail.S3.2.conv.weight", "detail.S3.2.bn.weight", "detail.S3.2.bn.bias", "detail.S3.2.bn.running_mean", "detail.S3.2.bn.running_var", "segment.S1S2.conv.conv.weight", "segment.S1S2.conv.bn.weight", "segment.S1S2.conv.bn.bias", "segment.S1S2.conv.bn.running_mean", "segment.S1S2.conv.bn.running_var", "segment.S1S2.left.0.conv.weight", "segment.S1S2.left.0.bn.weight", "segment.S1S2.left.0.bn.bias", "segment.S1S2.left.0.bn.running_mean", "segment.S1S2.left.0.bn.running_var", "segment.S1S2.left.1.conv.weight", "segment.S1S2.left.1.bn.weight", "segment.S1S2.left.1.bn.bias", "segment.S1S2.left.1.bn.running_mean", "segment.S1S2.left.1.bn.running_var", "segment.S1S2.fuse.conv.weight", "segment.S1S2.fuse.bn.weight", "segment.S1S2.fuse.bn.bias", "segment.S1S2.fuse.bn.running_mean", "segment.S1S2.fuse.bn.running_var", "segment.S3.0.conv1.conv.weight", "segment.S3.0.conv1.bn.weight", "segment.S3.0.conv1.bn.bias", "segment.S3.0.conv1.bn.running_mean", "segment.S3.0.conv1.bn.running_var", "segment.S3.0.dwconv1.0.weight", "segment.S3.0.dwconv1.1.weight", "segment.S3.0.dwconv1.1.bias", "segment.S3.0.dwconv1.1.running_mean", "segment.S3.0.dwconv1.1.running_var", "segment.S3.0.dwconv2.0.weight", "segment.S3.0.dwconv2.1.weight", "segment.S3.0.dwconv2.1.bias", "segment.S3.0.dwconv2.1.running_mean", "segment.S3.0.dwconv2.1.running_var", "segment.S3.0.conv2.0.weight", "segment.S3.0.conv2.1.weight", "segment.S3.0.conv2.1.bias", "segment.S3.0.conv2.1.running_mean", "segment.S3.0.conv2.1.running_var", "segment.S3.0.shortcut.0.weight", "segment.S3.0.shortcut.1.weight", "segment.S3.0.shortcut.1.bias", "segment.S3.0.shortcut.1.running_mean", "segment.S3.0.shortcut.1.running_var", "segment.S3.0.shortcut.2.weight", "segment.S3.0.shortcut.3.weight", "segment.S3.0.shortcut.3.bias", "segment.S3.0.shortcut.3.running_mean", "segment.S3.0.shortcut.3.running_var", "segment.S3.1.conv1.conv.weight", "segment.S3.1.conv1.bn.weight", "segment.S3.1.conv1.bn.bias", "segment.S3.1.conv1.bn.running_mean", "segment.S3.1.conv1.bn.running_var", "segment.S3.1.dwconv.0.weight", "segment.S3.1.dwconv.1.weight", "segment.S3.1.dwconv.1.bias", "segment.S3.1.dwconv.1.running_mean", "segment.S3.1.dwconv.1.running_var", "segment.S3.1.conv2.0.weight", "segment.S3.1.conv2.1.weight", "segment.S3.1.conv2.1.bias", "segment.S3.1.conv2.1.running_mean", "segment.S3.1.conv2.1.running_var", "segment.S4.0.conv1.conv.weight", "segment.S4.0.conv1.bn.weight", "segment.S4.0.conv1.bn.bias", "segment.S4.0.conv1.bn.running_mean", "segment.S4.0.conv1.bn.running_var", "segment.S4.0.dwconv1.0.weight", "segment.S4.0.dwconv1.1.weight", "segment.S4.0.dwconv1.1.bias", "segment.S4.0.dwconv1.1.running_mean", "segment.S4.0.dwconv1.1.running_var", "segment.S4.0.dwconv2.0.weight", "segment.S4.0.dwconv2.1.weight", "segment.S4.0.dwconv2.1.bias", "segment.S4.0.dwconv2.1.running_mean", "segment.S4.0.dwconv2.1.running_var", "segment.S4.0.conv2.0.weight", "segment.S4.0.conv2.1.weight", "segment.S4.0.conv2.1.bias", "segment.S4.0.conv2.1.running_mean", "segment.S4.0.conv2.1.running_var", "segment.S4.0.shortcut.0.weight", "segment.S4.0.shortcut.1.weight", "segment.S4.0.shortcut.1.bias", "segment.S4.0.shortcut.1.running_mean", "segment.S4.0.shortcut.1.running_var", "segment.S4.0.shortcut.2.weight", "segment.S4.0.shortcut.3.weight", "segment.S4.0.shortcut.3.bias", "segment.S4.0.shortcut.3.running_mean", "segment.S4.0.shortcut.3.running_var", "segment.S4.1.conv1.conv.weight", "segment.S4.1.conv1.bn.weight", "segment.S4.1.conv1.bn.bias", "segment.S4.1.conv1.bn.running_mean", "segment.S4.1.conv1.bn.running_var", "segment.S4.1.dwconv.0.weight", "segment.S4.1.dwconv.1.weight", "segment.S4.1.dwconv.1.bias", "segment.S4.1.dwconv.1.running_mean", "segment.S4.1.dwconv.1.running_var", "segment.S4.1.conv2.0.weight", "segment.S4.1.conv2.1.weight", "segment.S4.1.conv2.1.bias", "segment.S4.1.conv2.1.running_mean", "segment.S4.1.conv2.1.running_var", "segment.S5_4.0.conv1.conv.weight", "segment.S5_4.0.conv1.bn.weight", "segment.S5_4.0.conv1.bn.bias", "segment.S5_4.0.conv1.bn.running_mean", "segment.S5_4.0.conv1.bn.running_var", "segment.S5_4.0.dwconv1.0.weight", "segment.S5_4.0.dwconv1.1.weight", "segment.S5_4.0.dwconv1.1.bias", "segment.S5_4.0.dwconv1.1.running_mean", "segment.S5_4.0.dwconv1.1.running_var", "segment.S5_4.0.dwconv2.0.weight", "segment.S5_4.0.dwconv2.1.weight", "segment.S5_4.0.dwconv2.1.bias", "segment.S5_4.0.dwconv2.1.running_mean", "segment.S5_4.0.dwconv2.1.running_var", "segment.S5_4.0.conv2.0.weight", "segment.S5_4.0.conv2.1.weight", "segment.S5_4.0.conv2.1.bias", "segment.S5_4.0.conv2.1.running_mean", "segment.S5_4.0.conv2.1.running_var", "segment.S5_4.0.shortcut.0.weight", "segment.S5_4.0.shortcut.1.weight", "segment.S5_4.0.shortcut.1.bias", "segment.S5_4.0.shortcut.1.running_mean", "segment.S5_4.0.shortcut.1.running_var", "segment.S5_4.0.shortcut.2.weight", "segment.S5_4.0.shortcut.3.weight", "segment.S5_4.0.shortcut.3.bias", "segment.S5_4.0.shortcut.3.running_mean", "segment.S5_4.0.shortcut.3.running_var", "segment.S5_4.1.conv1.conv.weight", "segment.S5_4.1.conv1.bn.weight", "segment.S5_4.1.conv1.bn.bias", "segment.S5_4.1.conv1.bn.running_mean", "segment.S5_4.1.conv1.bn.running_var", "segment.S5_4.1.dwconv.0.weight", "segment.S5_4.1.dwconv.1.weight", "segment.S5_4.1.dwconv.1.bias", "segment.S5_4.1.dwconv.1.running_mean", "segment.S5_4.1.dwconv.1.running_var", "segment.S5_4.1.conv2.0.weight", "segment.S5_4.1.conv2.1.weight", "segment.S5_4.1.conv2.1.bias", "segment.S5_4.1.conv2.1.running_mean", "segment.S5_4.1.conv2.1.running_var", "segment.S5_4.2.conv1.conv.weight", "segment.S5_4.2.conv1.bn.weight", "segment.S5_4.2.conv1.bn.bias", "segment.S5_4.2.conv1.bn.running_mean", "segment.S5_4.2.conv1.bn.running_var", "segment.S5_4.2.dwconv.0.weight", "segment.S5_4.2.dwconv.1.weight", "segment.S5_4.2.dwconv.1.bias", "segment.S5_4.2.dwconv.1.running_mean", "segment.S5_4.2.dwconv.1.running_var", "segment.S5_4.2.conv2.0.weight", "segment.S5_4.2.conv2.1.weight", "segment.S5_4.2.conv2.1.bias", "segment.S5_4.2.conv2.1.running_mean", "segment.S5_4.2.conv2.1.running_var", "segment.S5_4.3.conv1.conv.weight", "segment.S5_4.3.conv1.bn.weight", "segment.S5_4.3.conv1.bn.bias", "segment.S5_4.3.conv1.bn.running_mean", "segment.S5_4.3.conv1.bn.running_var", "segment.S5_4.3.dwconv.0.weight", "segment.S5_4.3.dwconv.1.weight", "segment.S5_4.3.dwconv.1.bias", "segment.S5_4.3.dwconv.1.running_mean", "segment.S5_4.3.dwconv.1.running_var", "segment.S5_4.3.conv2.0.weight", "segment.S5_4.3.conv2.1.weight", "segment.S5_4.3.conv2.1.bias", "segment.S5_4.3.conv2.1.running_mean", "segment.S5_4.3.conv2.1.running_var", "segment.S5_5.bn.weight", "segment.S5_5.bn.bias", "segment.S5_5.bn.running_mean", "segment.S5_5.bn.running_var", "segment.S5_5.conv_gap.conv.weight", "segment.S5_5.conv_gap.bn.weight", "segment.S5_5.conv_gap.bn.bias", "segment.S5_5.conv_gap.bn.running_mean", "segment.S5_5.conv_gap.bn.running_var", "segment.S5_5.conv_last.conv.weight", "segment.S5_5.conv_last.bn.weight", "segment.S5_5.conv_last.bn.bias", "segment.S5_5.conv_last.bn.running_mean", "segment.S5_5.conv_last.bn.running_var", "bga.left1.0.weight", "bga.left1.1.weight", "bga.left1.1.bias", "bga.left1.1.running_mean", "bga.left1.1.running_var", "bga.left1.2.weight", "bga.left2.0.weight", "bga.left2.1.weight", "bga.left2.1.bias", "bga.left2.1.running_mean", "bga.left2.1.running_var", "bga.right1.0.weight", "bga.right1.1.weight", "bga.right1.1.bias", "bga.right1.1.running_mean", "bga.right1.1.running_var", "bga.right2.0.weight", "bga.right2.1.weight", "bga.right2.1.bias", "bga.right2.1.running_mean", "bga.right2.1.running_var", "bga.right2.2.weight", "bga.conv.0.weight", "bga.conv.1.weight", "bga.conv.1.bias", "bga.conv.1.running_mean", "bga.conv.1.running_var", "head.conv.conv.weight", "head.conv.bn.weight", "head.conv.bn.bias", "head.conv.bn.running_mean", "head.conv.bn.running_var", "head.conv_out.0.weight", "head.conv_out.0.bias", "aux2.conv.conv.weight", "aux2.conv.bn.weight", "aux2.conv.bn.bias", "aux2.conv.bn.running_mean", "aux2.conv.bn.running_var", "aux2.conv_out.0.conv.weight", "aux2.conv_out.0.bn.weight", "aux2.conv_out.0.bn.bias", "aux2.conv_out.0.bn.running_mean", "aux2.conv_out.0.bn.running_var", "aux2.conv_out.1.weight", "aux2.conv_out.1.bias", "aux3.conv.conv.weight", "aux3.conv.bn.weight", "aux3.conv.bn.bias", "aux3.conv.bn.running_mean", "aux3.conv.bn.running_var", "aux3.conv_out.0.conv.weight", "aux3.conv_out.0.bn.weight", "aux3.conv_out.0.bn.bias", "aux3.conv_out.0.bn.running_mean", "aux3.conv_out.0.bn.running_var", "aux3.conv_out.1.weight", "aux3.conv_out.1.bias", "aux4.conv.conv.weight", "aux4.conv.bn.weight", "aux4.conv.bn.bias", "aux4.conv.bn.running_mean", "aux4.conv.bn.running_var", "aux4.conv_out.0.conv.weight", "aux4.conv_out.0.bn.weight", "aux4.conv_out.0.bn.bias", "aux4.conv_out.0.bn.running_mean", "aux4.conv_out.0.bn.running_var", "aux4.conv_out.1.weight", "aux4.conv_out.1.bias", "aux5_4.conv.conv.weight", "aux5_4.conv.bn.weight", "aux5_4.conv.bn.bias", "aux5_4.conv.bn.running_mean", "aux5_4.conv.bn.running_var", "aux5_4.conv_out.0.conv.weight", "aux5_4.conv_out.0.bn.weight", "aux5_4.conv_out.0.bn.bias", "aux5_4.conv_out.0.bn.running_mean", "aux5_4.conv_out.0.bn.running_var", "aux5_4.conv_out.1.weight", "aux5_4.conv_out.1.bias". 
	Unexpected key(s) in state_dict: "arch", "epoch", "state_dict", "optimizer". 

How can I solve it?

**Comment by CoinCheung** [comment]
How did you obtain your chekpoint file ?

**Comment by CoinCheung** [comment]
Closing this since this is not active anymore, maybe you have solved your problem.
