### ISSUE TITLE
different fps

### ISSUE THREAD

**Issue by duongdqq** [CoinCheung/BiSeNet#142]
Thanks @CoinCheung for your source code. I am researching your code and it is getting good results so far with bisenetv1. But, I find some conflict with the Bisenetv2 paper. According to the paper of Bisenetv2, the fps is 156 and 47.3 . But in this repository, the fps is just 50/16 for fp16 and fp32. Can anyone know why the speed is different from the paper and help me fix it out

**Comment by CoinCheung** [comment]
The test method is different from the paper, you can find more information in the readme.

**Comment by CoinCheung** [comment]
Closing this since you might figure it out yourself.
