### ISSUE TITLE
Inference from trt model

### ISSUE THREAD

**Issue by poornimajd** [CoinCheung/BiSeNet#144]
I was trying to convert the segmentation model to trt format.After conversion I was able to infer from it using the cpp code in the repository.But I was trying to get a python equivalent for the same.I tried the below code(snippet is shown here),but I get weird values in the output.

```
    engine = engine_utils.load_engine(
            trt_runtime, trt_engine_path)
    context = engine.create_execution_context()
    stream = cuda.Stream()
    img=cv2.imread("./114.jpg")
    img=cv2.resize(img,(1024,1024))
    
    to_tensor = transforms.Compose([
		    transforms.ToTensor(),
		    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
		    ])
    img = to_tensor(img)

    _, H, W = img.shape

    img = img.unsqueeze(0)
    host_input=to_numpy(img)
    cuda.memcpy_htod_async(device_input, host_input, stream)

    context.execute_async(bindings=[int(device_input), int(device_output)], stream_handle=stream.handle)
    
    cuda.memcpy_dtoh_async(host_output, device_output, stream)
    output_data = torch.Tensor(host_output).reshape(1,1024,1024)
   
    stream.synchronize()
    print(np.array(output_data,dtype=np.float32))
```

When I print the output using the last line,I get an array of 1024x1024 with the following values,a snippet is shown:
```

[[1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44
  1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44
  1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44 1.8e-44
  1.8e-44 1.8e-44 1.8e-44 1.8e-44 2.1e-44 2.1e-44 2.1e-44 2.1e-44 2.1e-44
  2.1e-44 2.1e-44 2.1e-44 2.1e-44 2.1e-44 2.1e-44 2.1e-44 2.1e-44 2.1e-44...]..]
```
But the same trt model when inferred using the cpp code gives the correct output.Can anyone help me to get the correct inference in python.
One thing I suspected is something is happening in this line in the cpp code which I am not able to replicate in python:
https://github.com/CoinCheung/BiSeNet/blob/master/tensorrt/trt_dep.cpp#L183
Any help is greatly appreciated.

**Comment by CoinCheung** [comment]
Hi, 

The datatype of the output is int64, have you ever tried to use int64 rather than float32?

**Comment by poornimajd** [comment]
Was able to solve it using a torchtrt repo. But I am not sure what was the exact issue.
Thank you for the suggestion.Will try it and reopen the issue if needed.
