### ISSUE TITLE
about ARM

### ISSUE THREAD

**Issue by staring-s** [CoinCheung/BiSeNet#146]
def forward(self, x):
        feat = self.conv(x)
        atten = F.avg_pool2d(feat, feat.size()[2:])
        atten = self.conv_atten(atten)
        atten = self.bn_atten(atten)
        atten = self.sigmoid_atten(atten)
        out = torch.mul(feat, atten)
        return out
I wonder why there is a self.conv?

**Comment by CoinCheung** [comment]
What is the problem with this `self.conv` ?

**Comment by CoinCheung** [comment]
I am closing this. Please open new issues or continue leave message here if you would like to have more discussions.
