### ISSUE TITLE
change FPS

### ISSUE THREAD

**Issue by caiyancheng** [CoinCheung/BiSeNet#147]
我发现这个网络的FPS大部分是被加载数据集（dataloader)拖后腿（只有12FPS），我尝试只对net(imgs)算时间后，发现速度可以达到惊人的230FPS

**Comment by caiyancheng** [comment]
V1

**Comment by caiyancheng** [comment]
没有使用作者的加速方式，直接time.time()进行计算

**Comment by obstract1** [comment]
您好，我的微信是ly19429,有幾個問題想要请教您

**Comment by obstract1** [comment]
> 没有使用作者的加速方式，直接time.time（）进行计算

您好，我的微信是ly19429，有几个问题想要请教您

**Comment by CoinCheung** [comment]
How did you tested? What is your gpu and pytorch/cuda version ?

**Comment by CoinCheung** [comment]
Close this with love & peace.
