### ISSUE TITLE
How to segmentation the video？？

### ISSUE THREAD

**Issue by rhythm-A** [CoinCheung/BiSeNet#149]
emmm..
now，the predict.py file can just segmentation the single frame picture.
how to use the model to segment video?

**Comment by CoinCheung** [comment]
Hi,

you need to parse the video and process each frame one by one. Maybe like this:
```
    cap = cv2.VideoCapture('video.mp4')
    success, frame = cap.read() 
    if success:
        .....

```

**Comment by CoinCheung** [comment]
Close this since this is not active anymore.
