### ISSUE TITLE
no logging output or .log file saved

### ISSUE THREAD

**Issue by Rundong-Li** [CoinCheung/BiSeNet#151]
I wonder why there is no logging information output in the bash terminal, and after `setup_logger()`, there is no .log file in the `./res` path. I think this is due to something wrong with `dist.init_process_group()`.

**Comment by CoinCheung** [comment]
Are you using pytorch1.8? If so, please use python 3.8 and change following line:
https://github.com/CoinCheung/BiSeNet/blob/90de8f9bdb6281f700087a5384996b18a4c6dae7/lib/logger.py#L19
to `force=True`.

There is some changes in pytorch1.8 which disabled logger.

**Comment by Rundong-Li** [comment]
> Are you using pytorch1.8? If so, please use python 3.8 and change following line:
> https://github.com/CoinCheung/BiSeNet/blob/90de8f9bdb6281f700087a5384996b18a4c6dae7/lib/logger.py#L19
> 
> 
> to `force=True`.
> There is some changes in pytorch1.8 which disabled logger.

Yes, that's the problem. I degrade to torch 1.6 and everything goes fine. Thanks for your quick reply!

**Comment by CoinCheung** [comment]
I am glad that you can make it work. I am closing this since you have solved your problem.
