### ISSUE TITLE
We can use torch2trt to convert torch model to trt model directly。

### ISSUE THREAD

**Issue by dd1ge** [CoinCheung/BiSeNet#152]
And torch2trt support the  conversion of bilinear interpolation op now, so we can replace  nn.PixelShuffle ops with bilinear interpolation ops  to get a lighter model。
Hope this information is helpful to you。
And thanks a lot, author.

**Comment by CoinCheung** [comment]
Yes, now that tensorrt 7.2 has come out, we can also do it with onnx. This code was updated almost one year ago when torch2trt was not working so well as now. Maybe I will modify it sometime in the future or the users are encouraged to explore.

**Comment by CoinCheung** [comment]
Thanks for tell me about this. I am closing this issue.
