### ISSUE TITLE
Hi,I have a problem:ValueError: Error initializing torch.distributed using tcp:// rendezvous: rank parameter missing

### ISSUE THREAD

**Issue by xihongZ** [CoinCheung/BiSeNet#164]
Traceback (most recent call last):
  File "/home/hi/ZXH/new test/bisenetv2/tools/train_amp.py", line 207, in <module>
    main()
  File "/home/hi/ZXH/new test/bisenetv2/tools/train_amp.py", line 199, in main
    rank=args.local_rank
  File "/home/hi/.conda/envs/pt160/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/hi/.conda/envs/pt160/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 119, in _tcp_rendezvous_handler
    raise _error("rank parameter missing")
ValueError: Error initializing torch.distributed using tcp:// rendezvous: rank parameter missing
How can I solve this problem？thanks

**Comment by CoinCheung** [comment]
Please use pytorch 1.8.1.

**Comment by xihongZ** [comment]
I used pytorch 1.8.1, but the same problem still occurs.

**Comment by CoinCheung** [comment]
Please describe what modifications did you make, and how did you run the scritp.

**Comment by xihongZ** [comment]
I did not modify it, just reproduce this code and run train_amp.py.

**Comment by CoinCheung** [comment]
how did you start training ?

**Comment by hao1305430263** [comment]
i change  this:
` dist.init_process_group(backend='nccl',
                                init_method='tcp://127.0.0.1:{}'.format(
                                    args.port),
                                world_size=torch.cuda.device_count(),
                                rank=args.local_rank)`
then it can run well

**Comment by xihongZ** [comment]
This I used is consistent with what you wrote above, which led to this error.  How did you modify it?

**Comment by xihongZ** [comment]
> i change this:
> ` dist.init_process_group(backend='nccl', init_method='tcp://127.0.0.1:{}'.format( args.port), world_size=torch.cuda.device_count(), rank=args.local_rank)`
> then it can run well



> i change this:
> ` dist.init_process_group(backend='nccl', init_method='tcp://127.0.0.1:{}'.format( args.port), world_size=torch.cuda.device_count(), rank=args.local_rank)`
> then it can run well

This I used is consistent with what you wrote above, which led to this error. How did you modify it?

**Comment by Napier7** [comment]
Hava you dealt with it ? I run it on windows, and I suspect windows caused the problem.

**Comment by huangqi111** [comment]
> Traceback (most recent call last):
> File "/home/hi/ZXH/new test/bisenetv2/tools/train_amp.py", line 207, in
> main()
> File "/home/hi/ZXH/new test/bisenetv2/tools/train_amp.py", line 199, in main
> rank=args.local_rank
> File "/home/hi/.conda/envs/pt160/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
> store, rank, world_size = next(rendezvous_iterator)
> File "/home/hi/.conda/envs/pt160/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 119, in _tcp_rendezvous_handler
> raise _error("rank parameter missing")
> ValueError: Error initializing torch.distributed using tcp:// rendezvous: rank parameter missing
> How can I solve this problem？thanks
now  you solve this problem？ how to solve this problem，I also Encounter this problems

**Comment by CoinCheung** [comment]
This is likely to be solved, since the author did not post the start method. I am closing this.
