### ISSUE TITLE
I used my own dataset to train the model successfully, but Nan appeared when evaluating the model.

### ISSUE THREAD

**Issue by WangzekunY** [CoinCheung/BiSeNet#165]
The training log is as follows：

iter: 79700/80000, lr: 0.000365, eta: 0:03:56, time: 79.87, loss: 0.3749, loss_pre: 0.1215, loss_aux0: 0.1223, loss_aux1: 0.1311
iter: 79800/80000, lr: 0.000253, eta: 0:02:37, time: 78.51, loss: 0.3866, loss_pre: 0.1257, loss_aux0: 0.1263, loss_aux1: 0.1346
iter: 79900/80000, lr: 0.000136, eta: 0:01:18, time: 79.39, loss: 0.3952, loss_pre: 0.1283, loss_aux0: 0.1291, loss_aux1: 0.1379
iter: 80000/80000, lr: 0.000000, eta: 0:00:00, time: 78.73, loss: 0.3896, loss_pre: 0.1265, loss_aux0: 0.1273, loss_aux1: 0.1358

save models to ./res/model_final.pth

evaluating the final model

  0%|          | 0/11 [00:00<?, ?it/s]
  9%|▉         | 1/11 [00:01<00:14,  1.48s/it]
 18%|█▊        | 2/11 [00:01<00:10,  1.13s/it]
 27%|██▋       | 3/11 [00:02<00:07,  1.14it/s]
 36%|███▋      | 4/11 [00:02<00:04,  1.43it/s]
 45%|████▌     | 5/11 [00:02<00:03,  1.75it/s]
 55%|█████▍    | 6/11 [00:02<00:02,  2.08it/s]
 64%|██████▎   | 7/11 [00:03<00:01,  2.46it/s]
 73%|███████▎  | 8/11 [00:03<00:01,  2.80it/s]
 82%|████████▏ | 9/11 [00:03<00:00,  3.11it/s]
 91%|█████████ | 10/11 [00:03<00:00,  3.38it/s]
100%|██████████| 11/11 [00:04<00:00,  3.60it/s]
100%|██████████| 11/11 [00:04<00:00,  2.66it/s]
single mIOU is: nan

  0%|          | 0/11 [00:00<?, ?it/s]
  9%|▉         | 1/11 [00:01<00:12,  1.27s/it]
 18%|█▊        | 2/11 [00:01<00:09,  1.02s/it]
 27%|██▋       | 3/11 [00:02<00:06,  1.21it/s]
 36%|███▋      | 4/11 [00:02<00:04,  1.47it/s]
 45%|████▌     | 5/11 [00:02<00:03,  1.74it/s]
 55%|█████▍    | 6/11 [00:03<00:02,  1.98it/s]
 64%|██████▎   | 7/11 [00:03<00:01,  2.19it/s]
 73%|███████▎  | 8/11 [00:03<00:01,  2.37it/s]
 82%|████████▏ | 9/11 [00:04<00:00,  2.52it/s]
 91%|█████████ | 10/11 [00:04<00:00,  2.64it/s]
100%|██████████| 11/11 [00:04<00:00,  2.73it/s]
100%|██████████| 11/11 [00:04<00:00,  2.27it/s]
single scale crop mIOU is: nan

  0%|          | 0/11 [00:00<?, ?it/s]
  9%|▉         | 1/11 [00:02<00:22,  2.26s/it]
 18%|█▊        | 2/11 [00:03<00:17,  1.98s/it]
 27%|██▋       | 3/11 [00:04<00:14,  1.78s/it]
 36%|███▋      | 4/11 [00:06<00:11,  1.64s/it]
 45%|████▌     | 5/11 [00:07<00:09,  1.54s/it]
 55%|█████▍    | 6/11 [00:08<00:07,  1.47s/it]
 64%|██████▎   | 7/11 [00:10<00:05,  1.42s/it]
 73%|███████▎  | 8/11 [00:11<00:04,  1.39s/it]
 82%|████████▏ | 9/11 [00:12<00:02,  1.36s/it]
 91%|█████████ | 10/11 [00:14<00:01,  1.34s/it]
100%|██████████| 11/11 [00:15<00:00,  1.33s/it]
100%|██████████| 11/11 [00:15<00:00,  1.40s/it]
ms flip mIOU is: nan

  0%|          | 0/11 [00:00<?, ?it/s]
  9%|▉         | 1/11 [00:04<00:40,  4.09s/it]
 18%|█▊        | 2/11 [00:07<00:34,  3.82s/it]
 27%|██▋       | 3/11 [00:10<00:28,  3.62s/it]
 36%|███▋      | 4/11 [00:13<00:24,  3.47s/it]
 45%|████▌     | 5/11 [00:16<00:20,  3.37s/it]
 55%|█████▍    | 6/11 [00:19<00:16,  3.30s/it]
 64%|██████▎   | 7/11 [00:22<00:13,  3.25s/it]
 73%|███████▎  | 8/11 [00:26<00:09,  3.22s/it]
 82%|████████▏ | 9/11 [00:29<00:06,  3.19s/it]
 91%|█████████ | 10/11 [00:32<00:03,  3.17s/it]
100%|██████████| 11/11 [00:35<00:00,  3.16s/it]
100%|██████████| 11/11 [00:35<00:00,  3.23s/it]
ms crop mIOU is: nan

|   single_scale |   single_scale_crop |   ms_flip |   ms_flip_crop |
|----------------+---------------------+-----------+----------------|
|            nan |                 nan |       nan |            nan |

**Comment by CoinCheung** [comment]
What modifications did make in the code? What is your own dataset is like ? 

Please add a line of `print(hist)` above the following line: 
https://github.com/CoinCheung/BiSeNet/blob/ad67baa4d77928acca09dd2648455f2a955de679/tools/evaluate.py#L78
What is the result of this?

**Comment by WangzekunY** [comment]
The files I have changed are mainly for train.py, trains_ amp. py, evaluate. py, demo. py in tools, and cityscapes_cv2.py in lib； bisenetv2, bisenetv1.py in lib/models. Change the number of categories in the above files, and update label_info in cityscapes_cv2.py. 

The datasets used is 421 urban and rural monitoring pictures collected by myself, including 6 Tags. 

I trained three weeks ago, and I have been trying to solve the problem since it appeared, but I haven't solved it. In addition, it is worth noting that when I train 500 iterations, some indicators have data, and some indicators are Nan.

Now I see that you have changed the code 7 days ago. Do you need to try to train with the new code?

**Comment by CoinCheung** [comment]
Please print the confusion matrix as I mentioned above, and see what is it like.

**Comment by WangzekunY** [comment]
Hello, due to the loss of the previous training model, I downloaded your updated code again for training test. But this time, there was an error when evaluating the model after the training. The error is as follows. Do you know how to deal with it？

iter: 500/800, lr: 0.017393, eta: 0:03:58, time: 78.74, loss: 2.4784, loss_pre: 0.8580, loss_aux0: 0.8072, loss_aux1: 0.8132
iter: 600/800, lr: 0.021896, eta: 0:02:38, time: 77.38, loss: 2.4956, loss_pre: 0.8635, loss_aux0: 0.8191, loss_aux1: 0.8130
iter: 700/800, lr: 0.027565, eta: 0:01:18, time: 77.61, loss: 2.5629, loss_pre: 0.8914, loss_aux0: 0.8322, loss_aux1: 0.8393
iter: 800/800, lr: 0.034703, eta: 0:00:00, time: 78.87, loss: 2.6418, loss_pre: 0.9213, loss_aux0: 0.8598, loss_aux1: 0.8608

save models to ./res/model_final.pth
Traceback (most recent call last):
  File "/mnt/BiSeNet02/tools/train.py", line 223, in <module>
Traceback (most recent call last):
  File "/mnt/BiSeNet02/tools/train.py", line 223, in <module>
    main()
  File "/mnt/BiSeNet02/tools/train.py", line 219, in main
    main()
  File "/mnt/BiSeNet02/tools/train.py", line 219, in main
    train()
  File "/mnt/BiSeNet02/tools/train.py", line 203, in train
    train()
  File "/mnt/BiSeNet02/tools/train.py", line 203, in train
    heads, mious = eval_model(cfg, net)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    heads, mious = eval_model(cfg, net)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
Traceback (most recent call last):
  File "/mnt/BiSeNet02/tools/train.py", line 223, in <module>
    main()
  File "/mnt/BiSeNet02/tools/train.py", line 219, in main
    train()
  File "/mnt/BiSeNet02/tools/train.py", line 203, in train
    heads, mious = eval_model(cfg, net)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
    return func(*args, **kwargs)
  File "./tools/evaluate.py", line 193, in eval_model
  File "./tools/evaluate.py", line 193, in eval_model
    return func(*args, **kwargs)
  File "./tools/evaluate.py", line 193, in eval_model
    org_aux = net.aux_mode
    org_aux = net.aux_mode
    org_aux = net.aux_mode
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'aux_mode'
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'aux_mode'
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'aux_mode'

**Comment by CoinCheung** [comment]
Please use `train_amp.py`, `train.py` is old.

If you would like to use `train.py`, you can change the following line:
https://github.com/CoinCheung/BiSeNet/blob/ad67baa4d77928acca09dd2648455f2a955de679/tools/train.py#L203
into:
```
   heads, mious = eval_model(cfg, net.module)
```

For you now, you can run evaluate.py to compute mou of your current trained model again.

**Comment by WangzekunY** [comment]
Thank you for your help, I have run through my datasets, and the evaluation result is not Nan. The indicators of V1 and V2 are as follows：

BiSeNetV1：
|   single_scale |   single_scale_crop |   ms_flip |   ms_flip_crop |
|----------------+---------------------+-----------+----------------|
|       0.795367 |            0.794575 |  0.819927 |       0.825408 |

BiSeNetV2：
|   single_scale |   single_scale_crop |   ms_flip |   ms_flip_crop |
|----------------+---------------------+-----------+----------------|
|       0.747897 |            0.753137 |  0.776916 |       0.781725 |

**Comment by 202041600047** [comment]
I have adjusted my dataset to the format of cityscapes, but errors are always reported when running train.py and evaluate.py. I want to divide my defect dataset into two colors. The defect part is white and the background part is black, so I modified cityscapes_ cv2.py, as follows:
labels_info = [
{"hasInstances": True, "category": "object", "catid": 0, "name": "backforward", "ignoreInEval": False, "id": 0, "color": [0, 0, 0], "trainId": 0},
{"hasInstances": True, "category": "object", "catid": 0, "name": "defect", "ignoreInEval": False, "id": 1, "color": [255, 255, 255], "trainId": 1},
{"hasInstances": False, "category": "vehicle", "catid": 7, "name": "license plate", "ignoreInEval": True, "id": -1, "color": [0, 0, 142], "trainId": -1}]
And I'm in train.py and evaluate.py, cityscapes_ cv2.py has modified the number of categories to 2, but I haven't modified others
.The following error occurred when I ran evaluate. py:

setup and restore model
0%| | 0/1018 [00:00<?, ?it/s]Traceback (most recent call last):
File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 294, in
main()
File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 290, in main
evaluate(cfg, args.weight_pth)
File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 262, in evaluate
heads, mious = eval_model(cfg, net)
File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
return func(*args, **kwargs)
File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 204, in eval_model
mIOU = single_scale(net, dl, cfg.n_cats)
File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 72, in call
hist += torch.bincount(
RuntimeError: shape '[2, 2]' is invalid for input of size 509
0%| | 0/1018 [00:02<?, ?it/s]

What should I do? thank you

> 谢谢你的帮助，我已经跑遍了我的数据集，评估结果不是Nan。V1和V2的指标如下：
> 
> BiSeNetV1：
> | single_scale | single_scale_crop | ms_flip | ms_flip_crop |
> |----------------+---------------------+------------ -+----------------|
> | 0.795367 | 0.794575 | 0.819927 | 0.825408 |
> 
> BiSeNetV2：
> | single_scale | single_scale_crop | ms_flip | ms_flip_crop |
> |----------------+---------------------+------------ -+----------------|
> | 0.747897 | 0.753137 | 0.776916 | 0.781725 |

**Comment by CoinCheung** [comment]
I am closing this since problem is solved. And the problem mentioned by @202041600047 has been answered in another issue.
