### ISSUE TITLE
caffe bisenet

### ISSUE THREAD

**Issue by zhangzhili1112** [CoinCheung/BiSeNet#166]
有人在做caffe版本的复现吗？我复现的只有37.9%的精度
Is anyone doing a copy of Caffe? I have only 37.9% accuracy

**Comment by CoinCheung** [comment]
Hi,

I do not have too much experience with caffe, but I have updated a demo of ncnn. 

If you want to deploy you model on mobile platforms where you cannot use pytorch or tensorrt, you can try ncnn.
