### ISSUE TITLE
Test result

### ISSUE THREAD

**Issue by shliang0603** [CoinCheung/BiSeNet#171]
@CoinCheung  Thank you very much for your excellent work. I have tested the segmentation effect in a real scene, mainly for pedestrian segmentation, but the effect is very poor. I want to know if I want to improve the segmentation effect of pedestrian, should I use other datasets for retraining ？Can you give me some constructive advice?

Below is my test results, I only showed the category of person by filtering.
![image](https://user-images.githubusercontent.com/37186266/127456529-fb3994db-2cba-48d4-8268-bbee635c7e1a.png)

**Comment by CoinCheung** [comment]
Are you using model pretrained on cityscapes or coco directly? If you, maybe you still need to train on your own dataset, or  at least fine tune on it. There is likely to be some domain gap between the datasets I used and your test dataset.

**Comment by shliang0603** [comment]
Ok, thank you very much for your reply, do you have any good suggestions about pedestrian segmentation dataset recommendation

**Comment by CoinCheung** [comment]
Sorry that I am not familiar with this field. Both cityscapes and cocostuff have category of "person". Maybe you need to collect and annotate your own dataset if these datasets do not satisfy your requirement.

**Comment by CoinCheung** [comment]
I am closing this because question is answered.
