### ISSUE TITLE
label probelm

### ISSUE THREAD

**Issue by huangqi111** [CoinCheung/BiSeNet#175]
I use cityscapes dataset,label use  gtFine_color.png ，gtFine_instanceIds.png，gtFine_instanceTrainIds.png，gtFine_labelIds.png and gtFine_labelTrainIds.png.  which kind of label     I should use .l use labelTrainIds.png ,the result is very bad

**Comment by CoinCheung** [comment]
Please follow the method in ReadMe.md to prepare dataset.
If you find result is bad, please post the detail of your operations, and let us see what is likely to be the reason or if there are errors in the code.

**Comment by huangqi111** [comment]
I download datasets by the Baidu Disk.do not download from offical.l train by python tools/train.py .l have only one gpu

**Comment by huangqi111** [comment]
save models to ./res/model_final.pth

evaluating the final model
  0%|                                                                                                               | 0/5000 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [34:43<00:00,  2.40it/s]
single mIOU is: 0.0796331912279129

  0%|                                                                                                               | 0/5000 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [42:10<00:00,  1.98it/s]
single scale crop mIOU is: 0.07808423787355423

  0%|                                                                                                               | 0/5000 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [50:07<00:00,  1.66it/s]
ms flip mIOU is: 0.08314504474401474

  0%|                                                                                                               | 0/5000 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [2:02:43<00:00,  1.47s/it]
ms crop mIOU is: 0.07689348608255386

|   single_scale |   single_scale_crop |   ms_flip |   ms_flip_crop |
|----------------+---------------------+-----------+----------------|
|      0.0796332 |           0.0780842 |  0.083145 |      0.0768935 |



this is using coco dataset. I use tools/demo
.py to test.   the result is very bad,l use one gpu to train.

**Comment by CoinCheung** [comment]
What is your batch size, how many iterations did you train, did you adjust learning rate if you use batch size other than 16?

**Comment by huangqi111** [comment]
I use  original  bisenetv2_coco.py file to train  by one gpu.

cfg = dict(
    model_type='bisenetv2',
    n_cats=171,
    num_aux_heads=4,
    lr_start=5e-3,
    weight_decay=1e-4,
    warmup_iters=1000,
    max_iter=180000,
    dataset='CocoStuff',
    im_root='./datasets/coco',
    train_im_anns='./datasets/coco/train.txt',
    val_im_anns='./datasets/coco/val.txt',
    scales=[0.75, 2.],
    cropsize=[640, 640],
    eval_crop=[640, 640],
    eval_scales=[0.5, 0.75, 1, 1.25, 1.5, 1.75],
    ims_per_gpu=2,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=True,
    respth='./res',
)

**Comment by huangqi111** [comment]
I  change class：

 net = model_factory[cfg.model_type](171)

 model = BiSeNetV2(n_classes=171)

**Comment by huangqi111** [comment]
I change class：

 model = BiSeNetV2 (n_classes=171)

net = model_factory[cfg.model_type](171)

**Comment by CoinCheung** [comment]
@huangqi111 So you are training with a total batch size of 2, and you did not adjust learning rate according to batch size? If so, you are not expected to see good result...

**Comment by huangqi111** [comment]
I just follow  your code ，I only change the class，model = BiSeNetV2 (n_classes=171)，net = model_factory[model_type](171)  ，I try change lr to see the result

**Comment by CoinCheung** [comment]
Your batch size is too small, I used 4-8 gpu to maintain a total batch size of 16. If you use small batch, the result would not be good.

**Comment by huangqi111** [comment]
iter: 7800/180000, lr: 0.002656, eta: 1 day, 17:57:13, time: 87.70, loss: 16.5713, loss_pre: 2.8955, loss_aux0: 3.7527, loss_aux1: 3.5513, loss_aux2: 3.3679, loss_aux3: 3.0040
iter: 7900/180000, lr: 0.002654, eta: 1 day, 17:55:54, time: 88.07, loss: 16.2172, loss_pre: 2.8302, loss_aux0: 3.7051, loss_aux1: 3.4895, loss_aux2: 3.2827, loss_aux3: 2.9098
iter: 8000/180000, lr: 0.002653, eta: 1 day, 17:54:31, time: 87.93, loss: 16.3306, loss_pre: 2.8766, loss_aux0: 3.7129, loss_aux1: 3.4935, loss_aux2: 3.3050, loss_aux3: 2.9427
iter: 8100/180000, lr: 0.002652, eta: 1 day, 17:52:48, time: 87.01, loss: 16.4971, loss_pre: 2.9006, loss_aux0: 3.7203, loss_aux1: 3.5198, loss_aux2: 3.3321, loss_aux3: 3.0243
iter: 8200/180000, lr: 0.002650, eta: 1 day, 17:51:25, time: 87.92, loss: 16.5585, loss_pre: 2.9296, loss_aux0: 3.7224, loss_aux1: 3.5177, loss_aux2: 3.3602, loss_aux3: 3.0286
iter: 8300/180000, lr: 0.002649, eta: 1 day, 17:50:05, time: 88.08, loss: 16.2669, loss_pre: 2.7938, loss_aux0: 3.7470, loss_aux1: 3.5084, loss_aux2: 3.2905, loss_aux3: 2.9273
iter: 8400/180000, lr: 0.002647, eta: 1 day, 17:48:35, time: 87.61, loss: 16.6333, loss_pre: 2.9148, loss_aux0: 3.7747, loss_aux1: 3.5690, loss_aux2: 3.3679, loss_aux3: 3.0069
iter: 8500/180000, lr: 0.002646, eta: 1 day, 17:47:21, time: 88.41, loss: 16.4110, loss_pre: 2.8986, loss_aux0: 3.7299, loss_aux1: 3.5141, loss_aux2: 3.3219, loss_aux3: 2.9465
iter: 8600/180000, lr: 0.002645, eta: 1 day, 17:46:02, time: 88.17, loss: 16.6112, loss_pre: 2.8885, loss_aux0: 3.7884, loss_aux1: 3.5720, loss_aux2: 3.3629, loss_aux3: 2.9994
iter: 8700/180000, lr: 0.002643, eta: 1 day, 17:44:50, time: 88.49, loss: 16.8448, loss_pre: 2.9592, loss_aux0: 3.8061, loss_aux1: 3.6062, loss_aux2: 3.4047, loss_aux3: 3.0686
iter: 8800/180000, lr: 0.002642, eta: 1 day, 17:44:41, time: 91.81, loss: 16.4760, loss_pre: 2.8873, loss_aux0: 3.7287, loss_aux1: 3.5347, loss_aux2: 3.3414, loss_aux3: 2.9839
iter: 8900/180000, lr: 0.002641, eta: 1 day, 17:44:25, time: 91.51, loss: 16.2549, loss_pre: 2.7863, loss_aux0: 3.7355, loss_aux1: 3.5261, loss_aux2: 3.2871, loss_aux3: 2.9199
iter: 9000/180000, lr: 0.002639, eta: 1 day, 17:43:37, time: 89.89, loss: 16.3789, loss_pre: 2.8811, loss_aux0: 3.7295, loss_aux1: 3.5164, loss_aux2: 3.2987, loss_aux3: 2.9532
iter: 9100/180000, lr: 0.002638, eta: 1 day, 17:43:18, time: 91.55, loss: 16.4068, loss_pre: 2.8754, loss_aux0: 3.7266, loss_aux1: 3.5059, loss_aux2: 3.3152, loss_aux3: 2.9837
iter: 9200/180000, lr: 0.002636, eta: 1 day, 17:42:49, time: 91.06, loss: 16.4073, loss_pre: 2.8493, loss_aux0: 3.7492, loss_aux1: 3.5295, loss_aux2: 3.3247, loss_aux3: 2.9546
iter: 9300/180000, lr: 0.002635, eta: 1 day, 17:41:58, time: 89.90, loss: 16.5295, loss_pre: 2.9387, loss_aux0: 3.7094, loss_aux1: 3.5280, loss_aux2: 3.3401, loss_aux3: 3.0134
iter: 9400/180000, lr: 0.002634, eta: 1 day, 17:41:34, time: 91.47, loss: 16.0664, loss_pre: 2.8346, loss_aux0: 3.6255, loss_aux1: 3.4314, loss_aux2: 3.2541, loss_aux3: 2.9207
iter: 9500/180000, lr: 0.002632, eta: 1 day, 17:41:11, time: 91.60, loss: 16.0828, loss_pre: 2.7522, loss_aux0: 3.7105, loss_aux1: 3.4959, loss_aux2: 3.2687, loss_aux3: 2.8556
iter: 9600/180000, lr: 0.002631, eta: 1 day, 17:40:17, time: 89.92, loss: 16.2489, loss_pre: 2.8469, loss_aux0: 3.6976, loss_aux1: 3.4774, loss_aux2: 3.2774, loss_aux3: 2.9496


The loss can’t come down, I changed the learning rate several times, and it’s always 16.    Do I need to modify other parameters when I use cocostuff dataset

**Comment by huangqi111** [comment]
iter: 7800/180000, lr: 0.002656, eta: 1 day, 17:57:13, time: 87.70, loss: 16.5713, loss_pre: 2.8955, loss_aux0: 3.7527, loss_aux1: 3.5513, loss_aux2: 3.3679, loss_aux3: 3.0040
iter: 7900/180000, lr: 0.002654, eta: 1 day, 17:55:54, time: 88.07, loss: 16.2172, loss_pre: 2.8302, loss_aux0: 3.7051, loss_aux1: 3.4895, loss_aux2: 3.2827, loss_aux3: 2.9098
iter: 8000/180000, lr: 0.002653, eta: 1 day, 17:54:31, time: 87.93, loss: 16.3306, loss_pre: 2.8766, loss_aux0: 3.7129, loss_aux1: 3.4935, loss_aux2: 3.3050, loss_aux3: 2.9427
iter: 8100/180000, lr: 0.002652, eta: 1 day, 17:52:48, time: 87.01, loss: 16.4971, loss_pre: 2.9006, loss_aux0: 3.7203, loss_aux1: 3.5198, loss_aux2: 3.3321, loss_aux3: 3.0243
iter: 8200/180000, lr: 0.002650, eta: 1 day, 17:51:25, time: 87.92, loss: 16.5585, loss_pre: 2.9296, loss_aux0: 3.7224, loss_aux1: 3.5177, loss_aux2: 3.3602, loss_aux3: 3.0286
iter: 8300/180000, lr: 0.002649, eta: 1 day, 17:50:05, time: 88.08, loss: 16.2669, loss_pre: 2.7938, loss_aux0: 3.7470, loss_aux1: 3.5084, loss_aux2: 3.2905, loss_aux3: 2.9273
iter: 8400/180000, lr: 0.002647, eta: 1 day, 17:48:35, time: 87.61, loss: 16.6333, loss_pre: 2.9148, loss_aux0: 3.7747, loss_aux1: 3.5690, loss_aux2: 3.3679, loss_aux3: 3.0069
iter: 8500/180000, lr: 0.002646, eta: 1 day, 17:47:21, time: 88.41, loss: 16.4110, loss_pre: 2.8986, loss_aux0: 3.7299, loss_aux1: 3.5141, loss_aux2: 3.3219, loss_aux3: 2.9465
iter: 8600/180000, lr: 0.002645, eta: 1 day, 17:46:02, time: 88.17, loss: 16.6112, loss_pre: 2.8885, loss_aux0: 3.7884, loss_aux1: 3.5720, loss_aux2: 3.3629, loss_aux3: 2.9994
iter: 8700/180000, lr: 0.002643, eta: 1 day, 17:44:50, time: 88.49, loss: 16.8448, loss_pre: 2.9592, loss_aux0: 3.8061, loss_aux1: 3.6062, loss_aux2: 3.4047, loss_aux3: 3.0686
iter: 8800/180000, lr: 0.002642, eta: 1 day, 17:44:41, time: 91.81, loss: 16.4760, loss_pre: 2.8873, loss_aux0: 3.7287, loss_aux1: 3.5347, loss_aux2: 3.3414, loss_aux3: 2.9839
iter: 8900/180000, lr: 0.002641, eta: 1 day, 17:44:25, time: 91.51, loss: 16.2549, loss_pre: 2.7863, loss_aux0: 3.7355, loss_aux1: 3.5261, loss_aux2: 3.2871, loss_aux3: 2.9199
iter: 9000/180000, lr: 0.002639, eta: 1 day, 17:43:37, time: 89.89, loss: 16.3789, loss_pre: 2.8811, loss_aux0: 3.7295, loss_aux1: 3.5164, loss_aux2: 3.2987, loss_aux3: 2.9532
iter: 9100/180000, lr: 0.002638, eta: 1 day, 17:43:18, time: 91.55, loss: 16.4068, loss_pre: 2.8754, loss_aux0: 3.7266, loss_aux1: 3.5059, loss_aux2: 3.3152, loss_aux3: 2.9837
iter: 9200/180000, lr: 0.002636, eta: 1 day, 17:42:49, time: 91.06, loss: 16.4073, loss_pre: 2.8493, loss_aux0: 3.7492, loss_aux1: 3.5295, loss_aux2: 3.3247, loss_aux3: 2.9546
iter: 9300/180000, lr: 0.002635, eta: 1 day, 17:41:58, time: 89.90, loss: 16.5295, loss_pre: 2.9387, loss_aux0: 3.7094, loss_aux1: 3.5280, loss_aux2: 3.3401, loss_aux3: 3.0134
iter: 9400/180000, lr: 0.002634, eta: 1 day, 17:41:34, time: 91.47, loss: 16.0664, loss_pre: 2.8346, loss_aux0: 3.6255, loss_aux1: 3.4314, loss_aux2: 3.2541, loss_aux3: 2.9207
iter: 9500/180000, lr: 0.002632, eta: 1 day, 17:41:11, time: 91.60, loss: 16.0828, loss_pre: 2.7522, loss_aux0: 3.7105, loss_aux1: 3.4959, loss_aux2: 3.2687, loss_aux3: 2.8556
iter: 9600/180000, lr: 0.002631, eta: 1 day, 17:40:17, time: 89.92, loss: 16.2489, loss_pre: 2.8469, loss_aux0: 3.6976, loss_aux1: 3.4774, loss_aux2: 3.2774, loss_aux3: 2.9496


The loss can’t come down, I changed the learning rate several times, and it’s always 16.    Do I need to modify other parameters when I use cocostuff dataset

**Comment by huangqi111** [comment]
I set max_iter=180000，train is over，the loss is still 16

**Comment by huangqi111** [comment]
![image](https://user-images.githubusercontent.com/56476646/129879169-ce49b20f-1d0d-4d47-8c71-0b0b9aea41fb.png)


this is  result image

**Comment by CoinCheung** [comment]
I mean no offense, but I recommand you give up, because a batch size of 2 is too small. In theory, small batch size would make batch normalization behave badly. The model tends to fail to converge, and not generalize well.

If you insist on this, please follow these tips(based on you batch size of 2):
* set lr to be 1/8 of the default 
* set max_iter to be 8x of the default

**Comment by huangqi111** [comment]
I train  my dataset , It have three classes.evaluating the final model,the  mIOU is 1,aluating the final model
  0%|                                                                                                                 | 0/15 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.14it/s]
single mIOU is: 1.0

  0%|                                                                                                                 | 0/15 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.03it/s]
single scale crop mIOU is: 1.0

  0%|                                                                                                                 | 0/15 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:22<00:00,  1.52s/it]
ms flip mIOU is: 1.0

  0%|                                                                                                                 | 0/15 [00:00<?, ?it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:29<00:00,  1.96s/it]
ms crop mIOU is: 1.0

why  I  try to test,the result is bad 
![res](https://user-images.githubusercontent.com/56476646/130349799-4bad04f1-7337-4ae0-a405-9edd915973cb.jpg)
