### ISSUE TITLE
i find a bug in tools/evaluate.py

### ISSUE THREAD

**Issue by WangYunnan** [CoinCheung/BiSeNet#176]
line 122: Why do exp operations need to be taken? Although theoretically does not affect the final result, in actual testing, the final result will be slightly higher

**Comment by CoinCheung** [comment]
Hi,

That is due to some historical reason. You can remove the `exp` function if you feel it is not useful. The difference should be very limited.

**Comment by CoinCheung** [comment]
Thanks for telling this. I am closing this thread. If you want more discussion, please leave a message here directly.
