### ISSUE TITLE
Using Semantic branch only to improve the speed

### ISSUE THREAD

**Issue by RoyZhDec** [CoinCheung/BiSeNet#177]
First of all, thank you for your excellent work. I have a question to consult. According to the description in the ablation experiment part of the paper, if only the semantic branch is used and the detail branch is cut off, the calculation of the entire model will drop from 21.15GFLOPs to 7.63GFLOPs, so I am expecting a 3x speed increase, so I try to rewrite your network code, and only the semantic branch is used (one path). The final result is also in line with expectations, but the speed has not been greatly improved, only from the previous 100fps to about 125-130fps, which did not reach the 300fps I expected. Is my understanding of GFLOPs incorrect, or am I ignoring other issues?

Looking forward to your answer, thank you very much

**Comment by RoyZhDec** [comment]
FYI, the one branch model's pth size is 17MB, while the original model is 21MB.

**Comment by CoinCheung** [comment]
How did you test the fps? Did you get rid of the time of loading data from host memory to gpu?


==================================

The FLOPs is not always strictly aligned with fps. The running time includes both time of computation and time of accessing memory. For gpus, you have to load the data from gpu global memory to caches before computing. This process takes time, and the the time consumption is larger when you do not access memory contiguously. That is the reason why `sepconv` are not much faster than plain `conv` as expected. Additionally, some reduce operations such as sum up along given axis is not easy to implemented parallelly. If you want to sum up a vector of length N(N<1024), you are actually runing log(N) times, even though your gpu has more computation cores than N. You cannot always fully utilize memory bandwidth or the computation cores, so the FLOPs does not always determine the speed.

**Comment by RoyZhDec** [comment]
Thank you very much for your answer, I think I get your point.
