### ISSUE TITLE
how to  change labels_info to adpat own dataset

### ISSUE THREAD

**Issue by huangqi111** [CoinCheung/BiSeNet#179]
I have two classes to Qūfēn，it name is luosi，luomu，how   to  change label_info  right

  {"hasInstances": False, "category": "void", "catid": 0, "name": "unlabeled", "ignoreInEval": True, "id": 0, "color": [0, 0, 0], "trainId": 255},
    {"hasInstances": True, "category": "object", "catid": 1, "name": "luosi", "ignoreInEval": False, "id": 1, "color": [0, 0, 255], "trainId": 1},
    {"hasInstances": True, "category": "object", "catid": 2, "name": "luomu", "ignoreInEval": False, "id": -1, "color": [255, 0, 0], "trainId": -1},

**Comment by CoinCheung** [comment]
Hi, 
catid is the values of your label file, trainid is the label you want your catid map into.
For example, in your label, you have only two values 0 and 1, and they are the two categories of segmentation, you can use this:

{"hasInstances": False, "category": "void", "catid": 0, "name": "unlabeled", "ignoreInEval": True, "id": 0, "color": [0, 0, 0], "trainId": 0},
{"hasInstances": True, "category": "object", "catid": 1, "name": "luosi", "ignoreInEval": False, "id": 1, "color": [0, 0, 255], "trainId": 1},
