### ISSUE TITLE
evaluate.py  error!!!!!

### ISSUE THREAD

**Issue by chen1234520** [CoinCheung/BiSeNet#186]
torch.nn.modules.module.ModuleAttributeError: 'BiSeNetV2' object has no attribute 'module'!

    >>net.load_state_dict(torch.load(weight_pth, map_location='cpu'))
    >>net.cuda()
   

I modify the model loading method！

>>net = torch.load(weight_pth, map_location='cpu') 

get new error !

Traceback (most recent call last):
  File "tools/evaluate.py", line 296, in <module>
    main()
  File "tools/evaluate.py", line 292, in main
    evaluate(cfg, args.weight_pth)
  File "tools/evaluate.py", line 264, in evaluate
    heads, mious = eval_model(cfg, net.module)
AttributeError: 'collections.OrderedDict' object has no attribute 'module'

**Comment by drCJH** [comment]
For the first error, change the line 'heads, mious = eval_model(cfg, net.module)' to 'heads, mious = eval_model(cfg, net)'

**Comment by CoinCheung** [comment]
Hi,

As @drCJH mentioned, if you eval with your own models trained with distributd mode, please make sure to use `net.module` rather than the `net` dirctly.
