### ISSUE TITLE
use model in ros

### ISSUE THREAD

**Issue by Wuxinxiaoshifu** [CoinCheung/BiSeNet#187]
i want to use my trained model in ros,which i subscribe image topic and run bisenet to get the result of image segmentation.
can you gives me some suggestions?

**Comment by CoinCheung** [comment]
Hi, I have no experience with ros. If it is a linux system based on arm platform, maybe you can try ncnn. Sorry that I cannot provide useful advices.

**Comment by jsj441805126** [comment]
> i want to use my trained model in ros,which i subscribe image topic and run bisenet to get the result of image segmentation.我想在ROS中使用我训练好的模型，我订阅了图像主题并运行bisenet来获得图像分割的结果。 can you gives me some suggestions?你能给我一些建议吗？

Hello, subscribe to the image theme in ROS and run bisenet to get the result of image segmentation. Have you implemented this? Can you give me some guidance?
