### ISSUE TITLE
the mean value and std value of the citysacpes dataset

### ISSUE THREAD

**Issue by weiningwei** [CoinCheung/BiSeNet#189]
Hello, thank you for the code. But if I want to use your pretrained weight to test my dataset, which the scene is relatively simple, only including vehicles. In your [demo.py,](https://github.com/CoinCheung/BiSeNet/blob/master/tools/demo.py) I found the following code
`# prepare data
to_tensor = T.ToTensor(
    mean=(0.3257, 0.3690, 0.3223), # city, rgb
    std=(0.2112, 0.2148, 0.2115),
)`
So I want to ask you what meaning the value is and how to get the value of my dataset.

**Comment by CoinCheung** [comment]
The mean and std is computed from training set, it is the mean and std value of each channel computed from the whole training set. 

These values should be computed before training phase, while in the inference phase, you only need to set them to the identical values like in the training phase.

So if you want to use my pretrained models, you can set them same as in the demo.py. It depends on the training parameters not your own dataset.

**Comment by weiningwei** [comment]
Thanks for your reply.
