### ISSUE TITLE
Has anyone know how to train medical datasets with single channel?

### ISSUE THREAD

**Issue by Byronnar** [CoinCheung/BiSeNet#191]
Has anyone know how to train medical datasets with single channel? What shold be modify?
@CoinCheung

**Comment by CoinCheung** [comment]
Here is how I read images:
https://github.com/CoinCheung/BiSeNet/blob/44b230724fd031c22fe9ee12c2adbec3199e3656/lib/base_dataset.py#L52
you can modify this according to your need.

**Comment by Byronnar** [comment]
I know here. But should I modify the network in the bisenet_v2.py?

**Comment by CoinCheung** [comment]
There are two modifications that you should make to use bisenetv2:
https://github.com/CoinCheung/BiSeNet/blob/44b230724fd031c22fe9ee12c2adbec3199e3656/lib/models/bisenetv2.py#L53
and
https://github.com/CoinCheung/BiSeNet/blob/44b230724fd031c22fe9ee12c2adbec3199e3656/lib/models/bisenetv2.py#L370

In the first place, you need to modify the input channel from 3 to 1, and in the second place, you should change `strict=True` into `strict=False`.

**Comment by CoinCheung** [comment]
Actually, I think the easiest way is to read the images as 3-channel images. In that way you do not need to modify code.

**Comment by Byronnar** [comment]
Really grateful to you，I will try.

**Comment by Byronnar** [comment]
I have changed the code, but can not load the pretrained model, the error show as below: 
```
File "/data/byronnar/packages/Segmentation_PyTorch/code/networks/bisenetv2.py", line 364, in load_pretrain
    child.load_state_dict(state[name], strict=False)    # modify 3
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DetailBranch:
        size mismatch for S1.0.conv.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3]).
```
could you give me some advices?

**Comment by Byronnar** [comment]
> Actually, I think the easiest way is to read the images as 3-channel images. In that way you do not need to modify code.

Due to some situation, I can not use this method. But I want use pretrained model. Thank you.

**Comment by CoinCheung** [comment]
My bad, you should replace the second place with the following:
```
                st_sd = state[name]
                st_chd = child.state_dict()
                new_st = {}
                for k,v in st_sd.items():
                    if not st_sd[k].size() == st_chd[k].size(): continue
                    new_st[k] = v
                child.load_state_dict(new_st)
```
You can read the associated part of the code, it is very easy.

**Comment by Byronnar** [comment]
Appreciate your help very much， I will read the associated part of the code.  Thanks.

**Comment by Byronnar** [comment]
> My bad, you should replace the second place with the following:
> 
> ```
>                 st_sd = state[name]
>                 st_chd = child.state_dict()
>                 new_st = {}
>                 for k,v in st_sd.items():
>                     if not st_sd[k].size() == st_chd[k].size(): continue
>                     new_st[k] = v
>                 child.load_state_dict(new_st)
> ```
> 
> You can read the associated part of the code, it is very easy.

I can train the datasets by modify this code, Thanks. And last question, could please tell me how to modify the BiseNetv1 code? Always load pretrained model. I am not good at this.  Thank u very much.

**Comment by CoinCheung** [comment]
Maybe you can add a line:
```
self.cp.resnet.conv1 = nn.Conv2d(1, 64, 3, 1, 1)
```
after this:
https://github.com/CoinCheung/BiSeNet/blob/44b230724fd031c22fe9ee12c2adbec3199e3656/lib/models/bisenetv1.py#L277

**Comment by Byronnar** [comment]
Yes, I have solved this problem. Thank you very much for your patient guidance。
This method is useful.
```
    def init_weight(self):
        state_dict = modelzoo.load_url(resnet18_url)
        self_state_dict = self.state_dict()

        new_st = {}
        for k, v in state_dict.items():
            if 'fc' in k: continue
            if not self_state_dict[k].size() == state_dict[k].size (): continue
            new_st[k] = v
```
Thanks.
