### ISSUE TITLE
Great projects! Could you please tell me how to train own backbone_v2.pth ? 

### ISSUE THREAD

**Issue by Byronnar** [CoinCheung/BiSeNet#192]
Well, backbone_v2.pth trained on which datasets?  Can I train a backbone weights? Looking forward to your reply. Thank u.

**Comment by CoinCheung** [comment]
It is trained on imagnet dataset, I cannot provide training script now, because it is not my work, and people around me is not likely to allow me to upload the code.

**Comment by Byronnar** [comment]
Thanks for your reply so much! I have another question,can I train one-chinnael gray images?  And how should I modify the code to load the  backbone_v2.pth , Thanks .

**Comment by Byronnar** [comment]
Really grateful to you，I will try.
