### ISSUE TITLE
Single Scale evaluation size

### ISSUE THREAD

**Issue by lkdci** [CoinCheung/BiSeNet#193]
Thanks for the great work. I have a few questions about the evaluation process.
It seems that your single scale reported results were achieved on the full image resolution of (1024, 2048), meaning applying model inference with full size without any down-sampling to training size.
Yet the original paper apply the following process:
"With the input of 2048 × 1024 resolution, we first resize it to 1024 × 512 resolution to inference and then resize the prediction to the original size of the input."
Am I missing something?

**Comment by CoinCheung** [comment]
Hi,

You are right about this. Cropsize of training and inference should roughly align with each other. Though infering on images a bit larger than training crop size is acceptable, infering on too large images is detrimental (or so I believe). 

I did not try this when I found the result is close to result in the paper. So you are right on this details. Thanks for telling me this.
