### ISSUE TITLE
lb_ignore value not use in loss function

### ISSUE THREAD

**Issue by nicexxact** [CoinCheung/BiSeNet#194]
Hello, 

The argument lb_ignore from the dataset is not used in OhemCELoss or in MscEval. By default is 255 for both.

**Comment by CoinCheung** [comment]
Hi,

Thanks for telling me this !!! 

You are right, the lb_ingore at each part is not aligned. Currently, I have not met datasets that have 200+ categories thus using the default value of 255 is enough. Maybe I will fix this in the future.
