### ISSUE TITLE
onnx2ncnn problem

### ISSUE THREAD

**Issue by lavender-ling** [CoinCheung/BiSeNet#196]
您好，我在进行 /path/to/ncnn/build/tools/onnx/onnx2ncnn model_v2_sim.onnx model_v2_sim.param model_v2_sim.bin这步操作时，出现以下错，onnx模型已经简化过了，请问有什么解决方法？谢谢。
ArgMax not supported yet!
  # axis=1
  # keepdims=0

**Comment by CoinCheung** [comment]
what platform are you using, and which version of pytorch/ncnn are you using?

**Comment by lavender-ling** [comment]
> what platform are you using, and which version of pytorch/ncnn are you using?
ubuntu 18.04
opencv 4.5.4
pytorch 1.7.1
ncnn     the laster

**Comment by CoinCheung** [comment]
Please follow the specifications in readme.

There are two points I found different from readme;
* I used commit of 9391fae741a1fb8d58cdfdc92878a5e9800f8567
* you did not set `--aux-mode` as what is does in readme

Please make these two things align with readme, and let us see whether problem still exists.

**Comment by lavender-ling** [comment]
> Please follow the specifications in readme.
> 
> There are two points I found different from readme;
> 
> * I used commit of 9391fae741a1fb8d58cdfdc92878a5e9800f8567
> * you did not set `--aux-mode` as what is does in readme
> 
> Please make these two things align with readme, and let us see whether problem still exists.
ok，i will try it， thanks

**Comment by lavender-ling** [comment]
after the change，the problem solved，thanks
