### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by CaoXiang-space** [CoinCheung/BiSeNet#198]
hello,
thanks for your amzing work!! I have reproduced the source code using Cityscapes , and the accuracy is close to the results in the paper. Now I have prepared my binary data set, and have changed the corresponding files, but there are some mistakes that upset me, I really need help~~~~~~~
![image](https://user-images.githubusercontent.com/64094381/141302215-8dba7319-42fd-42ee-9c43-15f2658083bd.png)

**Comment by CaoXiang-space** [comment]
I figured out! my label pictures are not binary images,so I changed then  and then there are no problems.

**Comment by huangwan-jiayi** [comment]
> I figured out! my label pictures are not binary images,so I changed then and then there are no problems.

hallo，I encountered the same problem, can you teach me how to do it。Thanks！
