### ISSUE TITLE
MIOU

### ISSUE THREAD

**Issue by CaoXiang-space** [CoinCheung/BiSeNet#201]
Hi,
I tried my own dataset,there are two classes,but the eval results is amazing that  the mIou value is 1.I guess it is caused by data imbalance. Do you have any opinion?
 
![image](https://user-images.githubusercontent.com/64094381/141672622-dffd2924-21d9-46fd-a3ca-2b788a257ecd.png)

**Comment by CaoXiang-space** [comment]
I also tried example.py,but the res.png is not the ideal result,it cannot give out the category,sad...

**Comment by CoinCheung** [comment]
Sorry for being so late, have you solved your problem? May I close this now?
