### ISSUE TITLE
老哥，请教一下，5个loss反向传播，更新参数会互相干扰吗？

### ISSUE THREAD

**Issue by Davidleeeeee** [CoinCheung/BiSeNet#207]
如图，红色部分的参数，是否同时会被两个不同方向的loss相互影响？我看论文说会加速，但是感觉loss1也会将误差传递过来，岂不是相互干扰了？
![QQ图片20211128221558](https://user-images.githubusercontent.com/10355435/143771699-ecdd2380-4385-4317-a424-3e04bce5ebe1.png)

**Comment by CoinCheung** [comment]
For what I know, auxiliary loss is first proposed in [googlenet](https://arxiv.org/pdf/1409.4842v1.pdf), and is also used in [pspnet](https://arxiv.org/abs/1612.01105). It is not a new trick, and people tend to believe it can work, though I did not see the strict matchematical proof of this.

From the perspective of backpropagation, the gradient of different branch will be summed up at the branch split point. Maybe the noises from each branch can be canceled, reducing the variance of the gradient. This would make direction of gradient more accurate, thus training would be accelerated. I have no proof of this, it is only some intuition.

**Comment by Davidleeeeee** [comment]
谢谢啦老哥！
