### ISSUE TITLE
about 'cmake ..'

### ISSUE THREAD

**Issue by xihongZ** [CoinCheung/BiSeNet#208]
![K6Y`%8P J(%GU$LF8 GXHV3](https://user-images.githubusercontent.com/68284029/144747001-643f9c24-c541-45dc-b262-75c6843f1ec5.png)
Why do I have such an error here?

**Comment by CoinCheung** [comment]
What is the problem?

**Comment by xihongZ** [comment]
> What is the problem?
The problems are 'Looking for pthread_create -not found' and 'Looking for pthread_create in pthreads -not found'.
And I performed the ‘make’ operation and got the following result .
![5M8YLVBI5J{)I$~9(R@6} X](https://user-images.githubusercontent.com/68284029/144771628-8ad50077-a01a-4731-bd45-8940eb6ad811.png)

**Comment by CoinCheung** [comment]
Have you installed tensorrt 7.2.3 correctly? Are you using the cmake version I am using ?

**Comment by xihongZ** [comment]
> Have you installed tensorrt 7.2.3 correctly? Are you using the cmake version I am using ?

Can I use 1080ti to test the model speed ? I installed tensorrt 6.5.1.

**Comment by CoinCheung** [comment]
You can use 1080ti as long as it supports the environment I use(tensorrt 7.2.3 and cuda 10.2).

**Comment by CoinCheung** [comment]
I am closing this, since you might have solved your problem. Feel free to leave a message if you want more discussions.
