### ISSUE TITLE
Fragile segmentation results

### ISSUE THREAD

**Issue by kongyanye** [CoinCheung/BiSeNet#209]
I’m using the bisenet v2 model pretrained on cityscape dataset, and run inference via tools/demo.py script to segment a sample image. The weird thing I found is, if I put a cv2.resize directly after cv2.imread to reshape a given image to specific shape (e.g., 512\*512), then the segmentation results of a large photo (with higher resolution, e.g., 3840\*1920) and a small photo (with lower resolution, e.g., 1920\*960) will be different to a large extent. Clear I can see the segmentation results of large photo is better than small photo although the input to the model is almost the same (both of them are the resized version).

The two photos are visually almost the same. Only difference between them is the small value change during the cv2.resize operation. Is the model so sensitive to resize operation? Or the parameters like std and mean normalization and pretrained models are too over fitting?

**Comment by CoinCheung** [comment]
Hi,

Input size matters, and has impact on model performance. That is why there is crop evaluation method. There is a paper that discusses the impact of training and inference input size, you can refer to this: https://arxiv.org/abs/1906.06423
