### ISSUE TITLE
Infer with one single image

### ISSUE THREAD

**Issue by xihongZ** [CoinCheung/BiSeNet#211]
Why is the color of the image I run demo.py inconsistent with the color of each category in the official cityscapes data set?
![VBOYQA36QDBHI(3@SIAJH 0](https://user-images.githubusercontent.com/68284029/147518372-b6320d51-0439-4ccc-a21e-0d38f5512daf.png)

**Comment by CoinCheung** [comment]
Because color is generated randomly, and is not designed to be align with specific dataset. See this line: https://github.com/CoinCheung/BiSeNet/blob/f9231b7c971413e6ebdfcd961fbea53417b18851/tools/demo.py#L28

**Comment by xihongZ** [comment]
> 

How can I generate images according to the colors of the categories of the cityscapes data set?

**Comment by CoinCheung** [comment]
Cityscapes palette is here:
https://github.com/CoinCheung/BiSeNet/blob/f9231b7c971413e6ebdfcd961fbea53417b18851/lib/cityscapes_cv2.py#L19
You can parse this as json object, and map each trainId to its color.
