### ISSUE TITLE
a question about openvino

### ISSUE THREAD

**Issue by shiyanan96** [CoinCheung/BiSeNet#212]
the fig.1 is the part code in the openvino/main.cpp,  if there is a mistake of dims? 
when int oH = outsize[1], int oW = outsize[2], the inference output is the size of [1, width].
In my opinion, int oH = outsize[2], int oW = outsize[3];
when modify in this way, although the size of  inference output  is right, but the values of the output is wrong, as the fig2 shows.
By the way, why the output dim of the onnx model is [1,ArgMaxpreds_dim_1,height], where is the dim of width?
Thank you!
![企业微信截图_1640662866279](https://user-images.githubusercontent.com/46163165/147525653-e42d9223-4279-4951-9f60-c07a425f6d5b.png)

![企业微信截图_16406628487043](https://user-images.githubusercontent.com/46163165/147525662-50559bf3-e528-4485-9d86-79131c746d92.png)

**Comment by CoinCheung** [comment]
Does the original code not work? Or it doesn't work after your modification?

**Comment by CoinCheung** [comment]
Did you use onnx-simplifier to simplify your onnx model?

**Comment by CoinCheung** [comment]
I followed the steps in the readme, and the output result has correct shape. What modifications did you make to the code?

**Comment by sky999syn666** [comment]
> Does the original code not work? Or it doesn't work after your modification?

The original code doesn't work, which outputs a result with the size of width*1; after my modification, the size of output is the same as the input, but the segment result is more than the numubers of segmentation classes, for example, the 13-class segmentation task should output the results in the range  of [0,12], but it will outputs 14 or 16. It seems like the problem is related to the InferenceEngine::Precision.

**Comment by sky999syn666** [comment]
> I followed the steps in the readme, and the output result has correct shape. What modifications did you make to the code?

when you run the "python tools/export_onnx.py --config configs/bisenetv2_city.py --weight-path /path/to/your/model.pth --outpath ./model_v2.onnx", did it show the error?

**Comment by CoinCheung** [comment]
I did not saw the error, did you use the pytorch version as in readme? the deployment with another framework is very tricky. You need to be very careful to find out a combination that works.

**Comment by sky999syn666** [comment]
> I did not saw the error, did you use the pytorch version as in readme? the deployment with another framework is very tricky. You need to be very careful to find out a combination that works.

Sorry, I've mispoken. Running the "python tools/export_onnx.py" doesn't have the error, but when running the  "/opt/intel/openvino/deployment_tools/model_optimizer/mo.py " to transfer onnx to openvino's xml and bin, it would show error as follewed.
![企业微信截图_1640673577597](https://user-images.githubusercontent.com/46163165/147536539-0153ab69-29bf-4685-aeff-41ff7b2c1c70.png)
So, I have to modify the opset_version=11 to opset_version=10 in the tools/export_onnx.py.

**Comment by CoinCheung** [comment]
What is your openvino-version? did you run ` source /opt/intel/openvino_2021.4.689/bin/setupvars.sh` to setup environment?

**Comment by sky999syn666** [comment]
> What is your openvino-version? did you run ` source /opt/intel/openvino_2021.4.689/bin/setupvars.sh` to setup environment?
My openvino-version is 2020.4.287 because of ubuntu version is 16.04. I have setup environment

**Comment by CoinCheung** [comment]
I recommand you to use openvino docker image, older version may not support onnx in the same way as new versions. Besides, it will also save your time to install and configure from very beginning.
You will not have ubuntu version problem if you use docker.

**Comment by sky999syn666** [comment]
> I recommand you to use openvino docker image, older version may not support onnx in the same way as new versions. Besides, it will also save your time to install and configure from very beginning. You will not have ubuntu version problem if you use docker.

Okay, thank you, I will have a try. But, I still don't understand why "oH = outsize[1], int oW = outsize[2]," in fig.1, shoudn't outsize.shape be [N, C=1, H, W] ?

**Comment by CoinCheung** [comment]
After using `torch.argmax` without assigning `keepdims=True`, the output dimension would reduce from nchw to nhw. So it is "oH = outsize[1], int oW = outsize[2],".

**Comment by sky999syn666** [comment]
> I followed the steps in the readme, and the output result has correct shape. What modifications did you make to the code?



> After using `torch.argmax` without assigning `keepdims=True`, the output dimension would reduce from nchw to nhw. So it is "oH = outsize[1], int oW = outsize[2],".

Okay, I got it. Thank you very much!

**Comment by sky999syn666** [comment]
> I recommand you to use openvino docker image, older version may not support onnx in the same way as new versions. Besides, it will also save your time to install and configure from very beginning. You will not have ubuntu version problem if you use docker.

I used openvino docker image, and successfully converted onnx to xml, but I met another problem, as followed, the netwotk architecture is the same as your git.
![企业微信截图_16406821346564](https://user-images.githubusercontent.com/46163165/147549333-396ddebb-d9de-402a-b315-51327c87545a.png)

According the error prompt, I check the xml, as follows, it seems no problem, could you give some suggestion?
![企业微信截图_16406821755727](https://user-images.githubusercontent.com/46163165/147549509-14784976-3a02-4930-9c9b-fa12c45d7e25.png)

**Comment by CoinCheung** [comment]
What is your pytorch and openvino version? Did you use same code as I use？

**Comment by sky999syn666** [comment]
pytorch version is 1.9.0， openvino version is 2021.4.752, the code is same.

**Comment by sky999syn666** [comment]
> What is your pytorch and openvino version? Did you use same code as I use？

pytorch version is 1.9.0, openvino version is 2021.4.752, the code is same.

**Comment by CoinCheung** [comment]
Please use same versions as I use. I have not tried your combination, so I do not know whether that would work.
Also if you have modified expor_onnx.py or model structures, please resume them.
Or you can ask for openvino official support if they have discussion websites.
