### ISSUE TITLE
How to do int8 quantization, how is the effect, thank you

### ISSUE THREAD

**Issue by weizh588** [CoinCheung/BiSeNet#213]
How to do int8 quantization, how is the effect, thank you

**Comment by CoinCheung** [comment]
Hi,

I tried int8 very long ago with tensorrt 7.0.0 or 7.2.3. This is post training quantization and requires calibration of the model weights. I cannot remember too clearly, but with a Tesla T4 gpu, the inference fps is not too bigger than fp16 inference (about 1-2 more fps). Additionally, the segmentation output image is much worse than that of fp16, and I guess the miou must have dropped a lot. I did not spend too much time on this, but I have the impression that int8 is not so economic as fp16 in this case.
