### ISSUE TITLE
Python inference for trt model

### ISSUE THREAD

**Issue by namKolorfuL** [CoinCheung/BiSeNet#215]
Hi, I've converted the model to onnx and then trt format but I have no idea on how to load the trt model to my real-time video inference code in python. I've checked your cpp inference code and tried to convert them to python but failed. Any idea how it should be done? Thanks for sharing the implementation anyways!

**Comment by CoinCheung** [comment]
I will add a script when I have enough time to work on it. You can also refer to the official tutorial and examples. Link is here: https://github.com/NVIDIA/TensorRT

**Comment by zhuya1996** [comment]
> 
Can you do it now？？

**Comment by namKolorfuL** [comment]
> > 
> 
> Can you do it now？？

welp, I followed this guide and converted to the model to TensorRT, they provided scripts to convert and infer FCN model as well. Take a look. https://learnopencv.com/building-industrial-embedded-deep-learning-inference-pipelines-with-tensorrt/

**Comment by CoinCheung** [comment]
Close this since script is added.
