### ISSUE TITLE
关于argmax的问题请教一下

### ISSUE THREAD

**Issue by Wenshuo-Xiong** [CoinCheung/BiSeNet#216]
您好，我看您在v2的实现里最后有一步argmax，想跟您请教一下这个操作支持转到openvino里吗？
我之前试过一个其他的网络，在最后加了一个torch.argmax(pred, dim=1, keep_dims=true)，转到onnx后还是正常的，从onnx转到openvino以后发现openvino的输出是torch.max()的值。（比如其中一维是[2.1, 1.1, 3.3, 7.4, 5.3]，本来argmax应该输出4，但是openvino给出的是7.4）
想问一下从onnx转到openvino的时候需要额外加什么参数才能正确的支持argmax操作吗？
（从onnx转openvino的时候做过onnxsim，然后直接“python mo.py --input_model sge_sim.onnx --input_shape [1,3,448,448] --mean_values="[127.5, 127.5 , 127.5]" --scale_values="[127.5, 127.5, 127.5]" --data_type FP32”转换的）

**Comment by CoinCheung** [comment]
Maybe it is a problem of openvino version. I did not observe this problem when I added the openvino demo. You can use the same openvino version and environment, and see whether the problem still exists.
