### ISSUE TITLE
train on my own dataset,my image is jpg and label is png .

### ISSUE THREAD

**Issue by henbucuoshanghai** [CoinCheung/BiSeNet#218]
is that  ok?   my image is not png ,it is jpg

**Comment by CoinCheung** [comment]
Yes you can, images are actually read with opencv-python:
https://github.com/CoinCheung/BiSeNet/blob/f9231b7c971413e6ebdfcd961fbea53417b18851/lib/base_dataset.py#L53

**Comment by henbucuoshanghai** [comment]
kind and useful answer.&nbsp; my label is json now ,how to convert it to png ?could u give me some code,tks&nbsp; &nbsp;haha...

**Comment by CoinCheung** [comment]
What is the structure of your json file?

**Comment by henbucuoshanghai** [comment]
"version": "3.136.1",
  "flags": {},
  "shapes": [
    {
      "label": "person",
      "line_color": null,
      "fill_color": null,
      "points": [
        [
          709.2307692307692,
          111.30769230769229
        ],
        [
          698.974358974359,
          133.1025641025641
        ],
        [
          709.2307692307692,
          140.7948717948718
        ],
        [
          756.6666666666666,
          125.41025641025641
        ]
      ],
      "shape_type": "polygon",
      "flags": {}
    },

**Comment by henbucuoshanghai** [comment]
like this

**Comment by CoinCheung** [comment]
you can use `cv2.drawContours` to draw the label values to a background label image.

**Comment by henbucuoshanghai** [comment]
感谢。png可以np.zeros当背景？然后各类用单独的颜色填充就行？颜色随便？如（2,122,178）？&nbsp;只需要把img和对应的png放进路径，就可以？别的需要修改哪里？
感谢感谢
