### ISSUE TITLE
How to test on my own pictures with your pretrained model?

### ISSUE THREAD

**Issue by EchoAmor** [CoinCheung/BiSeNet#22]
Hello, thanks for your work and your humor! 

now  I need to get segemantation results on my own pictures(.bmp),but I need to use your pretrained model, can u give me some advice?(my coding ability is very poor now) Thanks very much!

**Comment by CoinCheung** [comment]
Hi, 

I hope you have figured out the solution. I refactored the codebase, and now you can infer with single picuture with the script of`demo.py`.

**Comment by EchoAmor** [comment]
@CoinCheung thanks a lot!
