### ISSUE TITLE
image size requirements for the models

### ISSUE THREAD

**Issue by MSEwantCS** [CoinCheung/BiSeNet#222]
I tried the example.jpg and it worked, however when I change my own picture, the model seems not work.

How do I tune the model to fit other input pictures? Thanks in advance.

**Comment by MSEwantCS** [comment]
Just checked issue 221, and its odd resolution issue

https://github.com/CoinCheung/BiSeNet/issues/221#issue-1164041080

**Comment by CoinCheung** [comment]
Hi,

resolution should be a muliply of 32, such as 384,512,640. It is assumed to be divided by 32.
