### ISSUE TITLE
BATCHSIZE

### ISSUE THREAD

**Issue by stu-xsy** [CoinCheung/BiSeNet#226]
where is the batchsize?

**Comment by CoinCheung** [comment]
It is here: 
https://github.com/CoinCheung/BiSeNet/blob/f9231b7c971413e6ebdfcd961fbea53417b18851/configs/bisenetv1_coco.py#L18
This is the number of training samples on **one** gpu. If you train with 2 gpus, the global batchsize will be 2 multiplies this variable.
