### ISSUE TITLE
cpp openvino inference demo  bug

### ISSUE THREAD

**Issue by czyczyczy** [CoinCheung/BiSeNet#228]
the cpp openvino inference demo(main.cpp):
    the function get_color_map()(129):
        uniform_int_distribution<uint8_t>, uint8_t is not allowed , how can i solve this problem?
thanks

**Comment by CoinCheung** [comment]
what is the configuration of you system? What is your compiler?

**Comment by CoinCheung** [comment]
Please use gcc/g++ if you can. Or you can try to replace `uint8_t` into `unsigned char`.

**Comment by czyczyczy** [comment]
In vs2019 ， uniform_int_dsitribute only allowed :  short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long
Unfortunately, my project is deployed on windows platform, so i can't compile this code used gcc/g++

**Comment by CoinCheung** [comment]
You can change it into `unsigned int`, and cast it to `uint8_t` using `static_cast<uint8_t>()`.

**Comment by czyczyczy** [comment]
I will try this method. Thanks for your answer.

**Comment by CoinCheung** [comment]
I am closing this since there seems to be no problem now.
