### ISSUE TITLE
No .log file when training.

### ISSUE THREAD

**Issue by zjwzcx** [CoinCheung/BiSeNet#229]
Hi! Thanks for your awesome work and detailed instructions in the README file and issues.

I try to train BiSeNet on my custom dataset. **However, I found that there is no .log file even though I haven't modified the code related to the logger.** 

 I just provide a workaround (may be ugly) for this problem:
Insert
        `for handler in logging.root.handlers[:]:
            logging.root.removeHandler(handler)`
before
        `logging.basicConfig(level=log_level, format=FORMAT, filename=logfile, force=True)` in the line 20 of ./lib/logger.py

And then the .log file will appear as expected.

Actually, I'm not familiar with logger mechanism. If you have some insight or better solutions for this problem, please discuss with me. Thank you!

**Comment by CoinCheung** [comment]
what is your python version and pytorch version? From some pytorch version on, there would be this problem，I solve this by using python3.8 and I do not have this problem any more.

**Comment by zjwzcx** [comment]
> what is your python version and pytorch version? From some pytorch version on, there would be this problem，I solve this by using python3.8 and I do not have this problem any more.

Thanks for your reply! I use python 3.6.15 and torch 1.8.1+cu102.

**Comment by CoinCheung** [comment]
Then if you do not want to get your hands dirty from modifying the code, you can update to python3.8 and try again. Your solution of removing handlers is inspiring, I will try this and see if I can add this line along with other modifications in the future.
 Thanks for telling me this!!!

**Comment by zjwzcx** [comment]
> Then if you do not want to get your hands dirty from modifying the code, you can update to python3.8 and try again. Your solution of removing handlers is inspiring, I will try this and see if I can add this line along with other modifications in the future. Thanks for telling me this!!!

Looking forward to your better solution. I'll close this question right away.
