### ISSUE TITLE
About the inference time

### ISSUE THREAD

**Issue by mengzhibin** [CoinCheung/BiSeNet#23]
I have tested your model params of the diss version, it's speed is very slow which could to 50ms in 1024x2048 size. your result is very good, but some still not clear.

**Comment by Aktcob** [comment]
the inference time is about 20ms for 1024*1024. So, for a bigger size, I think 50ms is not a bad number.

**Comment by mengzhibin** [comment]
@Aktcob when replace sync bn in this project with apex bn, the inference time is about 10ms with 1024x2048. but multi evaluate result 74 which is worth.

**Comment by wk524629918** [comment]
Could you  provide me a code of inference time? Thank you
