### ISSUE TITLE
ValueError: Error initializing torch.distributed using tcp:// rendezvous: rank parameter missing

### ISSUE THREAD

**Issue by qinghuayu1** [CoinCheung/BiSeNet#233]
Traceback (most recent call last):
  File "/root/AI/tools/train.py", line 227, in <module>
    main()
  File "/root/AI/tools/train.py", line 219, in main
    dist.init_process_group(backend='nccl', init_method='tcp://127.0.0.1:{}'.format(args.port),
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 130, in _tcp_rendezvous_handler
    raise _error("rank parameter missing")
ValueError: Error initializing torch.distributed using tcp:// rendezvous: rank parameter missing

please,help me ,please. I can not solve it . thanks

**Comment by CoinCheung** [comment]
Would you describle how did you run the script?

**Comment by qinghuayu1** [comment]
> Would you describle how did you run the script?

That problem is because I'm running code under Windows. But I run the code with your instructions under linux and get a new error. Sorry, I can't fix it
![f99fb2017c1ead5e5742001a3785463](https://user-images.githubusercontent.com/101563970/169548073-b034b40c-196f-4c10-9067-6527451edede.jpg)

**Comment by CoinCheung** [comment]
https://github.com/CoinCheung/BiSeNet/blob/master/datasets/cityscapes/train.txt
Please prepare your dataset like this.

**Comment by qinghuayu1** [comment]
> https://github.com/CoinCheung/BiSeNet/blob/master/datasets/cityscapes/train.txt Please prepare your dataset like this.

I did as you instructed，just like this
![image](https://user-images.githubusercontent.com/101563970/169553206-b256ab60-6da9-4a7d-9f33-edf7c071faec.png)

**Comment by CoinCheung** [comment]
You need to use comma rather than spaces.
