### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Thatboy7** [CoinCheung/BiSeNet#234]

**Comment by CoinCheung** [comment]
What is the problem?

**Comment by Thatboy7** [comment]
> What is the problem?

hello,if i want to train my own dataset ,the label img is 3channel or 1channel,i meet the same problem as others 
![image](https://user-images.githubusercontent.com/28282980/174718424-b8162aeb-a5f8-4d6f-8036-3ab5874098cc.png)
but i don't know why. there is no reply for this question. could you help me ?

**Comment by Thatboy7** [comment]
> What is the problem?

i have solved my problem . i made a mistake

**Comment by CoinCheung** [comment]
I am closing this, since you have solved your problem.
