### ISSUE TITLE
lack F.interpolate in bisenetv1.py 

### ISSUE THREAD

**Issue by qixi666666** [CoinCheung/BiSeNet#235]
in bisenetv1.py  class ContextPath lack F.interpolate about avg in line 141, so the result is wrong

**Comment by CoinCheung** [comment]
What result is wrong? Would you be more specific?

**Comment by qixi666666** [comment]
avg should be avg_up = F.interpolate(avg, (H32, W32), mode='nearest'), then feat32_sum = feat32_arm + avg_up, if lack F.interpolate(avg, (H32, W32), mode='nearest'),  avg only 1*1, feat32_sum = feat32_arm + avg will not report wrong, but the result is not true.

**Comment by CoinCheung** [comment]
Have you compared the values?

**Comment by qixi666666** [comment]
你可以直接看看原始的old / model.py  ContextPath 中这部分的定义，确实少一块，上升的过程

**Comment by CoinCheung** [comment]
This should bring no difference, since input shape is (1,1).

**Comment by qixi666666** [comment]
not 1*1  , should be H32, W32 , both  feat32_arm and  avg should be H32, W32, then +

**Comment by CoinCheung** [comment]
The feature will be broadcast to H32 and W32 before adding.
