### ISSUE TITLE
Have you ever used TRT on Windows

### ISSUE THREAD

**Issue by zhuya1996** [CoinCheung/BiSeNet#236]
Have you ever used TRT on Windows

**Comment by zhuya1996** [comment]
hello 您好

**Comment by CoinCheung** [comment]
Sadly, I have no experience with windows. I even do not know how to configure anaconda for pycharm. Maybe you can refer to official website for tutorials.

**Comment by zhuya1996** [comment]
您好，能否写一个python 调用onnx 的代码呀&nbsp; 我用bisenet生成了onnx 但是不知道如何推理




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月16日(星期四) 上午8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CoinCheung/BiSeNet] Have you ever used TRT on Windows (Issue #236)





 
Sadly, I have no experience with windows. I even do not know how to configure anaconda for pycharm. Maybe you can refer to official website for tutorials.
