### ISSUE TITLE
loss setting problem

### ISSUE THREAD

**Issue by coallar** [CoinCheung/BiSeNet#238]
Hi, bro, thanks for your great job.

i have a problem about loss setting.

in original source code, loss is : logit_loss + sum(aux_loss).  e.g. num_heads_brach=2 in BiSeNetv1, so length of aux_loss is 2.  
my problem is : modifying loss to logit_loss + mea(aux_loss) may be more suitable? is it right?

**Comment by CoinCheung** [comment]
Hi，

I did not test that, I simply use this setting and find the result is acceptable.

**Comment by coallar** [comment]
> Hi，
> 
> I did not test that, I simply use this setting and find the result is acceptable.

thanks~
