### ISSUE TITLE
pth to onnx  我自己训练生成的pth模型转onnx模型的问题

### ISSUE THREAD

**Issue by zhuya1996** [CoinCheung/BiSeNet#239]
您好    python tools/export_onnx.py --config configs/bisenetv2_city.py --weight-path /path/to/your/model.pth --outpath ./model.onnx   请问我自己训练出的模型，用这句话转onnx ，还需要在哪设置类别吗

**Comment by zhuya1996** [comment]
您好，能些一个 onnx 推理图片的代码吗  windows 下 python使用的

**Comment by zhuya1996** [comment]
您好，能写一个 onnx 推理图片的代码吗 windows 下 python使用的

**Comment by CoinCheung** [comment]
> 您好 python tools/export_onnx.py --config configs/bisenetv2_city.py --weight-path /path/to/your/model.pth --outpath ./model.onnx 请问我自己训练出的模型，用这句话转onnx ，还需要在哪设置类别吗

You can assign the category number in the config file, you can use the exactly same config file as you used to train your model.

**Comment by CoinCheung** [comment]
> 您好，能写一个 onnx 推理图片的代码吗 windows 下 python使用的

I am not familiar with windows develop environment, and, to be honest, I do not have such plan of try window. I will add a tensorrt python script in the future when I have time.

**Comment by zhuya1996** [comment]
Looking forward to your tensorrt Python reasoning   thansk

**Comment by CoinCheung** [comment]
close since this is done.
