### ISSUE TITLE
Dimension error when making an inference on jpg images

### ISSUE THREAD

**Issue by frandoLin** [CoinCheung/BiSeNet#241]
Hi, I tried to use the demo.py with the weight pre-trained on cityscape to make an inference on my test image, however, it throws an error as below:

![image](https://user-images.githubusercontent.com/41569547/175900656-14dae154-a21a-44e6-9182-b41956a7e794.png)

Here is my test image which is jpg format:
![test_img](https://user-images.githubusercontent.com/41569547/175900042-9439cb6f-0f4e-4965-9e85-478e61d5b2ad.jpg)

So, I was wondering if BiSeNet only take the images with png format as input.  Then, I tried to use pillow to convert jpg to png but I got the same error as mentioned above. Also, I confused with that the images under the Leftimg8bit actually are not 8 bit but 24 bit. I am thinking of if it can only take the images by cityscape if I choose the weight pre-trained on that.

**Comment by CoinCheung** [comment]
Close this since the question is answered.
