### ISSUE TITLE
Any suggestions for optimization？

### ISSUE THREAD

**Issue by laocan** [CoinCheung/BiSeNet#252]
any suggestions for optimization?
1. Speed up the reasoning
2. improve the accuracy of segmentation details
thx!

**Comment by CoinCheung** [comment]
This is what the researchers are doing everyday, isn't it? Maybe you can read paper of your interest and try the proposed method.

**Comment by laocan** [comment]
For part 2:
I've added Diceloss for 2-class seg(for unbalanced labels) and multiplied the different losses(pre, aux, dice) with weights([1,0.5,1]) but get worse result. ===>  now,  I fix the weight equally and train again.
BTW the training process is so slow...

**Comment by CoinCheung** [comment]
Good job!!! I am closing this.
