### ISSUE TITLE
How to save the predicted image output? thx

### ISSUE THREAD

**Issue by emilyemliyM** [CoinCheung/BiSeNet#255]

**Comment by CoinCheung** [comment]
What do you mean? Which script are your referring to?

**Comment by emilyemliyM** [comment]
> What do you mean? Which script are your referring to?

Hi,
I want to use the pretrain weight to test the dataset,and save the prediction .
Thanks.

**Comment by CoinCheung** [comment]
This is not supported now, if you mean to compute the metric of miou on test set and save the predicted images at the same time. You can do this separately, by running `evaluate.py` script to compute mious, and running `tools/demo.py` to infer single image and save the result.
