### ISSUE TITLE
use for kitti, how to train or finetune,thanks!

### ISSUE THREAD

**Issue by emilyemliyM** [CoinCheung/BiSeNet#257]
Dear author,

If I want to use the model to do the training in the Kitti dataset.
So we have the different category number, for the sityscapes ,it is 20 .
For Kitti, for examplt, the category number is 6.
So how to o the training work? add a conv2d(20, 6)? or anything else.

**Comment by emilyemliyM** [comment]
I use the command below:L
torchrun --nproc_per_node=2 train_amp.py --finetune-from pretrain_weight/model_final_v2_city.pth

But it shows that missing a lot of key : below:
![image](https://user-images.githubusercontent.com/88700988/185650743-36fefb3d-9468-4d0d-8b6b-b41cfc56ecda.png)


I just set the category num to 5.

**Comment by CoinCheung** [comment]
Maybe you are using unmatched config file and finetune weight file.

**Comment by CoinCheung** [comment]
Close this, since this is not activate for long time, and likely the problem is solved.
