### ISSUE TITLE
Faild to use segment.py for tensorrt inference 

### ISSUE THREAD

**Issue by github2016-yuan** [CoinCheung/BiSeNet#258]
I have followed your order [segment.py](https://github.com/CoinCheung/BiSeNet/tree/master/tensorrt#2-inference-with-tensorrt)
I have converted onnx to trt with it . But when I use order like this:
`python segment.py run --mdpth ./model.trt --impth ../example.png --outpth ./res.png`

I get error below:
`Traceback (most recent call last):
  File "segment.py", line 157, in <module>
    main()
  File "segment.py", line 149, in main
    out = palette[pred]
IndexError: index 1020 is out of bounds for axis 0 with size 256`

It seems that the error is about size mismatch.
Hope to get your solution thanks.

**Comment by github2016-yuan** [comment]
My env is win11.

**Comment by github2016-yuan** [comment]
OK, I solve it. I use  **model_final_v1_city_new.pth** as the original model.
line 30 in tensorrt/segment.py
change `palette = np.random.randint(0, 256, (256, 3)).astype(np.uint8)`
**To** `palette = np.random.randint(0, 1024, (1024, 3)).astype(np.uint8)`

**Comment by github2016-yuan** [comment]
> OK, I solve it. I use **model_final_v1_city_new.pth** as the original model. line 30 in tensorrt/segment.py change `palette = np.random.randint(0, 256, (256, 3)).astype(np.uint8)` **To** `palette = np.random.randint(0, 1024, (1024, 3)).astype(np.uint8)`

Maybe this is NOT a right solution ...

**Comment by CoinCheung** [comment]
Would you patch briefly how to reproduce this problem? Any specific steps?

**Comment by github2016-yuan** [comment]
> patch

Quick response! I will give the steps right now.

**Comment by github2016-yuan** [comment]
I used your repo before in ubuntu, retraining my own model and successfully deployed in jetson tx2 and nx . Good job.
Now I want to try it in wins and I followed steps below.
(1) I pull down the repo and download the model **model_final_v1_city_new.pth**
(2) I set up the env: torch 1.10.2  tensorrt 8.2.0.6 pycuda 2022.1 etc
(3) using `python tools/export_onnx.py --config configs/bisenetv1_city.py --weight-path /path/to/your/model.pth --outpath ./model.onnx ` to get onnx file and it works.
(4) using `python segment.py compile --onnx /path/to/model.onnx --savepth ./model.trt --quant fp16` to get model.trt
(5)using `python segment.py run --mdpth ./model.trt --impth ../example.png --outpth ./res.png` for inference and **Here** I get error like above .
This is all what I have done.
By the way I also tried tensorrt C++ using vs2017 and CMakeLists.txt. I built it but get some erroe related to tensorrt API  while running so I use segment.py.

**Comment by CoinCheung** [comment]
Did you export to onnx with the command in the readme?
```
$ cd BiSeNet/
$ python tools/export_onnx.py --config configs/bisenetv2_city.py --weight-path /path/to/your/model.pth --outpath ./model.onnx --aux-mode eval
```

**Comment by github2016-yuan** [comment]
> bisenetv2_city

Yeah I do some change. 
 `python tools/export_onnx.py --config configsbisenetv1_city.py --weight-path /path/to/your/model.pth --outpath ./model.onnx  `

Here v1_model should be with **bisenetv1_city.py** ? right?
I will stick to your cmd without any change and have a try again at once.

**Comment by CoinCheung** [comment]
Did you even add `--aux-mode eval` to export ?

**Comment by github2016-yuan** [comment]
OK, it works with param  `--aux-mode eval ` despite  there is a little difference between pth model and trt model inference. Maybe it is nornal. I will close it .

**Comment by CoinCheung** [comment]
Did you even change the mean/var of the pre-process?

**Comment by github2016-yuan** [comment]
No I just want to have a try in win11 about your repo pth->onnx->trt->inference， so I use model provided by you.

**Comment by CoinCheung** [comment]
Maybe aligning the mean/var values would narrow the performance gap between pytorch `pth` model and tensorrt model.
