### ISSUE TITLE
Training errow

### ISSUE THREAD

**Issue by Jasonshao0123** [CoinCheung/BiSeNet#259]
![2a7bd65854f0a80d585a76f7e410bc2](https://user-images.githubusercontent.com/46207106/185839605-e49c1b89-99ae-4490-a5c6-5f625ff76b22.png)
How to solve this problem？

**Comment by CoinCheung** [comment]
Please follow the step of readme to launch training, and please use same version of pytorch.

**Comment by Jasonshao0123** [comment]
Thanks for your reply，
I didn't change the version of pytorch.
I add this code into train_amp.py and the problem was solved.
parse.add_argument('--local_rank', defautle=-1, type=int,
                                   help='node rank for distributed training')

**Comment by CoinCheung** [comment]
I am closing this, since the problem is solved.
