### ISSUE TITLE
make 

### ISSUE THREAD

**Issue by liangjunhao1998** [CoinCheung/BiSeNet#263]
![2022-09-08 10-33-57 的屏幕截图](https://user-images.githubusercontent.com/85820796/189020781-b33f55d9-1af9-4463-9acc-1a9dd85b9b6f.png)
hello,may i ask hoe to solve this problem？

**Comment by CoinCheung** [comment]
Sorry, that is my bad, I had updated a fix. You can update the local code and have try:)

**Comment by liangjunhao1998** [comment]
> Sorry, that is my bad, I had updated a fix. You can update the local code and have try:)
Thanks, the problem is solved

**Comment by fancyhhhhhh** [comment]
> Sorry, that is my bad, I had updated a fix. You can update the local code and have try:)

Hi,I have the same problem,but I don't understand how to solve it,how to update the local code....

Thanks for your answering.

**Comment by CoinCheung** [comment]
Likely it is not same problem. I modified the `CMakeLists.txt` after that. @fancyhhhhhh
