### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by liangjunhao1998** [CoinCheung/BiSeNet#265]
![2022-09-08 15-05-22 的屏幕截图](https://user-images.githubusercontent.com/85820796/189057614-8e0a8b42-993c-4b38-97ba-4bcdc1be89bd.png)
Hello, I would like to ask how to solve this problem, about Tensorrt versions ?

**Comment by CoinCheung** [comment]
What is the configuration of your platform? Did you modify the code? Please align the cuda/cudnn/tensorrt/pytorch/cmake version as mine listed in readme.

**Comment by liangjunhao1998** [comment]
> What is the configuration of your platform? Did you modify the code? Please align the cuda/cudnn/tensorrt/pytorch/cmake version as mine listed in readme.

ubuntu 18.04
 GeForce RTX 3060  Driver Version 470.94
cuda 11.1 cudnn 8.0.5
tensorrt 8.2.5.1
cmake 3.16.2
opencv 3.4.15
I  did not modify the code

**Comment by CoinCheung** [comment]
Did you export onnx model with the same command as in README?

**Comment by liangjunhao1998** [comment]
> Did you export onnx model with the same command as in README?

yes，I have ported onnx mode,Now I'm upgrading cuda, try again

**Comment by CoinCheung** [comment]
I mean, did you add `--aux-mode eval` when you export onnx model?

**Comment by liangjunhao1998** [comment]
> I mean, did you add `--aux-mode eval` when you export onnx model?

yes,I add

**Comment by liangjunhao1998** [comment]
> I mean, did you add `--aux-mode eval` when you export onnx model?
Also, I would like to ask do I need to install onnx?

**Comment by CoinCheung** [comment]
I tried again on my platform, and it works as expected. Maybe you should align your platform configuration as mine, especially the cuda/cudnn version.

**Comment by liangjunhao1998** [comment]
> I tried again on my platform, and it works as expected. Maybe you should align your platform configuration as mine, especially the cuda/cudnn version.

What are the python and pytorch versions you are using？

**Comment by CoinCheung** [comment]
I use pytorch3.8 from miniconda and pytorch1.11.0(cuda11).

**Comment by liangjunhao1998** [comment]
> I use pytorch3.8 from miniconda and pytorch1.11.0(cuda11).
![2022-09-08 22-16-45 的屏幕截图](https://user-images.githubusercontent.com/85820796/189148855-a204f351-6697-4502-835d-aa2870f6ec79.png)

Thanks, I can convert model_final_v2_city.pth to trt by upgrading cuda from 11.1 to 11.3 and cudnn from 8.0.8 to 8.2.1, which is normal for FPS to 118.283 in an environment where the CPU is R7-5800H and the GPU is 3060?
