### ISSUE TITLE
Infer with one single image question

### ISSUE THREAD

**Issue by liangjunhao1998** [CoinCheung/BiSeNet#267]
I use the model_final_v2_ade20k.pth that you provided, using the command:

python tools/export_onnx.py --config configs/bisenetv2_city.py --weight-path /home/datou/BiSeNet/BiSeNet-master/model/model_final_v2_city.pth  --outpath ./model_v2_city.onnx --aux-mode eval

Convert pth to onnx and use the command：
./segment complie ../../model_v2_city.onnx ../../saved_v2city.trt --f16

Finally get trt, use the following command to test：
./segment run  ../../saved_v2city.trt ../../example.png ../../output_v2city.jpg
![output_v2city](https://user-images.githubusercontent.com/85820796/189263095-c1ccf450-2f9d-4c18-a958-82d8c295bc0f.jpg)

But the output result is not correct, the result is as follows, I want to ask what is the reason?

**Comment by CoinCheung** [comment]
Again, I observe no such problem on my own platform. What model are you using? Is the pytorch demo.py works correctly?

**Comment by liangjunhao1998** [comment]
> Again, I observe no such problem on my own platform. What model are you using? Is the pytorch demo.py works correctly?

yes,I am using the model model_final_v2_city.pth provided by your github, which can run normally in model.py
![图片](https://user-images.githubusercontent.com/85820796/189278884-000a7a4b-6ff3-492b-8f5e-e44f5f533aeb.png)
when i commend 
./segment run  ../../saved_v2_city.trt ../../example.png ../../output_v2city.jpg
![图片](https://user-images.githubusercontent.com/85820796/189278974-e980681e-4f16-420b-b91f-f984b06369a4.png)

this warning :TensorRT was linked against cuBLAS/cuBLASLt 11.6.5 but loaded cuBLAS/cuBLASLt 11.4.2
Will it affect the result? do you have this problem

**Comment by CoinCheung** [comment]
I pulled a new repo and run step by step, but I still cannot reproduce this problem.
![pic](https://user-images.githubusercontent.com/22693362/189290536-367f344e-d635-4f1d-98cd-78322aecd928.jpg)

**Comment by liangjunhao1998** [comment]
> I pulled a new repo and run step by step, but I still cannot reproduce this problem. ![pic](https://user-images.githubusercontent.com/22693362/189290536-367f344e-d635-4f1d-98cd-78322aecd928.
jpg)
I just dropped the tensorrt version from 8.2.5.1 to 8.0.1.6, and the result of the segmentation can be displayed normally.
![output_v2_city](https://user-images.githubusercontent.com/85820796/189297128-f9a54e4c-5938-41a1-a93f-00f5171ea26f.jpg)

I tested it, the gpu is 3060, the fps is 25.6845, is this normal?
