### ISSUE TITLE
Questions about FPS

### ISSUE THREAD

**Issue by liangjunhao1998** [CoinCheung/BiSeNet#269]
The authors report achieving an average IoU of 72.6% on the Cityscapes test set and 156 FPS on an NVIDIA GeForce GTX 1080Ti card.

But on my laptop NVIDIA GeForce GTX  3060, After converted into engine, the FPS was only 25. I would like to ask why the difference is so big

**Comment by CoinCheung** [comment]
Did you compared the input image sizes? Also, did you use fp16 mode, and does the authors of the paper uses fp16 mode?
