### ISSUE TITLE
About Loss and training time 

### ISSUE THREAD

**Issue by 499099371** [CoinCheung/BiSeNet#270]
Hello author, I trained your BiSeNetV2 code on 3090, and I showed that the Loss was particularly high, and the decline was particularly fast
    In addition, the training time needs two days. 
    Are these two problems normal?
![图片](https://user-images.githubusercontent.com/107231824/192306525-bf85f9ee-072d-48fd-a79b-b4ac0358dbda.png)
![图片](https://user-images.githubusercontent.com/107231824/192309380-6c535c52-1e3f-4a60-8254-af8952bce87e.png)

**Comment by CoinCheung** [comment]
There are 5 auxiliary losses for bisenetv2, so you should expect a higher loss.

As for training time, it depends on your input image size and number of your training iterations, and also associated with your dataset categories.
