### ISSUE TITLE
单卡训练

### ISSUE THREAD

**Issue by yangzhegithub** [CoinCheung/BiSeNet#273]
你好，可以支持单卡训练机制嘛？硬件资源有限

**Comment by Mantee0810** [comment]
> 你好，可以支持单卡训练机制嘛？硬件资源有限

你好，请问你调整好单卡训练的代码了吗

**Comment by CoinCheung** [comment]
Hi @yangzhegithub @Mantee0810 ,

Maybe you can also use distributed training with one gpu:
```
torchrun --nproc_per_node=1 tools/train_amp.py --config /path/to/config.py
```
Thus you do not need to modify your code.
