### ISSUE TITLE
A question about RuntimeError

### ISSUE THREAD

**Issue by Sangh0** [CoinCheung/BiSeNet#275]
Hello, thanks for your code implementations of BiSeNetV2

I have a question for you
I met the RuntimeError as following:

>   File "/MY_DL/ADAI_challenge/util/loss.py", line 17, in forward
    loss_hard = loss[loss > self.thresh]
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

The above code is in [lib]](https://github.com/CoinCheung/BiSeNet/tree/master/lib)/ohem_ce_loss.py
How do I solve this problem?

**Comment by CoinCheung** [comment]
Please check your dataset, are there dirty annotation images?
Also please use customer dataset rather than cityscapes/coco/ade20k, if you do not have label value mapping.

**Comment by Sangh0** [comment]
Thank you! I solved this error.
Have a good day.

**Comment by CoinCheung** [comment]
Good to know you have solved this problem!!! I am closing this since problem is solved.

**Comment by shilpaullas4** [comment]
Hi  @CoinCheung , 
@Sangh0 ,

I was trying to train my custom dataset on bisenet v2 and stuck with the same  RuntimeError

ERROR MESSAGE : 

**_loss_hard = loss[loss > self.thresh]                                                                              
RuntimeError: CUDA error: an illegal memory access was encountered                                                    
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                                                                
[W CUDAGuardImpl.h:113] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)       
terminate called after throwing an instance of 'c10::CUDAError'                                                       
  what():  CUDA error: an illegal memory access was encountered                                                       
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1._**  


Could you please help me to resolve this issue?
