### ISSUE TITLE
模型转换相关问题（ncnn）

### ISSUE THREAD

**Issue by wo712268** [CoinCheung/BiSeNet#279]
作者你好！我使用bisenet训练了一些自己的模型，类型主要是车道线（包括道路上的虚线），在训练完成后我将模型按照readme的说明转换并部署到了ncnn上。但结果并不理想，与直接使用demo.py里的推理结果相比，ncnn中的推理结果差了很多，尤其是车道线，很容易丢失和模糊。我猜测可能是以下几个原因：
1. 部署过程中模型丢失信息，但在训练自己模型之前我使用了你们开源的模型并进行了测试，你们的模型转换后推理结果差不多，因此我假设模型转换丢失的信息是有限的。

2. 图片大小问题，我训练时候用的原图大小为2160*3840，网络的crop_size为1024*1024，你们的demo.py是可以直接用原图大小进行推理的，而ncnn，包括tensorRT都会要求将原图先resize为1024*1024再进行推理。显然分辨率差了很多倍，但我不太懂Pytorch，我不清楚在Pytorch中net.eval()内部是怎样操作的，所以感到比较困惑。

3. 可以给一点建议吗？关于部署这一方面，我希望可以尽量避免造成推理结果上的损失。

希望看到了可以回复我呀，感谢！

**Comment by CoinCheung** [comment]
Hi, 

Maybe you  can run inference with crop_size of 1024x1024 as for training, and fuse the results together for a 2160x3840 result. Cropsize really matters here.

**Comment by CoinCheung** [comment]
I do not have crop inference implemented here, so if you want to try this, you need to write some code for it.

**Comment by CoinCheung** [comment]
I am closing this, since this is not active for long time.
