### ISSUE TITLE
ImportError: No module named 'inplace_abn'

### ISSUE THREAD

**Issue by wk524629918** [CoinCheung/BiSeNet#28]

**Comment by wk524629918** [comment]
please help me

**Comment by CoinCheung** [comment]
What is your environment and how did you setup training or eval ?

**Comment by TianMingChen** [comment]
Did you have solve this problem?
when I install inplace_abn,I get this problem.
 
nvcc fatal   : Unsupported gpu architecture 'compute_61'
error: command '/usr/bin/nvcc' failed with exit status 1

**Comment by CoinCheung** [comment]
Hi, 

I refactored the implementation, and we do not rely on `inplace abn` now. If you are still in need of this, you can update to pytorch1.6, and try the new code.
