### ISSUE TITLE
question when I try to deploy with tensorrt

### ISSUE THREAD

**Issue by fancyhhhhhh** [CoinCheung/BiSeNet#280]
Hi,old iron
I have got a weight after training on my own datasets,thanks for your answering before.
in the README.md of tensorrt,you said your platform "opencv built from source",I don't know how to built from source.
I had installed opencv in my conda environment,and the version of cuda,ubuntu,cmake and tensorrt is like yours.
When I type "cmake .." in the terminal ,there will be an error like this

CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

After referring some blogs ,I think I should add "set（OpenCV_DIR  /path/to/opencv/build）" to CMakeLists.txt
My question is opencv is in my conda environment ,should I replace the absolute path of opencv lib with the /path/to/opencv?

Really thank you!

**Comment by CoinCheung** [comment]
Hi,

You can install opencv from system source, for example, you can use `apt install libopencv-dev`. Or you can install opencv via building from source code. I have not tried to use opencv installed from conda. It may lack `opencv.md`, which is required by cmake.

**Comment by CoinCheung** [comment]
Hi,

If you still have problem with this, please let me know the steps how to reproduce the problem, and post a screenshot of the error message.

**Comment by fancyhhhhhh** [comment]
> Hi,
> 
> If you still have problem with this, please let me know the steps how to reproduce the problem, and post a screenshot of the error message.

Thanks for your replying,  I had solved this problem.Thank you

**Comment by CoinCheung** [comment]
Then I am closing this.
