### ISSUE TITLE
trt convert

### ISSUE THREAD

**Issue by XDxiaoqi** [CoinCheung/BiSeNet#285]
python  conver_to_trt.py
Warning: Encountered known unsupported method torch.Tensor.argmax
[TensorRT] ERROR: 4: [network.cpp::validate::2411] Error Code 4: Internal Error (Network must have at least one output)
c++:
ERROR: builtin_op_importers.cpp:3422 In function importResize:
[8] Assertion failed: scales.is_weights() && "Resize scales must be an initializer!"
parse model failed

very appreciate to find the problem.

**Comment by CoinCheung** [comment]
Did you export the onnx model in the same way as in the readme?

**Comment by XDxiaoqi** [comment]
cuda和tensorRt的版本问题,对齐后顺利运行的
感谢
