### ISSUE TITLE
为啥显示的精度不一样呢？

### ISSUE THREAD

**Issue by lilbetter-l** [CoinCheung/BiSeNet#287]
提供的代码是这种方式显示的精度结果，但是论文里面却不一样？论文里面分为了 val 和 test ，这两者怎么对应呢？？？？
none | ss | ssc | msf | mscf | fps(fp32/fp16/int8) | link
-- | -- | -- | -- | -- | -- | --
bisenetv1 | 75.44 | 76.94 | 77.45 | 78.86 | 25/78/141 | download
bisenetv2 | 74.95 | 75.58 | 76.53 | 77.08 | 26/67/95 | download

**Comment by CoinCheung** [comment]
There are results on val set. I did not evaluate the model on test set.

**Comment by lilbetter-l** [comment]
感谢回复！刚开始接触语义分割，还有一点不是很明白，请问 ss | ssc | msf | mscf 这四者都是val test 的精度，具体是那个对应论文里面的 val  test 的精度？这块困扰了很久！！！




> There are results on val set. I did not evaluate the model on test set.

**Comment by CoinCheung** [comment]
**ss** is single scale, most paper would use this, and if they say they use multi-scale inference, it would be **msf** or **msfc**.

**Comment by CoinCheung** [comment]
Closing this since this is not active for some time.
