### ISSUE TITLE
inference time 

### ISSUE THREAD

**Issue by robbie2021** [CoinCheung/BiSeNet#289]
Hi,thank you for your great work!
I use the pretrained model_final_v2_city.pth , demo.py with input size (512, 1024), the inference time is 1300ms ！！！ why ?

**Comment by CoinCheung** [comment]
Sorry for being so late. I was so occupied by other work during these months. If you still have this problem, would you tell me how I can reproduce your result? Which framework are you using, and what is your platform like?
