### ISSUE TITLE
No module named 'lib'

### ISSUE THREAD

**Issue by zercy-99** [CoinCheung/BiSeNet#292]
Why will an error be reported when running the code？

Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    import lib.data.transform_cv2 as T
ModuleNotFoundError: No module named 'lib'

**Comment by CoinCheung** [comment]
What is the steps to reproduce this problem? What did you do?

**Comment by zercy-99** [comment]
After completing the steps you gave, I just run"demo.py". Then I failed.

**Comment by CoinCheung** [comment]
Would you show me the screenshot what did you do?

**Comment by zercy-99** [comment]
The screenshot of the code I ran on the ECS is as follows:
![1677157412224](https://user-images.githubusercontent.com/126148056/220914181-3e797d92-3e4b-4cc2-b2fe-6ffe8bf913b5.jpg)

**Comment by zercy-99** [comment]
I downloaded the data package(cocostuff) and then unzipped it to the specified path as prompted. After running the "demo.py", an error was reported. The picture is the error

**Comment by CoinCheung** [comment]
I think the step in the readme use the command of `python tools/demo.py` rahther than `python demo.py`.

**Comment by zercy-99** [comment]
I have specified the path above, which means to run `python tools/demo.py`. Is it necessary to modify "_init_.py" in the folder lib

**Comment by zercy-99** [comment]
The ECS must enter the directory where the code is located before it can run.  It will make a mistake according to your suggestion.  Can I take all the files in tools to the outermost folder?
![Uploading 1677161798564.png…]()

**Comment by CoinCheung** [comment]
I moved `demo.py` to upper level directory of `BiSeNet` and run it, I did not meet this problem.

**Comment by CoinCheung** [comment]
Maybe you have figured out the solution, so let me close this.
