### ISSUE TITLE
May I ask why the larger the batch size, the slower the training time

### ISSUE THREAD

**Issue by ZzzTD** [CoinCheung/BiSeNet#299]
this is on 3090
## bisenetv2
cfg = dict(
    model_type='bisenetv2',
    n_cats=2,
    num_aux_heads=4,
    lr_start=5e-3,
    weight_decay=5e-4,
    warmup_iters=1000,
    max_iter=160000,
    dataset='CityScapes',
    im_root=r'E:\ZTD\BiSeNet-master\datasets\cityscapes',
    train_im_anns=r'E:\ZTD\BiSeNet-master\datasets\cityscapes\train.txt',
    val_im_anns=r"E:\ZTD\BiSeNet-master\datasets\cityscapes\val.txt",
    scales=[0.25, 2.],
    cropsize=[512, 1024],
    eval_crop=[1024, 1024],
    eval_scales=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
    ims_per_gpu=32,
    eval_ims_per_gpu=2,
    use_fp16=True,
    use_sync_bn=False,
    respth=r'E:\ZTD\BiSeNet-master\weights',
)

iter: 101/160000, lr: 0.003454, eta: 5 days, 10:10:56, time: 296.02, loss: 32.5080, loss_pre: 16.0787, loss_aux0: 0.7583, loss_aux1: 0.9673, loss_aux2: 3.3306, loss_aux3: 11.3731
iter: 201/160000, lr: 0.004348, eta: 5 days, 2:00:40, time: 256.46, loss: 3.8151, loss_pre: 1.3689, loss_aux0: 0.5362, loss_aux1: 0.5403, loss_aux2: 0.5947, loss_aux3: 0.7751
iter: 301/160000, lr: 0.005474, eta: 4 days, 23:39:08, time: 259.38, loss: 2.9660, loss_pre: 0.7845, loss_aux0: 0.5065, loss_aux1: 0.4969, loss_aux2: 0.5227, loss_aux3: 0.6553
iter: 401/160000, lr: 0.006892, eta: 4 days, 22:32:10, time: 260.31, loss: 2.7057, loss_pre: 0.6096, loss_aux0: 0.4993, loss_aux1: 0.4859, loss_aux2: 0.5083, loss_aux3: 0.6025
iter: 501/160000, lr: 0.008676, eta: 4 days, 21:48:10, time: 259.92, loss: 2.4787, loss_pre: 0.5242, loss_aux0: 0.4844, loss_aux1: 0.4651, loss_aux2: 0.4799, loss_aux3: 0.5251
iter: 601/160000, lr: 0.010923, eta: 4 days, 21:15:33, time: 259.51, loss: 2.4036, loss_pre: 0.4775, loss_aux0: 0.4786, loss_aux1: 0.4534, loss_aux2: 0.4608, loss_aux3: 0.5332
iter: 701/160000, lr: 0.013751, eta: 4 days, 20:48:47, time: 258.92, loss: 2.3568, loss_pre: 0.4634, loss_aux0: 0.4755, loss_aux1: 0.4490, loss_aux2: 0.4560, loss_aux3: 0.5129

But when i set the batchsize is 16 on 3070ti:
iter: 101/160000, lr: 0.003454, eta: 2 days, 23:55:32, time: 163.55, loss: 35.5408, loss_pre: 16.1520, loss_aux0: 0.7061, loss_aux1: 1.1959, loss_aux2: 3.1689, loss_aux3: 14.3178
iter: 201/160000, lr: 0.004348, eta: 2 days, 23:05:16, time: 158.34, loss: 3.9226, loss_pre: 1.0883, loss_aux0: 0.5269, loss_aux1: 0.5686, loss_aux2: 0.6657, loss_aux3: 1.0731
iter: 301/160000, lr: 0.005474, eta: 2 days, 22:42:16, time: 157.85, loss: 2.9539, loss_pre: 0.6585, loss_aux0: 0.5184, loss_aux1: 0.5175, loss_aux2: 0.5852, loss_aux3: 0.6743

There is a significant difference in training time between the two.
Thank you for taking the time to look at my question. Thank you

**Comment by CoinCheung** [comment]
What is the working status of your cpu and gpu? Maybe the speed that you feed your data from cpu memory to gpu memory brings a great latency. Maybe your gpus are not working in full load.

**Comment by ZzzTD** [comment]
@CoinCheung thanks a lot, I have solved this issue.
