### ISSUE TITLE
Agree with you

### ISSUE THREAD

**Issue by zhixuanli** [CoinCheung/BiSeNet#3]
> Therefore, I feel that the real contribution of this paper is the successful usage of the training and evaluating tricks, though the authors made little mention of these tricks and only advocates their model structures in the paper.

This phenomenon is very common now, which is very bad!!

**Comment by jetxa** [comment]
How about opening a repo to discuss the training tricks, like [Tips and tricks to make GANs work](https://github.com/soumith/ganhacks)

**Comment by zhixuanli** [comment]
@jetxa 
It's a good idea.

I have learned a lot from @CoinCheung 's code.

**Comment by jetxa** [comment]
@zhixuanli  Me too :raised_hands:

**Comment by CoinCheung** [comment]
Thanks for support !! I am closing this. Be free to open another topic if you want to discuss more.
