### ISSUE TITLE
about  the miou?

### ISSUE THREAD

**Issue by louyanyang** [CoinCheung/BiSeNet#30]
@CoinCheung  hi, thanks for your job. when reproducing your result with default hp in this repo, the miou is 75.68% with your evaluate.py, does not arrives at your report 78+%. can you give me some suggestion?

**Comment by ngunauj** [comment]
@louyanyang   Maybe the author is using trainval for training.

**Comment by louyanyang** [comment]
@ngunauj  ok ,thanks for your attention

**Comment by CoinCheung** [comment]
1. I trained on train split and evaluate on the eval split. I did not train on trainval split. I think cityscapes is not same as pascal voc in this.

2. I have no idea how you reproduced the result. Any differences in the details can bring performance difference. Please open a new issue if you find any errors in this repository, and I will be grateful and fix it.
