### ISSUE TITLE
F1 score和iou相同

### ISSUE THREAD

**Issue by fancyhhhhhh** [CoinCheung/BiSeNet#301]
感谢作者分享，我使用您实现的模型在我自己的数据集上训练，并且使用您提供的评估指令，评估了模型。我得到的表格在下面。请问F1 score和iou值完全相同，这是否是正常的

![Screenshot from 2022-11-22 19-20-33](https://user-images.githubusercontent.com/116441063/231481778-e1a5c3b4-708a-4f4e-b9d8-8b23b7ba692c.png)

**Comment by CoinCheung** [comment]
What is same? I cannot see in the picture than results are same?

**Comment by fancyhhhhhh** [comment]
不好意思，我没表述清楚。我是想实现一个二分类任务，只有前景和背景。我得到的结果是下面这样的。请问红色框的内容一样是否正常？以及黄色框中的四个结果分别对应什么？十分感谢！
![微信图片_20230413193955](https://user-images.githubusercontent.com/116441063/231747744-d848397c-d892-4316-a08a-8f989f1ec99b.png)

**Comment by CoinCheung** [comment]
Hi,

That is the field of `ratio` which means the ratio of two categories, it is computed from the ground truth and is deserved to be same, if your test set is fixed.

**Comment by chandler-wu** [comment]
正如“CoinCheung”所说，红色框里的是比例，是由你的测试集/验证集决定的。ss是单尺度，ssc是单尺度裁剪，msf是多尺度翻转，msfc是多尺度翻转+裁剪。ss\ssc\msf\msfc分别计算了f1 score和iou。
