### ISSUE TITLE
Can this model train in windows10

### ISSUE THREAD

**Issue by fry404006308** [CoinCheung/BiSeNet#302]
Can this model train in win10.
If can, how to do. 
thanks so much.

**Comment by CoinCheung** [comment]
Hi,

I do not have experience with win10. Maybe you can try to set up a virtual machine and still use linux in the virtual machine?

**Comment by fry404006308** [comment]
您好，我是范仁义，您的邮件我已经收到，我会尽快处理，谢谢。

**Comment by CoinCheung** [comment]
I am closing this since the question is answered.

**Comment by fry404006308** [comment]
您好，我是范仁义，您的邮件我已经收到，我会尽快处理，谢谢。
