### ISSUE TITLE
About the resnet weight preloading problem

### ISSUE THREAD

**Issue by hanzy123** [CoinCheung/BiSeNet#304]
Thank you for your excellent work, but I am confused about using modelzoo.load_url(resnet18_url) to download and assign weights when loading resnet, because this requires downloading the resnet18-5c106cde.pth file in advance when using it offline. After the model was built, I noticed that you still used model_final_v1_city_new.pth to copy parameters to the model, which made the previous copy work a bit redundant. I tried to modify the class Resnet18 in the resnet.py file and found that the final inference result did not change. I wonder if my modification is reasonable?

```python
from torchvision import models

    def init_weight(self):
#         state_dict = modelzoo.load_url(resnet18_url)
        state_dict = models.resnet18(pretrained=False,)
        self_state_dict = self.state_dict()
#         for k, v in state_dict.items():
#             if 'fc' in k: continue
#             self_state_dict.update({k: v})
#         self.load_state_dict(self_state_dict)
```

**Comment by CoinCheung** [comment]
What is the difference between original implementation and yours?

**Comment by CoinCheung** [comment]
I am closing this because no further communication is here. Please open new issues if you want more discussions.
