### ISSUE TITLE
请问一下如何改一下语义分割后颜色，与citys数据集分割后的颜色一致

### ISSUE THREAD

**Issue by plmoknhhh** [CoinCheung/BiSeNet#309]

**Comment by plmoknhhh** [comment]
感谢

**Comment by plmoknhhh** [comment]
我之前在github下载了deeplabv3plus的源码，里面有cityscapes的颜色映射，直接调用并且替换了

**Comment by CoinCheung** [comment]
Glad to know you have solved your problem. I am closing this.
