### ISSUE TITLE
训练的时候报错tools/train_amp.py FAILED

### ISSUE THREAD

**Issue by yangaiping** [CoinCheung/BiSeNet#313]
我按照作者您提供的训练执行命令·：
export CUDA_VISIBLE_DEVICES=0
NGPUS=1
cfg_file=configs/bisenetv2_coco.py
torchrun --nproc_per_node=$NGPUS tools/train_amp.py --config $cfg_file
遇到了如下报错问题：
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/b13ff0d4-f545-48e6-8f2e-11072bad3e44)

**Comment by CoinCheung** [comment]
Hi,

Would you please show me the full error message?

**Comment by yangaiping** [comment]
好的，谢谢您，这是完整报错信息
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/e22f2143-7c64-4afb-856f-dd53601f6f17)
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/6e73fef1-af10-43d9-a7f5-9b8f9b91c62a)

**Comment by CoinCheung** [comment]
Have you specified dataset correctly?

**Comment by yangaiping** [comment]
您好，这是我的数据集文件
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/11541341-b3c2-4032-b401-07d7fbe695ad)
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/67b1fc14-e83d-474a-8891-8aad4f036b0a)

**Comment by CoinCheung** [comment]
Did you generate `train.txt` with the method in README.txt

**Comment by yangaiping** [comment]
我刚刚发现当我执行这个代码时会生成train.txt和val.txt，但是这两个文件是空的
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/a984cf69-84d3-4d7e-9fb1-4d1c12033f1b)

**Comment by yangaiping** [comment]
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/3f4151ec-3cee-4f75-9391-c563ff15a75d)

**Comment by CoinCheung** [comment]
What is in the folder of `images` and `labels`?

**Comment by yangaiping** [comment]
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/2cbdb3f3-cb1f-472f-a82b-db21d964d8a8)
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/45e188f7-c5d2-4ff2-b790-7d225bdebd38)

**Comment by CoinCheung** [comment]
Why are these label files in format of `txt`?
![image](https://github.com/CoinCheung/BiSeNet/assets/22693362/5ce3faba-5e84-44eb-a9ab-b234d5182105)

Are you using coco-stuff dataset?

**Comment by yangaiping** [comment]
我用的是coco2017labels-segments.zip数据集

**Comment by yangaiping** [comment]
我可能已经发现了我的问题，我再试试coco-stuff dataset数据集

**Comment by yangaiping** [comment]
我已经使用了正确的数据集，并且成功划分数据集，但是训练的时候仍然报错，请问这是为什么呢
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/8e994902-5dc6-467f-85e6-303dc40afbaa)
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/b75d9896-b7b8-4c1a-bc4b-e974f1b0d3dc)

**Comment by CoinCheung** [comment]
Seems that you have hidden files in your `image/train2017` folder, and likely in your `train.txt` file, would you have a check of this?

**Comment by yangaiping** [comment]
我把隐藏的文件.ipynb_checkpoints删掉了重新执行python tools/gen_dataset_annos.py --dataset coco，然后再执行下列命令，又出现了一个新的错误
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/e1d7563e-a70d-4fb6-83ae-9470d43ceefc)
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/e9d4946d-7387-4e53-99c9-55d48ff476ff)

**Comment by CoinCheung** [comment]
```
python tools/check_dataset_info.py --im_root datasets/coco --im_anns datasets/coco/train.txt
```

What is the output of this?

**Comment by yangaiping** [comment]
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/01c2a140-1b62-4884-b0ec-e860eb899e4a)
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/6cc83252-4f91-4222-94af-73baf485ae40)

**Comment by CoinCheung** [comment]
Why does your coco-stuff has 201 categories? I used coco-stuff with only 171 classes.

You can change n_cat in the config file into 202, if you would like to use your dataset.

**Comment by yangaiping** [comment]
谢谢您，可能是我的数据集问题，我改成202后重新执行训练命令后好像成功运行了，但是我还想问怎么修改iter: 400/180000，感觉180000很大，怎么调小这个参数呢
![image](https://github.com/CoinCheung/BiSeNet/assets/109123962/9aed27bc-3544-4c51-b9aa-d5cf9e467136)

**Comment by yangaiping** [comment]
真的非常感谢您，感谢您耐心地解答我的问题，再次感谢！
