### ISSUE TITLE
关于tensorrt加速的问题

### ISSUE THREAD

**Issue by Joy2Boy** [CoinCheung/BiSeNet#315]
我是在nano板上进行的模型部署的，但是由于nano板自带tensor7.1.3的版本，我无法部署您在代码中采用的tensorrt加速代码，于是我采用了一个适配我的nano板的加速代码，但最终得到的效果很差，请问能不能提供一些解决方法或如何修改您的加速代码使得能在nano板上tensorrt7.1.3版本运行，谢谢。我采用您的tensorrt加速代码在PC端进行的分割效果图，比在nano板上运行的效果要好很多，所以我猜测是这个原因导致的。

**Comment by CoinCheung** [comment]
Good to know, I am closing this.
