### ISSUE TITLE
单卡训练报错

### ISSUE THREAD

**Issue by YyChen818** [CoinCheung/BiSeNet#316]
作者您好，我按照您提供的方法训练自己的数据集，遇到如下报错，已经查询了各种方法，减小imagesize，降低batchsize，但是错误依然存在。
![2023-08-16 15-16-20 的屏幕截图](https://github.com/CoinCheung/BiSeNet/assets/40732819/33e2eec3-5524-473b-8e88-4870a062d7b2)
期待您的回复！

**Comment by kongbai-account** [comment]
这个错误我遇到过，你可以用csdn里这个方法重试一遍
https://blog.csdn.net/qq_39149619/article/details/131882664

**Comment by YyChen818** [comment]
谢谢   我解决啦！

**Comment by XU-GITHUB-curry** [comment]
> 谢谢 我解决啦！

请问你是如何解决的呢
