### ISSUE TITLE
On COCO dataset 

### ISSUE THREAD

**Issue by shivSD** [CoinCheung/BiSeNet#32]
Do you have any pretrained weights for COCO dataset. If not do you have any train.py or script to load the COCO dataset. Appreciate any help.

**Comment by CoinCheung** [comment]
Do you mean coco stuff dataset? I am not familiar with that dataset, do you know any paper doing experiments on that?

**Comment by CoinCheung** [comment]
Sorry for being so late, maybe you do not need this anymore. But I have updated the result on cocostuff. Now that this is done, I am closing this.
