### ISSUE TITLE
about ade20k n_cats=150?

### ISSUE THREAD

**Issue by genhao3** [CoinCheung/BiSeNet#322]
As we know, ade20k has 150 categories (1-150). But in the configuration file, does n_cats=150 mean that background 0 is not included? My question is actually when we do binary segmentation tasks, background 0 is also regarded as a category. So in the ade20k dataset, is n_cats=151 correct?

**Comment by CoinCheung** [comment]
Yes, you are right. Thanks for pointing out this.
