### ISSUE TITLE
请问为何将遍历完数据集当作训练结束条件？而不是迭代次数？

### ISSUE THREAD

**Issue by 13291269328** [CoinCheung/BiSeNet#327]
![训练结束条件](https://github.com/CoinCheung/BiSeNet/assets/92571806/bede2d67-6679-4e27-8741-2d542549ec2d)

**Comment by CoinCheung** [comment]
The dataset is repeated for multi-rounds so that the number of iterations meets the settings. It is not one epoch, but multi-epoches. Therefore, here the ceasing condition is number of iterations, not dataset size.

**Comment by JJY0710** [comment]
> The dataset is repeated for multi-rounds so that the number of iterations meets the settings. It is not one epoch, but multi-epoches. Therefore, here the ceasing condition is number of iterations, not dataset size.

表示疑惑，单机单卡训练的时候，这里确实遍历完数据集就结束了，应该怎么修改呢，改成epoch形式，发现学习率更新有问题
