### ISSUE TITLE
No module named 'lib'

### ISSUE THREAD

**Issue by ccwxjsn** [CoinCheung/BiSeNet#337]

**Comment by FhilMs** [comment]
I was trying to run this project on Colab, and I met the same problem, here is the code about how I solve this problem on Colab
**import os
import sys

# 切换工作目录到项目的根目录
os.chdir('/content/BiSeNet')

# 确保正确的路径已添加到 Python 搜索路径中
sys.path.append('/content/BiSeNet')
sys.path.append('/content/BiSeNet/lib')

# 检查当前工作目录
print("Current working directory:", os.getcwd())**

**Comment by CoinCheung** [comment]
Sorry for being so late, you are likely to figure it out, after referring to FhilMs's comment. I am closing this.
