### ISSUE TITLE
Question about lr_mul in optimizer.py

### ISSUE THREAD

**Issue by uulm-mschoen** [CoinCheung/BiSeNet#42]
In the README you say, that you 'use a 10 times larger lr at the model output layers.'
When I look at your model.py, I see that you set `lr_mul` to True for these layers.
Why do you then multiply the lr by 10 for layers where `lr_mul` is set to False in the step function of your optimizer?
```
if pg.get('lr_mul', False):
  pg['lr'] = self.lr * 10
else:
  pg['lr'] = self.lr
```
For my understanding it should be exactly the other way around:
```
if pg.get('lr_mul', False):
  pg['lr'] = self.lr
else:
  pg['lr'] = self.lr * 10
```

**Comment by CoinCheung** [comment]
I do not think so, it should be the other wise.

**Comment by CoinCheung** [comment]
I am closing this since it may have been out of date and you are likely to have figured it out.
