### ISSUE TITLE
different from original paper on ARM and FFM

### ISSUE THREAD

**Issue by linbaiwpi** [CoinCheung/BiSeNet#44]
Hi, I noticed that in your implementation, the global pool block in ARM and FFM is replaced by avg_pool2d.
While in the [official implementation](https://github.com/ycszen/TorchSeg/blob/master/furnace/seg_opr/seg_oprs.py), the authors used nn.AdaptiveAvgPool2d(1).

**Comment by CoinCheung** [comment]
Yes, but I do not thinks that would bring difference if the input image size is fixed to 1024, since we need to implement a global average pooling here.
