### ISSUE TITLE
Can you provide a script to do prediction on images with the trained model?

### ISSUE THREAD

**Issue by zpge** [CoinCheung/BiSeNet#49]
Can you provide a script to do prediction on images with the trained model? like demo.py or predict.py??

**Comment by CoinCheung** [comment]
Hi, I added a [demo.py](https://github.com/CoinCheung/BiSeNet/blob/master/demo.py) script. It should work to run inference on single image. It is very simple but can work ( at least on my platform). Hope this will help you.

**Comment by zpge** [comment]
It works. Thanks a lot.
