### ISSUE TITLE
Can't download the Pretrain Model 

### ISSUE THREAD

**Issue by Mps24-7uk** [CoinCheung/BiSeNet#50]
Please upload the pretrain model to the google drive. It is really complicated to download the pretrain from pan.baidu

**Comment by CoinCheung** [comment]
Sorry, I have uploaded the pretrained weights to (google drive)[https://drive.google.com/open?id=1UMYbeaW1_wsWadZn4rR5AbQ2-YtqTKac], you can follow the link and download it.

**Comment by Mps24-7uk** [comment]
@CoinCheung Thank you so much for uploading the pretrain weights to the google drive
