### ISSUE TITLE
NaN mIOU on Test Set

### ISSUE THREAD

**Issue by dronefreak** [CoinCheung/BiSeNet#55]
Hi @CoinCheung 

When I change the mode in the  evaluation code from `val` to `test`, the mIOU is returned as NaN.
Do you have an idea what might cause this? Because the code performs well on the `val` set and I get the score that is reported in this repo.
Thanks!

**Comment by CoinCheung** [comment]
I have no idea, Does cityscapes have released test set?

**Comment by dronefreak** [comment]
Yes Indeed. The test set is now available alongwith the training and validation sets.

**Comment by songqi-github** [comment]
have you solved this problem? When I was trying to evaluate my model on test set, I got this error :
 
File "evaluate2.py", line 129, in evaluate
    N, _, H, W = label.shape
ValueError: too many values to unpack (expected 4)

then I print the label shape, which is [5, 1, 1024, 2048, 3] in test set while shape=[5, 1, 1024, 2048] in val set.
Do you meet this problem? @dronefreak @CoinCheung

**Comment by dronefreak** [comment]
Hi @songqi-github 
Yeah I have solved the issue. The issue is with our understanding of the test dataset.
Basically, the ground truths of the testing set are never released because then researchers can literally claim any mIOU score on it.
The way how it works is that you need to perform predictions in the testing images (RGB) and them convert all the label_IDs to train_IDs and then submit the predictions to the Cityscapes test server for evaluation. The server will check for true/false positives/negatives and compare your submitted predictions with the actual ground truths of the testing set, and then give you a final result. Hope this helps!

**Comment by songqi-github** [comment]
Hi @CoinCheung 
Thanks for your answer. Do you have the address of the Cityscapes test server? I didn't find anything when I searched for this. Besides, could you please share the code of converting label_IDs to train_IDs ? I would appreciate for that. Thanks

**Comment by dronefreak** [comment]
Hi,

https://www.cityscapes-dataset.com/login/
You can go the above link for the submission.

As far the conversion is concerned:
Considering your predictions are in `outputs` folder, you can run the following code. The `outputs` folder should have all the predictions in the sub-folders as `berlin` `bonn` etc.
```
import cv2
import os
import numpy as np

valid_classes = [
    7,
    8,
    11,
    12,
    13,
    17,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    31,
    32,
    33,
]

def decode_segmap_id(temp):
    ids = np.zeros((temp.shape[0], temp.shape[1]),dtype=np.uint8)
    for l in range(0, 19):
        ids[temp == l] = valid_classes[l]
    return ids

data_dir = 'outputs'
folder_list = os.listdir(data_dir)
cwd = os.getcwd()
for folder in folder_list:
	image_list = os.listdir(os.path.join(cwd, 'outputs', folder))
	for image in image_list:
		img = cv2.imread(os.path.join(cwd, 'new', folder, image), 0)
		img_new = decode_segmap_id(img)
		os.makedirs(os.path.join(cwd, 'new-2', folder), exist_ok=True)
		cv2.imwrite(os.path.join(cwd, 'new-2', folder, image), img_new)
```

**Comment by songqi-github** [comment]
Thanks and best wishes!

**Comment by dronefreak** [comment]
Closing this issue now.

**Comment by leedoge** [comment]
> Hi,
> 
> https://www.cityscapes-dataset.com/login/
> You can go the above link for the submission.
> 
> As far the conversion is concerned:
> Considering your predictions are in `outputs` folder, you can run the following code. The `outputs` folder should have all the predictions in the sub-folders as `berlin` `bonn` etc.
> 
> ```
> import cv2
> import os
> import numpy as np
> 
> valid_classes = [
>     7,
>     8,
>     11,
>     12,
>     13,
>     17,
>     19,
>     20,
>     21,
>     22,
>     23,
>     24,
>     25,
>     26,
>     27,
>     28,
>     31,
>     32,
>     33,
> ]
> 
> def decode_segmap_id(temp):
>     ids = np.zeros((temp.shape[0], temp.shape[1]),dtype=np.uint8)
>     for l in range(0, 19):
>         ids[temp == l] = valid_classes[l]
>     return ids
> 
> data_dir = 'outputs'
> folder_list = os.listdir(data_dir)
> cwd = os.getcwd()
> for folder in folder_list:
> 	image_list = os.listdir(os.path.join(cwd, 'outputs', folder))
> 	for image in image_list:
> 		img = cv2.imread(os.path.join(cwd, 'new', folder, image), 0)
> 		img_new = decode_segmap_id(img)
> 		os.makedirs(os.path.join(cwd, 'new-2', folder), exist_ok=True)
> 		cv2.imwrite(os.path.join(cwd, 'new-2', folder, image), img_new)
> ```

hello! Do you know how to test on the official link of cityscapes(just as you said) in multi-scales?thank you very much!!!

**Comment by dronefreak** [comment]
Hello @leedoge 
Multi-scale evaluation is theoretically part of your evaluation script. For example, refer to the code `evalute.py` written by @CoinCheung 
In that code you will see that multi-scale evaluation exists in the form of a for-loop. Please note that the Cityscapes server provides for evaluation on the test set, but I am not sure if there is a separate server for multi-scale evaluation. Multi-scale evaluation is a trick to improve the results by a slight margin, and hence it is adopted while generating the output predictions themselves and not on the official servers of Cityscapes.

**Comment by leedoge** [comment]
thank you! Now i see. But if i want to get a better result through multi-scales strategy , what should i do?Can i output multi-scales predictions and test it on cityscapes sever? and then caculate the mean iou of different scales by myself?

**Comment by dronefreak** [comment]
I will be more specific this time. Consider the following snippet from `evaluate.py`:
```
    def evaluate(self):
        ## evaluate
        n_classes = self.n_classes
        hist = np.zeros((n_classes, n_classes), dtype=np.float32)
        dloader = tqdm(self.dl)
        if dist.is_initialized() and not dist.get_rank()==0:
            dloader = self.dl
        for i, (imgs, label) in enumerate(dloader):
            N, _, H, W = label.shape
            probs = torch.zeros((N, self.n_classes, H, W))
            probs.requires_grad = False
            imgs = imgs.cuda()
            for sc in self.scales:
                prob = self.scale_crop_eval(imgs, sc)
                probs += prob.detach().cpu()
            probs = probs.data.numpy()
            preds = np.argmax(probs, axis=1)

            hist_once = self.compute_hist(preds, label.data.numpy().squeeze(1))
            hist = hist + hist_once
        IOUs = np.diag(hist) / (np.sum(hist, axis=0)+np.sum(hist, axis=1)-np.diag(hist))
        mIOU = np.mean(IOUs)
        return mIOU
```
In this snippet, there is a for-loop in the middle which iterates through the different set of scales `scales = [0.5, 0.75, 1, 1.25, 1.5, 1.75]` and uses the results from all scales. This is a typical setup for multi-scale evaluation. Once you generate your predictions and save them as images, you can upload them to the official Ctyscapes servers and get your results (essentially multi-scale). For a more detailed understanding, consider reading the `evaluate.py` completely. Hope this helps.

**Comment by leedoge** [comment]
@dronefreak i see! thank you very much. you are really a good man!
