### ISSUE TITLE
inplace_abn

### ISSUE THREAD

**Issue by TianMingChen** [CoinCheung/BiSeNet#57]
when I install inplace_abn,I get this problem.
 
nvcc fatal   : Unsupported gpu architecture 'compute_61'
error: command '/usr/bin/nvcc' failed with exit status 1

**Comment by CoinCheung** [comment]
what is your gpu and cuda version?

**Comment by TianMingChen** [comment]
> what is your gpu and cuda version?

My GPU is 1080 and cuda is cuda9.0

**Comment by CoinCheung** [comment]
weird what is your pytorch version, are you using anaconda, please remove ananconda paths from your `PATH` environmental variable.

**Comment by TianMingChen** [comment]
> weird. What is your pytorch version, are you using anaconda, please remove ananconda paths from your `PATH` environmental variable.

well ,I will have a test

**Comment by CoinCheung** [comment]
Closing this since no further message is posted, please open new issues if you still want to communicate.
