### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by Mps24-7uk** [CoinCheung/BiSeNet#58]
How do I resume training from the Checkpoint?

**Comment by CoinCheung** [comment]
Hi, I update a bit about loading checkpoint. you may try to train like this: 
```
python -m torch.distributed.launch --nproc_per_node=2 train.py --ckpt /path/to/you/model.pth
```
I have not tested it sufficiently, if you find any errors, please leave a message.

**Comment by CoinCheung** [comment]
Closing this since you might have found out the solutions to your task.
