### ISSUE TITLE
one problem

### ISSUE THREAD

**Issue by TianMingChen** [CoinCheung/BiSeNet#60]
when I run the bisenetv2,have this problem ,do you have some solution?
![image](https://user-images.githubusercontent.com/20785298/83374094-29b4f580-a3fd-11ea-81b6-51ff2b2012b5.png)
![image](https://user-images.githubusercontent.com/20785298/83374131-405b4c80-a3fd-11ea-8084-f028e9fd2330.png)
![image](https://user-images.githubusercontent.com/20785298/83374143-49e4b480-a3fd-11ea-92d7-2cb55cded32b.png)

**Comment by CoinCheung** [comment]
I am closing this since it is duplicated with [#67](https://github.com/CoinCheung/BiSeNet/issues/67).
