### ISSUE TITLE
bisenet v2 mIOU

### ISSUE THREAD

**Issue by TianMingChen** [CoinCheung/BiSeNet#61]
when i run the bisenetv2,the loss is high,but get mIOU73.5%,could help me have a look?

![image](https://user-images.githubusercontent.com/20785298/83587898-b937e100-a582-11ea-8d38-47d1058d83ec.png)

**Comment by ncuxiaogang** [comment]
The loss is the total sum loss of the multi-branch.

**Comment by TianMingChen** [comment]
> The loss is the total sum loss of the multi-branch.

ok,thank you!
