### ISSUE TITLE
n_min setting

### ISSUE THREAD

**Issue by songqi-github** [CoinCheung/BiSeNet#63]
n_min = n_img_per_gpu*cropsize[0]*cropsize[1]//16
criteria_p = OhemCELoss(thresh=score_thres, n_min=n_min, ignore_lb=ignore_idx)
what's the meaning of n_min? what if i have only one GPU with batchsize 6? Is that 
n_min = cropsize[0]*cropsize[1] ?
Thanks!

**Comment by CoinCheung** [comment]
It is a setting of ohem strategy. It means that if most samples are "easy" samples, at least `n_min` samples should be used to train the model. It is added to prevent ignoring too many training samples.

**Comment by CoinCheung** [comment]
I am closing this since there seems to be no further problem. Thanks for your interest.
