### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by umairanis03** [CoinCheung/BiSeNet#68]
Thanks for your wonderful work.

I am not able to access pan Baidu, hence not able to download the pre-trained model. 
Can someone please upload it's drive link or mail it to anis.1@iitj.ac.in

**Comment by SharifElfouly** [comment]
Hey, thanks to @CoinCheung here is the [link](https://drive.google.com/drive/folders/1UMYbeaW1_wsWadZn4rR5AbQ2-YtqTKac).

**Comment by JingshanXu** [comment]
> Hey, thanks to @CoinCheung here is the [link](https://drive.google.com/drive/folders/1UMYbeaW1_wsWadZn4rR5AbQ2-YtqTKac).

hi, it's the pre-trained model of v1 or v2

**Comment by CoinCheung** [comment]
You might have figured it out, so I am closing this.
