### ISSUE TITLE
training iterations

### ISSUE THREAD

**Issue by Aenteas** [CoinCheung/BiSeNet#69]
Hi,
In bisenetv2/train.py you have a single training epoch as there is one for loop on the dataloader. After I run the code it only runs for a few thousand iterations. Defining an outer loop: for epoch in epochs would solve this problem, but I feel like I am missing something. Do you have the default 151000 iterations during training?

**Comment by CoinCheung** [comment]
Yes, in the paper, they train 150k iterations, and since I warmed up for 1k iteration, I use 151k iterations. It is actually not trained for only one epoch. You may find the implementation of sampler [here](https://github.com/CoinCheung/BiSeNet/blob/master/bisenetv2/sampler.py).

**Comment by CoinCheung** [comment]
Closing this. Be my guest to leave a message if you have more to communicate.
