### ISSUE TITLE
您好，错误：ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by PenghuahuaPeng** [CoinCheung/BiSeNet#7]
请问您遇到过吗？另外gpu迁移到cpu检测复杂吗？

**Comment by CoinCheung** [comment]
Use English if you please, for others' convenience. 

I did not met problems about ninja, my ninja version is 1.8.2.post2. You may install this and see if the problem can be solved. Hope this would help.

**Comment by CoinCheung** [comment]
As for evaluating on cpu.  You may check the `evaluate.py` script and replace lines containing `.cuda()` with their corresponding cpu version.
