### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by songqi-github** [CoinCheung/BiSeNet#72]
Hi, what's your inference time of BiSeNetV2 ?

**Comment by CoinCheung** [comment]
I have not tested it yet, maybe I will do it in the near future when I have enough time to look at it.

**Comment by JustWannaHugU** [comment]
> I have not tested it yet, maybe I will do it in the near future when I have enough time to look at it.

Hi，Old Coin，now can you answer the question :"what's your inference time of BiSeNetV2" ?

**Comment by CoinCheung** [comment]
Hi,

On my Tesla T4 gpu with fp16 mode, the bisenetv2 fps is 50, and with fp32 mode, the fps is 16...

I tested it with input size of 1024x2048. 

T4 is much slower than 2080ti, I do not have 2080ti now, but I have upload the method and code how I test this. If you have other gpus, you can test it on your platform.

I am closing this, you can still leave a message or open new issues if you want more discussions.
