### ISSUE TITLE
unable to access the BiSeNetV2 pre-trained model using google drive

### ISSUE THREAD

**Issue by earlysleepearlyup** [CoinCheung/BiSeNet#73]
I am unable to access the BiSeNetV2 pre-trained model using google drive. Can you please provide me it's access permission: li.ying@cidi.ai. Thank you!

**Comment by CoinCheung** [comment]
Hi, 
You can download from baidu pan link of [bisenetv1](https://pan.baidu.com/s/1K-TafW8XC9fszm-FmR-Jhw)(extract code: 8pju) and [bisenetv2](https://pan.baidu.com/s/1smgpJT0ItE5xMtooxvAT3w)(extract code: yik9).

**Comment by CoinCheung** [comment]
I am closing this, please be free to open new issues for more communication.
