### ISSUE TITLE
Confused about applying colorjitter augment to mask.

### ISSUE THREAD

**Issue by hot-dog** [CoinCheung/BiSeNet#74]
Hi there, when read the source code, i am confused about the data augmentation operations, it seems that colorjitter augmentation is applyed both to image and mask, mask will be randomly changed. Is this a mistake or i am thinking wrong?

**Comment by CoinCheung** [comment]
Hi, 
Would you please tell me from which line shows that the colorjitter is applied to both image and labels ?

**Comment by hot-dog** [comment]
sorry, i looked into transform_cv2.py and found that colorjitter is not applyed to mask, i made a mistake. Issue closed.
