### ISSUE TITLE
About hyper-parameters in OhemCELoss

### ISSUE THREAD

**Issue by Mayy1994** [CoinCheung/BiSeNet#76]
Thanks for sharing the code with us

I have encountered some problems with OhemCELoss.
In _train.py_, I see you constructed the OhemCELoss like this:
```
 score_thres = 0.7
 n_min = n_img_per_gpu*cropsize[0]*cropsize[1]//16
 criteria_p = OhemCELoss(thresh=score_thres, n_min=n_min, ignore_lb=ignore_idx)
```
Could you please share with me the experiences in how to determine the hyper-parameters  _n_min_ and _score_thres_?

Many thanks in advance

**Comment by CoinCheung** [comment]
hi,

From my personal observation, there is no conspicuous routine of setting these hyper-parameters. You can just try different values according to different models and datasets. Or you can just fix these parameters to default values and adjust other parameters, before trying these parameters.

**Comment by Mayy1994** [comment]
I see. Thanks for your reply~
