### ISSUE TITLE
 The inference of example.png

### ISSUE THREAD

**Issue by mzmzdcr** [CoinCheung/BiSeNet#79]
when I finished the train/val ，single mIOU is: 0.73  single scale crop mIOU is: 0.747 ms flip mIOU is: 0.746 ms crop mIOU is: 0.756
I wanted to test the model's performance on an image. So, I run the demo.py. But the prediction given by the model was far inferior to the examples in the paper.
Can someone tell me what went wrong and how to solve it？

**Comment by mzmzdcr** [comment]
![res](https://user-images.githubusercontent.com/38181266/91677227-ac705c80-eb74-11ea-930f-e3b5a60df4d6.jpg)

**Comment by CoinCheung** [comment]
miou of 70 is not a state of the art, so it is reasonable to see this.
