### ISSUE TITLE
Very poor result

### ISSUE THREAD

**Issue by rose-jinyang** [CoinCheung/BiSeNet#81]
Hello
How are you?
Thanks for contributing this project.
I tested two images for human segmentation with the pre-trained BiSeNetv2 model.
The input images are following.
![1](https://user-images.githubusercontent.com/47862419/92007750-e7db7880-ed78-11ea-8dae-41de0a6c0f68.jpg)
![2](https://user-images.githubusercontent.com/47862419/92007940-178a8080-ed79-11ea-89c9-56627b689f6f.jpg)

The results are following.
![res](https://user-images.githubusercontent.com/47862419/92008378-adbea680-ed79-11ea-9298-6b12bd0bcfcc.jpg)
![res](https://user-images.githubusercontent.com/47862419/92007994-2a9d5080-ed79-11ea-9854-06a5d0cdab73.jpg)

How can I understand this?
Thanks

**Comment by JustWannaHugU** [comment]
Hello， I think the result is your training data is limited in Auto-Driving sense，so， why not try a traffic sense picture ？

**Comment by CoinCheung** [comment]
Close with love & peace.
