### ISSUE TITLE
problem about training log

### ISSUE THREAD

**Issue by yongguanjiangshan** [CoinCheung/BiSeNet#82]
hi, thank you for the contribution.
i learn a lot from your code.
here is my question. when training, the log outputs two results each 100 inter. 
such as below. do you know why?

`iter: 100/151000, lr: 0.006295, eta: 1 day, 3:01:43, time: 65.13, loss: 5.2069, loss_pre: 0.6938, loss_aux0: 1.2169, loss_aux1: 0.9999, loss_aux2: 1.1010, loss_aux3: 1.1953`
`iter: 100/151000, lr: 0.006295, eta: 1 day, 3:01:46, time: 65.13, loss: 4.3021, loss_pre: 0.5993, loss_aux0: 1.0043, loss_aux1: 0.7578, loss_aux2: 0.9266, loss_aux3: 1.0140`
`iter: 200/151000, lr: 0.007924, eta: 1 day, 2:02:22, time: 59.82, loss: 5.5728, loss_pre: 1.1768, loss_aux0: 1.2945, loss_aux1: 1.1485, loss_aux2: 1.0133, loss_aux3: 0.9397`
`iter: 200/151000, lr: 0.007924, eta: 1 day, 2:02:24, time: 59.82, loss: 6.6900, loss_pre: 0.8763, loss_aux0: 1.6241, loss_aux1: 1.4571, loss_aux2: 1.5158, loss_aux3: 1.2166`
`iter: 300/151000, lr: 0.009976, eta: 1 day, 1:37:55, time: 59.35, loss: 8.0209, loss_pre: 2.0541, loss_aux0: 1.8272, loss_aux1: 1.5216, loss_aux2: 1.2999, loss_aux3: 1.3181`
`iter: 300/151000, lr: 0.009976, eta: 1 day, 1:37:55, time: 59.36, loss: 8.0241, loss_pre: 2.3563, loss_aux0: 1.5317, loss_aux1: 1.4104, loss_aux2: 1.3514, loss_aux3: 1.3743`
`iter: 400/151000, lr: 0.012559, eta: 1 day, 1:27:22, time: 59.71, loss: 7.5488, loss_pre: 1.4626, loss_aux0: 2.1464, loss_aux1: 1.4746, loss_aux2: 1.2468, loss_aux3: 1.2185`
`iter: 400/151000, lr: 0.012559, eta: 1 day, 1:27:30, time: 59.73, loss: 6.4421, loss_pre: 1.6951, loss_aux0: 1.6171, loss_aux1: 1.1467, loss_aux2: 1.0038, loss_aux3: 0.9794`

**Comment by CoinCheung** [comment]
How did you setup training ? I did not observe this in my practice.

**Comment by yongguanjiangshan** [comment]
hi, i just use my own dataset. and didn't change the parameters. But when i train with your code, the output is normal. It is weird.

**Comment by CoinCheung** [comment]
May be you have solved this problem, I am closing this.
