### ISSUE TITLE
Support of Custom dataset

### ISSUE THREAD

**Issue by rose-jinyang** [CoinCheung/BiSeNet#83]
Hello
How are you?
Thanks for contributing this project.
I am going to train a new model with the supervisely-person-dataset.
How can I prepare the training dataset?
Could u provide a best script?
Thanks.

**Comment by kubitz** [comment]
see issue #47

**Comment by zoe218** [comment]
> Hello
> How are you?
> Thanks for contributing this project.
> I am going to train a new model with the supervisely-person-dataset.
> How can I prepare the training dataset?
> Could u provide a best script?
> Thanks.

hello~Have you tried bisenetv2 on the person dataset?

**Comment by zoe218** [comment]
@rose-jinyang

**Comment by CoinCheung** [comment]
I am closing this, since this feature is added, and maybe you have figured out your solution of this already.
