### ISSUE TITLE
How can I run on cpu??

### ISSUE THREAD

**Issue by wangjing60755** [CoinCheung/BiSeNet#86]
When I run on cpu,,

 dist.init_process_group(
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'

**Comment by CoinCheung** [comment]
Are you going to train your model with cpu ? That would be very slow.

**Comment by wangjing60755** [comment]
> Are you going to train your model with cpu ? That would be very slow.



> Are you going to train your model with cpu ? That would be very slow.

I need to test something on cpu，I can,t care speed,so ，how can I run on cpu?

**Comment by CoinCheung** [comment]
Have you ever refer to the `tools/demo.py` for inference ?

**Comment by CoinCheung** [comment]
Please post the details of how you tried to run inference if you still have problem. I cannot determine what the problem is from two lines of error message.

**Comment by wangjing60755** [comment]
> Please post the details of how you tried to run inference if you still have problem. I cannot determine what the problem is from two lines of error message.

I can run tools/demo.py ok!
When I run tools/train.py ,I meet 
:
Traceback (most recent call last):
  File "E:/Segment_datasets_hands/BiSeNet-master/tools/train.py", line 236, in <module>
    main()
  File "E:/Segment_datasets_hands/BiSeNet-master/tools/train.py", line 224, in main
    dist.init_process_group(
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'

**Comment by CoinCheung** [comment]
So you want to train you model with cpu, am I right ?

Training with cpu is not supported, since until now the speed of training on cpu is very slow... You can try to remove code associated with distributed and fp16 training, and see if it will work...
