### ISSUE TITLE
I have a problem about training

### ISSUE THREAD

**Issue by lk1048453160** [CoinCheung/BiSeNet#90]
![2020-10-24 13-09-24 的屏幕截图](https://user-images.githubusercontent.com/54702384/97068442-3deece80-15fa-11eb-949f-54a1af3e1fe3.png)
just like this. I need you help. Thanks~

**Comment by CoinCheung** [comment]
I cannot open this image. Have you figured it out? If not, please paste the error message so that I can have a bit insight on this.

**Comment by CoinCheung** [comment]
Closing this since it is not activate for so much time that you might have solved this problem now.
