### ISSUE TITLE
bisenet v2 has a lower performance than v1? what happens?

### ISSUE THREAD

**Issue by zhaoyin214** [CoinCheung/BiSeNet#94]
in this repo, it reported that the performance of v2 is lower than v1 but with 2x more parameters and longer inference time. it is quite different from the results reported by your paper. is there something wrong?

| none | ss | ssc | msf | mscf | fps(fp16/fp32) | link |
|------|:--:|:---:|:---:|:----:|:---:|:----:|
| bisenetv1 | 75.55 | 76.90 | 77.40 | 78.91 | 60/19 | [download](https://drive.google.com/file/d/140MBBAt49N1z1wsKueoFA6HB_QuYud8i/view?usp=sharing) |
| bisenetv2 | 74.12 | 74.18 | 75.89 | 75.87 | 50/16 | [download](https://drive.google.com/file/d/1qq38u9JT4pp1ubecGLTCHHtqwntH0FCY/view?usp=sharing) |

**Comment by CoinCheung** [comment]
How did you figure out the conclusion of " with 2x more parameters" ?  I tested it with T4 gpu and cropsize of 1024x2048 and tensorrt 7 which is not aligned with paper. Besides, some details are not given in the paper, there might be some difference between my implementation and paper. I have talked about my changes in the README.md.

**Comment by zhaoyin214** [comment]
i have downloaded the pretrained weights you provided, and the size of bisenetv2 is 2x that of v1, more or less

> How did you figure out the conclusion of " with 2x more parameters" ? I tested it with T4 gpu and cropsize of 1024x2048 and tensorrt 7 which is not aligned with paper. Besides, some details are not given in the paper, there might be some difference between my implementation and paper. I have talked about my changes in the README.md.

**Comment by CoinCheung** [comment]
That is because I did not remove the auxiliary layers which are used to  compute aux losses for the deeply supervision during training. These layers have many parameters.

**Comment by zhaoyin214** [comment]
anyway, it is a good re-implementation, helps a lot for me reading the paper and this net is one of my favorites, thanks a lot

> That is because I did not remove the auxiliary layers which are used to compute aux losses for the deeply supervision during training. These layers have many parameters.

**Comment by CoinCheung** [comment]
Thanks for noticing this implementation !! I am closing this.
