### ISSUE TITLE
Issue with conver_to_trt.py 

### ISSUE THREAD

**Issue by michieljanssen97** [CoinCheung/BiSeNet#95]
Hi @CoinCheung,

I'm struggling to convert my BiSenet '.pth' model to TensorRT. I tried to use your 'conver_to_trt.py' but didn't succeed in the conversion. I'm getting this error:

**AttributeError: 'Tensor' object has no attribute '_trt'**

Can you help me?

Thanks, 

Michiel

**Comment by CoinCheung** [comment]
Please follow the [specification](https://github.com/CoinCheung/BiSeNet/tree/master/tensorrt). I did not convert from pytorch to tensorrt directly, I first export from pytorch to onnx before converting to tensorrt.

**Comment by CoinCheung** [comment]
Since you might have solved your problem, I am closing this.
